- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
Ready for merging on 16th March :tada:
> Add github corner badge

- Gemfile
- Gemfile.lock
Saving this for once the queue has died down a bit
> Update sidekiq unique jobs

- app/models/github_repository.rb
- app/models/github_tag.rb
- app/models/version.rb
For merging after the queue has died back down
> Revert quickfixes

- app/models/github_issue.rb
- app/models/github_repository.rb
- app/models/github_user.rb
- db/migrate/20160403154201_create_github_issues.rb
- db/migrate/20160404181210_add_last_synced_at_to_github_issues.rb
- db/migrate/20160404181516_add_indexes_to_github_issues.rb
- db/migrate/20160404181835_add_pull_request_to_github_issues.rb
- db/migrate/20160405065854_add_last_synced_at_to_github_repositories.rb
- db/schema.rb
Fixes #159, replaces #206 
Todo:
> Store Github issues

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/admin/github_repositories/_github_repository.html.erb
- app/views/admin/project_suggestions/_project_suggestion.html.erb
- app/views/admin/stats/index.html.erb
- app/views/dashboard/_new_version.html.erb
- app/views/dashboard/index.html.erb
- app/views/github_repositories/_github_repository.html.erb
- app/views/github_repositories/show.html.erb
- app/views/projects/_project.html.erb
- app/views/projects/_statistics.html.erb
- app/views/projects/bus_factor.html.erb
- app/views/subscriptions/_subscription.html.erb
- config/application.rb
> Add timeago plugin for dynamic time ago in words

- app/models/github_issue.rb
- 'E-Easy' is what the Rust world use.
> Add further FIRST_PR_LABELS

- app/views/web_hooks/index.html.erb
Some words are missing in this sentence. I’m not sure these are the words you were going for, but this at least makes sense to me ¯\_(ツ)_/¯
> [WebHook] Fix explanation copy.

- app/views/api/docs/index.html.erb
A follow-up to https://github.com/librariesio/libraries.io/pull/743
> document maximum value of per_page query param (100)

- app/views/versions_mailer/new_version.html.erb
- app/views/versions_mailer/new_version.text.erb
I'd prefer not to get emails, but the link in the email was misleading.
> Add link in emails to opt out of emails.

- app/assets/stylesheets/_highlight.scss
- app/assets/stylesheets/application.scss
Code in readmes was already annotated with useful classnames, so this just adds some github-like styles for those elements 🌈.
> Add syntax highlighting styles

- app/helpers/application_helper.rb
- app/models/github_organisation.rb
- app/models/github_tag.rb
- app/models/github_user.rb
- app/models/project.rb
- app/models/repositories/atom.rb
- app/models/repositories/carthage.rb
- app/models/repositories/inqlude.rb
- app/models/repositories/julia.rb
- app/models/repositories/npm.rb
- app/models/user.rb
- app/models/version.rb
- config/routes.rb
> Fixed up serious rubocop warnings

- spec/cassettes/GithubRepository/1_16.yml
- spec/cassettes/GithubRepository/1_17.yml
- spec/factories.rb
- spec/models/github_repository_spec.rb
- spec/models/github_tag_spec.rb
- spec/models/manifest_spec.rb
- spec/models/project_mute_spec.rb
- spec/models/project_spec.rb
- spec/models/project_suggestion_spec.rb
- spec/models/readme_spec.rb
- spec/models/repository_dependency_spec.rb
- spec/models/repository_permission_spec.rb
- spec/models/repository_subscription_spec.rb
- spec/models/subscription_spec.rb
- spec/models/user_spec.rb
- spec/models/version_spec.rb
- spec/models/web_hook_spec.rb
Working towards better test coverage 💯
> More model specs

- Gemfile.lock
fixes #886 
I am guessing seeing this PR's code climate come back is proof this works?
> upgrade code-climate-test-reporter to 1.0.3

- app/helpers/tree_helper.rb
- app/views/tree/_dep.html.erb
- app/views/tree/show.html.erb
> Extract dependency tree resolver from view

- app/controllers/tree_controller.rb
- app/models/tree_resolver.rb
- app/views/tree/show.html.erb
> Move tree renderer into a separate class

- app/controllers/tree_controller.rb
- app/models/tree_resolver.rb
> Cache dependency trees for one day

- db/migrate/20161122104700_add_dependent_repos_count_to_projects.rb
- db/schema.rb
> Cache dependent repo counts

- app/models/project.rb
> Start updating dependent_repos_count

- app/controllers/collections_controller.rb
- app/controllers/keywords_controller.rb
- app/controllers/languages_controller.rb
- app/controllers/licenses_controller.rb
- app/controllers/platforms_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/search_controller.rb
- app/controllers/users_controller.rb
- app/models/project.rb
Removes 4-6 unnecessary sql queries on many overview pages
> Don't eager load versions with lists of projects

- app/views/explore/index.html.erb
Update the trending more often and sidebar less often
> Tweak explore page cache expiry times

- app/controllers/keywords_controller.rb
- app/controllers/languages_controller.rb
- app/controllers/licenses_controller.rb
- app/controllers/platforms_controller.rb
- app/models/concerns/source_rank.rb
- app/models/project.rb
- app/views/keywords/show.html.erb
- app/views/languages/show.html.erb
- app/views/licenses/show.html.erb
- app/views/platforms/show.html.erb
- app/views/projects/_statistics.html.erb
Part 3 of #912
Need to wait for the background task to finish updating all 1.9m projects before deploying
> Use dependent_repos_count instead of counting

- app/assets/stylesheets/application.scss
- app/controllers/github_repositories_controller.rb
- app/models/concerns/repo_urls.rb
- app/views/github_repositories/contributors.html.erb
> Improved repo contributor page with more stats

- app/assets/stylesheets/application.scss
Fix for #925.
I tried this just by tinkering with devtools because my checked out version of libraries isn't currently functional so please check it ⚠️ 😄
> Prevent project text from overflowing out of container, fixes #925

- Gemfile.lock
Fixes #944 and also fixes #945
> Update minitest to 5.10.1

- app/controllers/api/github_issues_controller.rb
- app/controllers/application_controller.rb
- app/controllers/github_issues_controller.rb
- app/models/concerns/issue_search.rb
- app/models/user.rb
- app/views/github_issues/your_dependencies.html.erb
- config/routes.rb
> Browse open issues on your dependencies

- app/controllers/github_repositories_controller.rb
- app/controllers/users_controller.rb
- app/models/github_organisation.rb
- app/models/github_repository.rb
- app/models/github_user.rb
- app/views/github_repositories/dependency_issues.html.erb
- app/views/users/dependency_issues.html.erb
- app/views/users/issues.html.erb
- config/routes.rb
Not linked anywhere yet as the issue data needs more syncing but here's the example urls:
- https://libraries.io/github/andrew/contribulator/dependency-issues
- https://libraries.io/github/andrew/dependency-issues
Also an extra one:
- https://libraries.io/github/andrew/issues
> User issues

- app/controllers/tree_controller.rb
- app/models/concerns/dependency_checks.rb
- app/models/tree_resolver.rb
- app/views/tree/_tree.html.erb
- app/views/tree/show.html.erb
- app/workers/tree_resolver_worker.rb
> Allow passing a date to the tree resolver to enable time traveling 

- app/controllers/api/tree_controller.rb
Adds the same data param as https://github.com/librariesio/libraries.io/pull/978 but to the API version of the tree resolver.
Example: https://libraries.io/api/npm/base62/tree?kind=Development&date=2014/7/15&api_key=XX
> Allow time travelling in dependency tree api

- app/models/github_organisation.rb
- app/models/github_user.rb
- app/views/users/show.html.erb
- db/migrate/20161213123856_rename_org_description_to_bio.rb
- db/schema.rb
Part 1 and 2 of https://github.com/librariesio/libraries.io/issues/668
> Rename org description field to bio

- Gemfile
- Gemfile.lock
- config/sitemap.rb
> Generate sitemaps in parallel, fixes #986

- README.md
Updated instruction in README to include redis and a few extra details to help clarify the process.
> Setup update in README

- README.md
Documentation for setting up Github auth and kicking off the Sidekiq workers.
> Added some more setup docs to README

- app/controllers/application_controller.rb
Fixes https://github.com/librariesio/libraries.io/issues/1009
> Added source of dependency to API output

- app/controllers/admin/stats_controller.rb
- app/models/application_record.rb
- app/views/admin/_nav.html.erb
- app/views/admin/stats/overview.html.erb
- config/routes.rb
Fixes #1043
Currently looks something like this:
> Added admin overview page

- app/controllers/application_controller.rb
- app/controllers/github_repositories_controller.rb
- app/controllers/repository_tree_controller.rb
- app/controllers/web_hooks_controller.rb
- app/models/github_repository.rb
- app/models/repository_tree_resolver.rb
- app/models/version.rb
- app/views/repository_tree/_dep.html.erb
- app/views/repository_tree/_dependency.html.erb
- app/views/repository_tree/_tree.html.erb
- app/views/repository_tree/show.html.erb
- app/workers/repository_tree_resolver_worker.rb
- config/routes.rb
- spec/cassettes/GithubDownloadForkWorker/should_download_a_repos_forks.yml
- spec/cassettes/GithubDownloadWorker/should_update_all_info_for_a_repo.yml
- spec/cassettes/GithubIssuesWorker/should_update_repo_for_a_project.yml
- spec/cassettes/RepositoryTreeController/GET_/_platform/_project/tree/renders_successfully_when_logged_out.yml
- spec/cassettes/TagNotificationsWorker/should_send_tag_notifications.yml
- spec/cassettes/UpdateRepositorySourceRankWorker/should_update_sourcerank_for_a_repo.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/_id/edit/denies_access_when_logged_out.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/_id/edit/denies_access_when_user_doesnt_have_pull_access_to_repo.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/_id/edit/renders_successfully_for_logged_in_users.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/denies_access_when_logged_out.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/denies_access_when_user_doesnt_have_pull_access_to_repo.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/new/denies_access_when_logged_out.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/new/denies_access_when_user_doesnt_have_pull_access_to_repo.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/new/renders_successfully_for_logged_in_users.yml
- spec/cassettes/WebHooksController/GET_/github/_owner/_name/web_hooks/renders_successfully_for_logged_in_users.yml
- spec/requests/repository_tree_spec.rb
> Repository tree resolver

- app/controllers/api/tree_controller.rb
- app/controllers/tree_controller.rb
- app/models/package_manager/atom.rb
- app/models/package_manager/dub.rb
- app/models/package_manager/haxelib.rb
- app/models/package_manager/hex.rb
- app/models/package_manager/npm.rb
- app/models/package_manager/nu_get.rb
- app/models/package_manager/packagist.rb
- app/models/package_manager/pub.rb
- app/models/package_manager/rubygems.rb
- app/models/repository_tree_resolver.rb
- app/models/tree_resolver.rb
- app/models/version.rb
- app/views/projects/_statistics.html.erb
- app/views/projects/show.html.erb
- app/views/repository_tree/_dependency.html.erb
- app/views/tree/_dependency.html.erb
- app/views/tree/show.html.erb
- spec/requests/api/tree_spec.rb
- spec/workers/tree_resolver_worker_spec.rb
> Rename dependency kind of "normal" to "runtime"

- Gemfile
- Gemfile.lock
- app/assets/javascripts/admin.js
- app/assets/javascripts/application.js
- app/controllers/admin/stats_controller.rb
- app/views/admin/stats/graphs.html.erb
- config/initializers/assets.rb
- config/routes.rb
- spec/cassettes/Admin_StatsController/GET_/admin/graphs/denies_access_for_non-admins.yml
- spec/cassettes/Admin_StatsController/GET_/admin/graphs/renders_successfully_for_admins.yml
- spec/requests/admin/stats_spec.rb
Adds graphs so we can spot for any potential problems in package manager downloading
> Add project and version frequency graphs to admin

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/layouts/application.html.erb
**headlines**
1) Enable turbolinks again, see (https://github.com/librariesio/libraries.io/issues/1055)
**TODOs**
> enable turbolinks5

- app/models/repository.rb
- lib/tasks/one_off.rake
Prequest for https://github.com/librariesio/libraries.io/pull/1110
Also needs to set the `host_type` on newly created repos from github
> Add rake task to set value of host_type for all existing repos

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/projects/unsung_heroes.html.erb
- config/routes.rb
A page to show heavily depended on libraries that have few stars on GitHub to help promote some of the hard working but under appreciated libraries many communities depend upon. 🏆
> Added Unsung Heroes page

- app/models/repository.rb
Fixes #1173
Refactors internal `Repository` methods to `send` based on the `host_type`.
> Refactor Repository host_type conditionals

- app/models/concerns/github_project.rb
- app/models/package_manager/base.rb
- app/models/package_manager/bower.rb
- app/models/package_manager/carthage.rb
- app/services/github_url_parser.rb
- spec/services/bitbucket_url_parser_spec.rb
- spec/services/github_url_parser_spec.rb
- spec/services/gitlab_url_parser_spec.rb
To have `BitbucketURLParser`, `GitlabURLParser`, and `GithubURLParser` all live in the same repository.
> Un-extraction of the github_urls gem

- app/models/concerns/bitbucket_repository.rb
- app/models/concerns/github_repository.rb
- app/models/concerns/gitlab_repository.rb
- app/models/repository.rb
- app/models/repository_host/base.rb
- app/models/repository_host/bitbucket.rb
- app/models/repository_host/github.rb
- app/models/repository_host/gitlab.rb
If 👍 on this architecture, I can begin to move code over to the different `RepositoryHost::Base` subclasses.
cc @andrew
> Create RepositoryHost classes

- app/controllers/pages_controller.rb
- app/views/pages/_contact.html.erb
- app/views/pages/_who.html.erb
- app/views/pages/about.html.erb
- app/views/pages/compatibility.html.erb
- app/views/pages/pmmatrix.html.erb
- config/routes.rb
- spec/cassettes/PagesController/GET_/packagemanagercompatibility/renders_successfully_when_logged_out.yml
- spec/requests/pages_spec.rb
* break out _who and _contact partials
* re-write /about page to be more usage focussed
* add section on strategy 
* add section on contributing 
Closes #1128
> Clean up about page and move compatibility matrix

- app/assets/stylesheets/application.scss
- app/controllers/pages_controller.rb
- app/views/layouts/_footer.html.erb
- app/views/pages/_who.html.erb
- app/views/pages/about.html.erb
- app/views/pages/team.html.erb
- config/routes.rb
- spec/cassettes/PagesController/GET_/team/renders_successfully_when_logged_out.yml
- spec/requests/pages_spec.rb
Closes librariesio/supporters#20
> Add community, advisor and staff to /team

- app/views/layouts/application.html.erb
Generate analytics tracking if there’s an ENV variable called
ANALYTICS.
TODO
> Move analytics to "ANALYTICS" environment variable

- app/views/api/docs/index.html.erb
> Fix API doc links to be less github specific

- app/services/github_hook_handler.rb
- spec/services/github_hook_handler_spec.rb
These should be all of the events that are consumed by [github-dispatch](https://github.com/librariesio/github-dispatch/blob/master/dispatch.rb).
cc @andrew
> Add more events to GithubHookHandler

- Gemfile
- Gemfile.lock
stripe gem added to Gemfile, version locked to 2.1.0 in Gemfile.lock
fixes #1295
> Update stripe gem

- app/controllers/search_controller.rb
- app/views/explore/_sidebar.html.erb
- app/views/projects/index.html.erb
- app/views/search/index.html.erb
Adding a few notices to contribute, focussing on support for more package managers. 
Adds to
/
/explore
/search
Fixes #1176
> Contribute notices

- .gitignore
- lib/tasks/export.rake
First pass at exporting data for research purposes, trying to match the data format that @AlexandreDecan is already using.
> Add rake task for exporting dependency data to csv

- app/models/identity.rb
- app/models/repository_user.rb
- db/migrate/20170413115806_add_repository_user_id_to_identities.rb
- db/schema.rb
- spec/models/identity_spec.rb
- spec/models/repository_user_spec.rb
Unblocks https://github.com/librariesio/libraries.io/pull/1352
Will allow joining between users and repositories independently of host type
> Link identities to repository users

- app/views/pages/team.html.erb
> Add Nadia to /team

- app/models/concerns/issue_search.rb
- app/models/issue.rb
- app/serializers/issue_serializer.rb
- app/views/issues/_issue.html.erb
- db/migrate/20170516140702_add_host_type_to_issues.rb
- db/migrate/20170516141712_change_github_id_to_uuid_on_issues.rb
- db/schema.rb
- spec/factories.rb
- spec/requests/api/issues_spec.rb
- spec/serializers/issue_serializer_spec.rb
Part 1 of #1170
Updates database to handle issues from GL+BB
> Prepare for downloading Issues and Pull Requests for GitLab and Bitbucket

- app/views/layouts/application.html.erb
Not sure of the syntax here but it appears valid. In irb.
> Add search to nabber for logged in users (who will be looking at a list of repos)

- app/assets/stylesheets/application.scss
- app/views/api/docs/index.html.erb
- app/views/pages/data.html.erb
- app/views/projects/index.html.erb
- app/views/projects/show.html.erb
Fix up three different well sizes and uses them in project#show,
api#index and pages#data.
> Fix wells, tidy API examples

- app/views/api/docs/index.html.erb
This was the only wrapper I was able to find. My google-fu is non-existent today
> Add wrappers section to api page

- app/controllers/pages_controller.rb
- app/views/layouts/_footer.html.erb
- app/views/pages/_releases.html.erb
- app/views/pages/data.html.erb
- app/views/pages/experiments.html.erb
- app/views/projects/unseen_infrastructure.html.erb
- config/routes.rb
- spec/requests/pages_spec.rb
- spec/requests/projects_spec.rb
* Adds Experiments page:
* updates footer:
TODO:
Closes #1140
> Add experiments page

- app/models/package_manager/bower.rb
We changed Bower's registry so it's behind a CDN, please change it as well :)
> Change bower registry to new one

- Gemfile.lock
Hi!
Fixes #1694
Fixes #1703
Fixes #1721
Fixes #1723
Fixes #1725
The next tickets were gems already updated, I think you can close it:
#1692
#1695
#1696
#1697
#1698
#1699
#1700
#1702
#1704
#1705
#1706
#1707
#1708
#1709
#1710
#1711
#1712
#1713
#1716
#1717
#1719
#1720
#1722
> Updated gems

- app/helpers/open_data_helper.rb
- app/views/pages/_open_data_downloads.html.erb
- app/views/pages/data.html.erb
Includes previous versions in the release table
> Updated open data page for latest release

- Gemfile.lock
upgrade pghero to resolve #1850
> upgrade pghero to 2.1.0

- app/models/package_manager/base.rb
I only noticed when testing out https://github.com/librariesio/libraries.io/pull/1855
> Use formatted_name for platform_name instead of a conditional that almost does the same thing

- app/models/package_manager/racket.rb
- lib/tasks/download.rake
- spec/models/package_manager/racket_spec.rb
Feature asked by #1820 
Greeting from [24pullrequests.com](http://24pullrequests.com)
> Add Racket

- app/views/versions_mailer/new_version.html.erb
- app/views/versions_mailer/new_version.text.erb
- spec/mailers/previews/versions_mailer_preview.rb
Logged in users who've not optted in will see a red alert bar with the
accept button.
Also added a mailer preview for the new version emails
> Prompt to users who've not updated their terms of service to login

- lib/tasks/download.rake
> Add import new async rake task for PureScript package manager

- Gemfile.lock
> upgrade bugsnag to v6.5.0

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/timeline_controller.rb
- app/views/timeline/show.html.erb
- config/routes.rb
A little spike at displaying what's happened on a project and it's repository over time, grouped by month. 
Shows when:
- releases are published
- git tags are pushed
- issues opened and closed
- pull requests opened and closed/merged
> Project timeline view

- app/models/project.rb
- app/serializers/project_serializer.rb
- spec/requests/api/bower_search_spec.rb
- spec/requests/api/projects_spec.rb
- spec/serializers/project_serializer_spec.rb
> Serialize also dependents_count and dependent_repos_count

- Gemfile
- Gemfile.lock
Last release of ffi caused issues on deployment so going careful with this one
> Updating ffi to 1.9.23

- app/models/concerns/monitoring.rb
- app/models/project.rb
- app/models/repository.rb
- app/models/repository_dependency.rb
- spec/models/project_spec.rb
Related to #1348
Wait to backfill the database before deploying this
> Start using new repository dependency relation

- spec/requests/api/status_spec.rb
> Status API doesn't use elasticsearch anymore

- app/controllers/api/status_controller.rb
- app/controllers/application_controller.rb
- app/models/concerns/dependency_checks.rb
- app/models/package_manager/base.rb
- app/models/repository_tree_resolver.rb
- app/views/pages/_matrix.html.erb
- config/sitemap.rb
> Refactor finding in package manager base class

- app/views/projects/unlicensed.html.erb
> Fix punctuation in licensing explanation

- config/routes.rb
- spec/routing/tree_routes_spec.rb
> Fix tree routes for namespaced npm packages

- db/migrate/20180403154402_add_runtime_dependencies_count_to_projects.rb
- db/schema.rb
Follow on from #2079, part of #1916
> Add runtime_dependencies_count to projects

- app/models/concerns/releases.rb
- app/models/project.rb
- app/models/tag.rb
Follow on from #2080, part of #1916
> Update runtime_dependencies_count from latest version when a project is saved

- app/controllers/api/subscriptions_controller.rb
Probably fixes https://github.com/librariesio/libraries.io/issues/1743
I don't have this running locally. (Having trouble installing all the dependencies.)
> Use project.id when creating a subscription

- app/views/projects/_statistics.html.erb
- app/views/repositories/_stats.html.erb
Makes it clearer that it's repo size, not package size
Fixes #2101
> Change size label in project and repo statistics box

- docs/development-setup.md
- [Y] Have you followed the guidelines for [contributors](http://docs.libraries.io/contributorshandbook)?
- [Y] Have you checked to ensure there aren't other open pull requests on the repository for a similar change?
- [NA] Is there a corresponding ticket for your pull request?
- [NA] Have you written new tests for your changes?
- [Y] Have you successfully run the project with your changes locally?
If so then please replace this section with a link to the ticket(s) it addressed, an explanation of your change and why you think we should include it. Thanks again! 
---
Hello.
This …
> Documentation fixes

- app/views/api/docs/index.html.erb
> The usage example actually links to sourcerank

- Gemfile.lock
#2145 
Everything seems to be working well.
> Update brakeman to 4.3.0

- app/models/user.rb
Add @havocp and @katzj to the list of admins
> Add havoc and jeremy to the list of admins

- app/views/projects/unlicensed.html.erb
> Only propose suggesting a license if there's a repo

- app/views/layouts/_footer.html.erb
Resolves #1666.
Adds a line to the footer explaining that the data is CC-BY-SA and links to https://libraries.io/data, which gives more explanation. This link destination is consistent with the [link on the Experiments page](https://github.com/librariesio/libraries.io/blob/860afa482f841a82115d3e148d2f28815fcc9bed/app/views/pages/experiments.html.erb#L67).
> Added reference to data license in footer

- app/controllers/api/projects_controller.rb
- app/controllers/application_controller.rb
- app/models/project.rb
- app/serializers/minimum_project_serializer.rb
- config/routes.rb
- spec/requests/api/projects_spec.rb
- spec/serializers/minimum_project_serializer_spec.rb
Sharing this early, it isn't ready for detailed review but figure let's talk it over before I write a bunch of tests etc. It probably still has syntax errors right now.
> add endpoints to efficiently get only project deps / bulk project deps

- app/controllers/api/status_controller.rb
These are cheap to include and useful.
> In private /check API, include latest_download_url method

- app/views/api/docs/index.html.erb
- app/views/pages/about.html.erb
Just a few typo fixes :slightly_smiling_face:
> Fixed typos

- app/views/shared/_flash.html.erb
want orange flash border consistent with bg
> changed border color

- app/controllers/api/status_controller.rb
- spec/requests/api/status_spec.rb
> On the /api/check controller, if we don't find every project, try again forcing lowercase comparison

- app/controllers/application_controller.rb
- app/views/shared/_flash.html.erb
- app/views/shared/flashes/1million-for-lifters.html.erb
This lets us have multiple messages that can be shown in the flash area so that different things can be tested
> Add ability to cycle through random flashes

- app/controllers/project_usage_controller.rb
- db/migrate/20181210155612_add_requirements_indexes.rb
- db/schema.rb
Adds some indexes that should help a few of our queries on distinct(requirements) and save a join when looking at repository_dependencies
> Add some query speedups

- config/environments/production.rb
> Force mail links to be https

- app/models/maintenance_stats/queries/releases_query.rb
slice returns a hash and we just need the value
> Fix end_date params

- app/views/projects/_statistics.html.erb
https://libraries.io/pypi/Pillow
> Use consistent sentence case

- .github/CONTRIBUTING.md
> fix broken issue template link in CONTRIBUTING

- app/serializers/repository_user_serializer.rb
- spec/requests/api/repository_users_spec.rb
- spec/serializers/repository_user_serializer_spec.rb
- [ √] Is there a corresponding ticket for your pull request?
> Deprecate following and followers from users

- app/views/pages/_open_data_documentation.html.erb
> Fixing typing error.

- app/views/pages/data.html.erb
I believe that the number of packages should have been updated when this commit was done: dff4251
> Updating number of packages

- .vscode/settings.json
- app/models/package_manager/maven.rb
> Look at maven.org for Maven Package Versions

- app/models/package_manager/maven.rb
- spec/models/package_manager/maven_spec.rb
This would prevent packages being added to Maven from the maven-repository.com/artifacts/latest scan if they do not have a valid name of `{group_id}:{artifact_name}`.
> Exclude Maven Names Found From latest That Are Invalid

- app/models/package_manager/maven.rb
From comments on #2401 after I had merged it.
> Additional Maven Name PR Fixes

- app/views/pages/experiments.html.erb
- app/views/projects/digital_infrastructure.html.erb
Her name is [Nadia Eghbal](https://nadiaeghbal.com/).
> Fix Eghbal's name on experiments pages

- Gemfile
- Gemfile.lock
https://github.com/librariesio/bibliothecary/pull/460
> Bibliothecary 6.7.4 (more maven interpolation)

- Gemfile
- app/controllers/api/projects_controller.rb
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/models/dependency.rb
- app/models/package_manager/base.rb
- app/models/package_manager/go.rb
- app/models/package_manager/pypi.rb
- app/models/project.rb
- app/models/repository_dependency.rb
- app/queries/project_status_query.rb
- app/serializers/project_status_serializer.rb
- spec/models/package_manager/go_spec.rb
- spec/models/project_spec.rb
- spec/queries/project_status_query_spec.rb
- spec/requests/api/projects_spec.rb
- spec/requests/api/status_spec.rb
- spec/spec_helper.rb
Not sure this is done yet, but I wanted to get some opinions.
In particular, I'm not sure if the last commit (project status) should be there - perhaps we want to leave that endpoint as it is? Thoughts?
> Improve package name casing

- Gemfile.lock
https://github.com/librariesio/libraries.io/network/alert/Gemfile.lock/nokogiri/open
> Latest nokogiri

- Gemfile.lock
- app/models/package_manager/conda.rb
- lib/tasks/download.rake
- spec/models/package_manager/conda_spec.rb
Still looking to figure out if anything else needs to be added, but this is ready for review I think.
> Add Conda Package Manager

- app/models/package_manager/conda.rb
- app/models/project.rb
…sts in the anaconda packages, or if it should be removed from the site
> Adding check status url for conda so that we can see if a package exists in the anaconda packages, or if it should be removed from the site

- config/sitemap.rb
This is a bit of pruning to cut down on the number of pages that Google is trying to crawl and let us focus on things which are more valuable
> Prune the sitemap

- app/models/project.rb
- app/serializers/project_serializer.rb
- db/migrate/20191016195047_project_licenses_normalized.rb
- db/schema.rb
- spec/models/project_spec.rb
- spec/requests/api/bower_search_spec.rb
- spec/requests/api/projects_spec.rb
- spec/serializers/project_serializer_spec.rb
First pass at this - thoughts?
> Expose license normalization

- app/views/layouts/application.html.erb
- app/views/projects/show.html.erb
- app/views/tree/_tree.html.erb
Mark pages that are versioned to have a canonical url to improve search results
> Add canonical URLs for project version pages

- lib/tasks/projects.rake
I still need to figure out the best way to run this task.
> Rake Task to Fill in license_normalized Values for Projects

- app/assets/stylesheets/_highlight.scss
- app/models/maintenance_stats/queries/github/releases_query.rb
- app/views/pages/_open_data_documentation.html.erb
- app/views/projects/unsubscribe.html.erb
- app/views/repositories/hacker_news.html.erb
- app/views/shared/_flash.html.erb
- config/github_graphql_schema.json
- config/initializers/simple_form.rb
- lib/tasks/projects.rake
- lib/tasks/research.rake
These are just in strings, so no effect on code functionality.
> Fix various typos in text

- app/models/repository_organisation.rb
- app/models/repository_user.rb
This is just a typo in a name. No real run-time effect, but might as well correct it.
> Typo login_uniqueness_with_case_insensitive_host

- Backlog.md
It's always amusing in a discussion of quality, when "quality" is misspelled ;)
> Fix typo of quality

- app/models/repository_host/bitbucket.rb
- app/models/repository_host/gitlab.rb
These look like typos that are waiting to be a problem some day.
> Fix typos of create_webhook

- .github/CONTRIBUTING.md
> Fix links to code of conduct, issue and PR templates

- app/controllers/api/docs_controller.rb
- app/controllers/api/project_usage_controller.rb
- app/controllers/api/projects_controller.rb
- app/controllers/api/repositories_controller.rb
- app/controllers/project_usage_controller.rb
- app/controllers/repositories_controller.rb
- app/models/concerns/repo_manifests.rb
- app/models/package_manager/carthage.rb
- app/models/project.rb
- app/models/repository_dependency.rb
- app/models/repository_subscription.rb
- app/models/repository_tree_resolver.rb
- app/models/tag.rb
- app/models/user.rb
- app/models/version.rb
- app/views/admin/stats/index.html.erb
- app/views/admin/stats/overview.html.erb
- app/views/api/docs/index.html.erb
- app/views/dashboard/_github_repository.html.erb
- app/views/repositories/_stats.html.erb
- app/views/repositories/dependencies.html.erb
Prerequisite to https://github.com/librariesio/libraries.io/pull/2584
> RepositoryDependency id migration step 1: disable all related code 

- app/controllers/repository_users_controller.rb
- app/models/concerns/repository_source_rank.rb
- app/models/concerns/source_rank.rb
These are causing some active queries on this table rn.
>  RepositoryDependency id migration step 2.5: more temp disabling of features.

- app/controllers/repository_users_controller.rb
Forgot to include a return in this temporary head response.
> Return :facepalm:.RepositoryDependency id migration step 2.6: one more fix

- app/controllers/api/docs_controller.rb
- app/controllers/api/project_usage_controller.rb
- app/controllers/api/projects_controller.rb
- app/controllers/api/repositories_controller.rb
- app/controllers/project_usage_controller.rb
- app/controllers/repositories_controller.rb
- app/controllers/repository_users_controller.rb
- app/models/concerns/repo_manifests.rb
- app/models/concerns/repository_source_rank.rb
- app/models/concerns/source_rank.rb
- app/models/package_manager/carthage.rb
- app/models/project.rb
- app/models/repository_dependency.rb
- app/models/repository_subscription.rb
- app/models/repository_tree_resolver.rb
- app/models/tag.rb
- app/models/user.rb
- app/models/version.rb
- app/views/admin/stats/index.html.erb
- app/views/admin/stats/overview.html.erb
- app/views/api/docs/index.html.erb
- app/views/dashboard/_github_repository.html.erb
- app/views/repositories/_stats.html.erb
- app/views/repositories/dependencies.html.erb
Cleanup after https://github.com/librariesio/libraries.io/pull/2585 and https://github.com/librariesio/libraries.io/pull/2584
> RepositoryDependency id migration step 3: cleanup

- app/controllers/api/docs_controller.rb
- app/views/api/docs/index.html.erb
Queries are timing out so let's get the page mostly working even
if we don't have this documented for now
> Don't document project usage for now

- app/models/package_manager/go.rb
- app/models/project.rb
- app/workers/go_project_verification_worker.rb
- lib/tasks/projects.rake
Added a worker and rake task to go through and verify Go project names against the Go proxy and remove projects that are not found on there. I am going to open this as a draft and let you guys think about if you want to run through these projects.
> Verify Go Projects

- app/controllers/api/application_controller.rb
- app/controllers/application_controller.rb
Wanted to get an eye on what active connections look like when we see stability issues.
> Log active connection count

- lib/tasks/projects.rake
> Add platform scope to rake task.

- config/database.yml
I'm just running a a docker service for old PG and this makes things way easier to run off the stock image.
> This makes things easier to run with a default setup db

- db/migrate/20210106132735_add_projects_index_languages_licenses.rb
- db/schema.rb
> Add indexes on languages and licenses for projects table

- app/controllers/keywords_controller.rb
- app/controllers/languages_controller.rb
- app/controllers/licenses_controller.rb
- app/controllers/platforms_controller.rb
- app/views/keywords/show.html.erb
- app/views/languages/show.html.erb
- app/views/licenses/show.html.erb
- app/views/platforms/show.html.erb
This simplifies the language, platform, license, and keyword overview pages by removing watched and dependent repos
> Simplify overview pages

- app/models/package_manager/pypi.rb
Only return "yanked" when "yanked" == true.
> One more quickfix for Pypi old-style deprecation detection.

- app/models/package_manager/clojars.rb
- app/models/package_manager/cpan.rb
Minor fixes for clojars and cpan
> Minor fixes

- app/models/repository_host/gitlab.rb
Similar to what we do for github and bitbucket
> Add unauthorized to gitlab ignorable exceptions

- app/workers/package_manager_download_worker.rb
Not doing anything here yet, I think @mellisio is working on the innards, but wanted to get this parameter added so we can fill it in on the other side.
> Prep for version specific package manager downloads

- app/models/package_manager/base.rb
- app/models/package_manager/rubygems.rb
- app/models/project.rb
- app/models/version.rb
- app/views/admin/projects/show.html.erb
- app/views/project_suggestions/new.html.erb
- db/migrate/20210126141107_add_status_to_version.rb
- db/schema.rb
- spec/models/package_manager/rubygems_spec.rb
Q: should we start showing Version statuses publicly on the project pages too?
> Make Version deprecatable, and implement Rubygems "yanking" deprecation.

- app/models/package_manager/cocoa_pods.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6011a36c9e8e6200185ec813
> Fix another Cocopoads issue when the pod is missing.

- lib/tasks/download.rake
To be merged after https://github.com/librariesio/depper/pull/27
> Remove download:nuget

- .github/CONTRIBUTING.md
- README.md
- app/views/explore/_sidebar.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/_package_manager_list.html.erb
- app/views/pages/team.html.erb
- app/views/projects/index.html.erb
- bin/deploy.sh
After merging I'll fork into a `main` branch and push it. To update your local copy:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
> master -> main

- app/models/package_manager/maven.rb
One more fix I should've included in https://github.com/librariesio/libraries.io/commit/2f6ee2279d6128e732d18d21bff05b9b710df8f7
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/601d7ba5cab0000017044e74
> Fix a Maven arity bug.

- app/models/package_manager/base.rb
Cleanup, refactor, and wrangle an N+1.
> PackageManagerDownloadWorker refactor: step 1

- app/controllers/accounts_controller.rb
- app/controllers/admin/projects_controller.rb
- app/controllers/admin/repositories_controller.rb
- app/controllers/admin/repository_organisations_controller.rb
- app/controllers/api/subscriptions_controller.rb
- app/controllers/project_suggestions_controller.rb
- app/controllers/repository_subscriptions_controller.rb
- app/controllers/subscriptions_controller.rb
- app/controllers/web_hooks_controller.rb
- app/models/concerns/github_identity.rb
- app/models/project.rb
- app/models/repository.rb
- app/models/repository_host/bitbucket.rb
- app/models/repository_host/github.rb
- app/models/repository_host/gitlab.rb
- app/models/repository_organisation.rb
- app/models/repository_user.rb
- app/models/user.rb
- app/models/web_hook.rb
- spec/models/project_spec.rb
update_attributes() is gone in Rails 6.0
> update_attributes() -> update()

- app/models/package_manager/cargo.rb
Followup to https://github.com/librariesio/libraries.io/pull/2741
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6033d050c7f3120018127c84
> Fix cargo versions arity

- app/models/package_manager/base.rb
> Silly mistake.

- app/models/package_manager/base.rb
I think this error happens when we get N updates for a new package at the same time and there's a race condition on creating the project.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6033e83995ee750017f32eeb
> For name uniqueness validation errors, rescue and re-lookup the project.

- app/models/package_manager/base.rb
Updates don't currently update a version if we've seen it before. This changes that to update a version *if* something we're interested in has changed. For safety I added a bit where we allow only a select number of attributes to be updated.
> Update versions if new information has come to light

- app/models/package_manager/maven.rb
This isn't used, I deleted the set from redis.
> Removed load_names from maven package manager

- app/models/package_manager/homebrew.rb
Followup to https://github.com/librariesio/libraries.io/pull/2760
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/603f055a2fd6bb0017327efe
> Fix Homebrew versions method.

- app/models/package_manager/atom.rb
- app/models/package_manager/base.rb
- app/models/package_manager/cargo.rb
- app/models/package_manager/conda.rb
- app/models/package_manager/cpan.rb
- app/models/package_manager/cran.rb
- app/models/package_manager/dub.rb
- app/models/package_manager/elm.rb
- app/models/package_manager/go.rb
- app/models/package_manager/haxelib.rb
- app/models/package_manager/hex.rb
- app/models/package_manager/homebrew.rb
- app/models/package_manager/npm.rb
- app/models/package_manager/packagist.rb
- app/models/package_manager/pub.rb
- app/models/package_manager/puppet.rb
- app/models/package_manager/pypi.rb
- app/models/package_manager/rubygems.rb
- docs/add-a-package-manager.md
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60010c298ed8fc0017c964c9
Also renamed a bunch of args to be more clear.
> Fix for Elm ingestion.

- app/models/package_manager/elm.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60478ca64d16670007648d2c
> Fix Elm versions ingestion.

- app/controllers/api/projects_controller.rb
- spec/requests/api/projects_spec.rb
I tested this API call and it seems to work, but I forgot to flip the switch.
> Start using optimized .../dependencies endpoint code

- app/models/package_manager/packagist.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6007059462591d001892e3a9?event_id=60871a7f00780ff373c30000&i=em&m=fq
> Less noise when we get a Packagist 404.

- app/models/project.rb
- app/models/version.rb
- app/workers/project_tags_update_worker.rb
Little baby-step to try and figure out what's going on here and optimize it. We collected a bunch of stats that definitely point to tag updating being the culprit here. The second commit has the meat, the first is just linting.
> Project tag updater

- app/models/package_manager/bower.rb
- app/models/package_manager/cargo.rb
- app/models/package_manager/hex.rb
- app/models/package_manager/pub.rb
Missed a few spots in my last refactor.
> Fix a few missed spots from PackageManager::Base class refactors.

- app/models/package_manager/racket.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60909d31a33ae00008664b94?event_id=60909d310079d8b8125b0000&i=em&m=nw
> Fix a spot in Racket updates that was missed during refactor

- app/models/repository.rb
- app/models/repository_user.rb
- lib/tasks/search.rake
Fixes https://github.com/librariesio/libraries.io/issues/2815
> Issue model cleanup

- docs/development-setup.md
Updated readme with a couple things I discovered while setting up the project on an Apple M1-chipped computer + Dockerized Postgres instance.
> Updated readme

- app/models/project.rb
Silences https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60ae5045f6c70d0008aa9be7
> Don't try to sync a project if its platform has been removed.

- app/models/project.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60f8a74af8ed0700070ea461
> Handle platform color for platforms that have been removed.

- app/models/project.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6131764cedd57a00080d72a8
> Consider a 404 from Packagist as "Removed" too

- app/models/package_manager/packagist.rb
Should fix Packagist packages not being synced recently.
> Ensure that the "Main" repository source is mapped to Main (Packagist)

- app/controllers/hooks_controller.rb
- app/models/package_manager/base.rb
- app/models/project.rb
- app/workers/package_manager_download_worker.rb
- lib/tasks/projects.rake
This should make it easier to debug from whence invalid workers are spawned.
> Add a source of package updates to the package update worker

- app/models/project.rb
This is admittedly not a root-cause fix, but wanting to get rid of a flood
of exceptions and hoping this will work.
> Project: wrap and flatten keywords

- app/models/package_manager/pypi.rb
- app/models/project.rb
- spec/models/package_manager/pypi_spec.rb
This fixes pypi packages that are accidentally marked as deprecated. 
> fixes pypi packages that are accidentally marked as deprecated.

- .gitignore
- config/routes.rb
- lib/tasks/version_scheme_counter.rake
- spec/tasks/version_scheme_counter_spec.rb
- [X ] Have you checked to ensure there aren't other open pull requests on the repository for a similar change?
- [ X] Have you written new tests for your changes?
- [ X] Have you successfully run the project with your changes locally?
In investigating supporting multiple versioning schemes the idea arose to gather some numbers on scheme counts "in the wild".
This PR contains a Rake task.
The purpose of this task is to try to detect (as intelligently as possible) the spread of versioning schemes in use in a list of provided platforms and package names. It is not finished since …
> Add version scheme detection task

- lib/tasks/version_scheme_counter.rake
Make sure to view the diff with "ignore whitespace"
> Fix to account for large CSV datasets as input

- app/models/package_manager/go.rb
- app/workers/go_project_verification_worker.rb
- spec/models/package_manager/go_spec.rb
This will try and lookup existing Go projects that match based on the repository URL and use the existing name instead of creating a new one. We have a lot of Go projects that have different casing but all point to the same module.
One example:
https://pkg.go.dev/github.com/Go-sqL-Driver/MySQL
https://pkg.go.dev/github.com/Go-SQL-Driver/MySQL
> Group Go Projects Around Repository URL to Avoid Different Cased Modules

- lib/tasks/version_scheme_counter.rake
- spec/tasks/version_scheme_counter_spec.rb
Also fixes restarting from where the task left off to accommodate for packages in the CSV which don't exist in libraries.
> Make detection have a successful match only when unanimous

- app/controllers/api/versions_controller.rb
- spec/requests/api/versions_spec.rb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6234d918bcf6b60009a6cd53
> Ignore versions with a missing project in Versions#index

- app/views/repository_tree/_dep.html.erb
- app/views/repository_tree/_dependency.html.erb
- app/views/tree/_dep.html.erb
- app/views/tree/_dependency.html.erb
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffca366b35b870018f87a07
> Wrap Project#normalize_licenses in a few places to fix nil license bug in view

- app/views/projects/versions.html.erb
> Enable pagination links on version pages

- app/models/package_manager/packagist.rb
- spec/models/package_manager/packagist_spec.rb
* Handle nil 'time' fields: https://app.bugsnag.com/tidelift/libraries-dot-io/errors/62966bdf99ebe7000b5da18f
* Handle missing packages: https://app.bugsnag.com/tidelift/libraries-dot-io/errors/62966cd4c10b0900083266f5
* Fix source: https://app.bugsnag.com/tidelift/libraries-dot-io/errors/62966bf6b69b5700083b86b8
* Handle nil licenses: https://app.bugsnag.com/tidelift/libraries-dot-io/errors/629673c9ab477b000aa70f6f
> Some fixes for new Packagist v2 package API.

- app/controllers/application_controller.rb
- spec/models/package_manager/go_spec.rb
Fix specs which fail when the local timezone date is different from UTC date
> Fix timezone specs

- app/controllers/api/search_controller.rb
- config/initializers/rack-attack.rb
- spec/requests/api/search_spec.rb
* Fix https://app.bugsnag.com/tidelift/libraries-dot-io/errors/62eb38c12818a60008044340?event_id=62eb38c100961b2377ef0000&i=sk&m=nw
* Fix failing spec
> Fix ip throttle

- config/initializers/marginalia.rb
- config/initializers/sidekiq.rb
https://github.com/basecamp/marginalia/wiki/Integration-with-Sidekiq
> Add marginalia annotations for sidekiq

- config/initializers/datadog.rb
> disable datadog profiler

- app/models/package_manager/base.rb
Some of the worst-performing PackageManagerDownloadWorker jobs have a "dupe version" error in their request trace (not sure if it's a cause or symptom of the slowness)
This adds one more rescue so that these don't make it to Bugsnag, and also logs both rescues so we can measure them.
Once deployed, we can check the frequency of them, per platform.
> Log duplicate version errors to measure frequency

- config/initializers/elasticsearch.rb
Missed this in https://github.com/librariesio/libraries.io/pull/3006
> Remove one missed requirement from GCP removal

- app/controllers/application_controller.rb
- config/environments/production.rb
* we always want to log to STDOUT
* configure lograge logging
* add a few extra things to lograge logs: "the error that was thrown", current user id, and remote ip
> Improvements to prod logging: always stdout, lograge++, etc

- docs/development-setup.md
- spec/models/repository_spec.rb
The docs for re-recording VCR cassettes were buried in a test.
> Update GitHub Token & VCR re-recording docs

- app/models/project.rb
- app/serializers/optimized_project_serializer.rb
- app/serializers/project_serializer.rb
- spec/rails_helper.rb
- spec/requests/api/projects_spec.rb
- spec/requests/api/subscriptions_spec.rb
- spec/serializers/project_serializer_spec.rb
Reverts librariesio/libraries.io#3052
Potentially will fix an intermittent error
> Revert "Add repository_status to projects"

- lib/tasks/maintenance_stats.rake
Log successful items to aid in debugging work in #3056
> Add success logging for maintenance stats task

- app/models/package_manager/base.rb
- app/models/package_manager/maven.rb
- app/models/package_manager/maven/google.rb
- app/workers/package_manager_download_worker.rb
- lib/tasks/maven.rake
- spec/fixtures/vcr_cassettes/google-maven/memory-advice.yml
- spec/models/package_manager/maven/google_spec.rb
This includes support for both incrementally receiving updates via PackageManagerDownloadWorker and for bootstrapping the repo via a Rake task.
> Add support for syncing Google Maven repository

- lib/tasks/projects.rake
For batch refreshing arbitrary packages after bugfixes and whatnot.
> Add rake task for resyncing projects from a given list

- lib/tasks/projects.rake
https://app.shortcut.com/tidelift/story/32102/create-a-way-to-resync-all-packages-in-an-ecosystem-in-batches-via-sidekiq
More data freshening tools 🧹
> Add task to re-sync a given platform

- app/models/project.rb
Received one more query timeout here, extending to be safe.
> Extend a timeout once more.

- app/models/package_manager/npm.rb
[Bugsnag](https://app.bugsnag.com/tidelift/libraries-dot-io/errors/644ad0674a9eb2000810354e)
> Fix another nil check uncovered by new status worker

- config/initializers/active_model_serializers.rb
https://github.com/rails-api/active_model_serializers/blob/v0.10.9/docs/general/logging.md
These are extremely voluminous
> Remove Rendered with log messages

- config/environments/production.rb
this will look something like
```
2023-06-08T16:18:52.156 INFO ...
```
Current log lines look like
```
I, [2023-06-08T20:23:22.347406 #14]  INFO -- : 
```
> Use an ISO8601 datetime format at the beginning of log lines

- app/models/package_manager/base.rb
- app/models/package_manager/npm.rb
- spec/models/package_manager/npm_spec.rb
- spec/models/package_manager/rubygems_spec.rb
Adds support for removed releases for the NPM package manager.
> Add removed release support for NPM

- app/models/package_manager/rubygems.rb
- spec/models/package_manager/rubygems_spec.rb
> Fix default argument for versions fetching

- lib/tasks/input_tsv_file.rb
- lib/tasks/one_off.rake
- lib/tasks/projects.rake
I also extracted the TSV file handling to its own class for reusability.
> feat: [sc-31451] Create one-off task to fix PyPI published_at dates

- lib/tasks/one_off.rake
Story details: https://app.shortcut.com/tidelift/story/31451
> Ensure projects are valid before doing more processing

- lib/tasks/projects.rake
This removes `projects:sync_by_platform` rake task, in favor of using `projects:sync_from_list` for similar operations in the future.
This also removes the `sleep` from `projects:sync_from_list` since it batches up async workers, so a wait time should not be necessary.
> Remove projects:sync_by_platform rake task, remove sleep from projects:sync_from_list

- app/models/package_manager/base.rb
- spec/models/package_manager/go_spec.rb
- spec/models/package_manager/pypi_spec.rb
Follow up to https://github.com/librariesio/libraries.io/pull/3169#discussion_r1275050493
This should bump the updated_at timestamps on a version only when the version's status changes to 'Removed'.
I only updated the Go spec since it was representative of the other package managers in that block; the method should probably be either overwritten by their respective package managers or spex should exist for the `base.deprecate_versions` method, but I didn't want to get into a big refactor on this.
> Bump updated_ats when updating versions to Removed status

- app/views/shared/flashes/libraries.html.erb
- app/views/shared/flashes/upstream-5.html.erb
- app/views/shared/flashes/upstream-7.html.erb
update banner message to be one libraries message instead of two upstream messages
> update banner message

- app/views/pages/data.html.erb
https://github.com/librariesio/libraries.io/assets/7821335/e1f8cd9d-bcb4-4df2-a42b-bf9f41dd23c7
> update copy on 'data' page

- app/controllers/search_controller.rb
- app/helpers/application_helper.rb
- app/views/search/index.html.erb
- spec/requests/search_spec.rb
Reverts #3209 - this breaks some links
> Revert SearchController#index: short-circuit when no search term is provided

- app/models/package_manager/nu_get.rb
- spec/models/package_manager/nu_get_spec.rb
Fixes [Bugsnag](https://app.bugsnag.com/tidelift/libraries-dot-io/errors/651785b1be6f4d00071480e3)
> Fix nil check, dont explode if no releases to check deprecation info on

- app/models/package_manager/maven/maven_central.rb
- spec/fixtures/vcr_cassettes/maven-central/lambda-tracer.yml
- spec/models/package_manager/maven/maven_central_spec.rb
Goal:
* Handle removed releases from Maven Central, using a real package with removed releases as an example.
> Enable removed release support for Maven Central

- app/workers/repository_maintenance_stat_worker.rb
- spec/workers/repository_maintenance_stat_worker_spec.rb
Story details: https://app.shortcut.com/tidelift/story/37574
Prepping this for after we verify https://github.com/librariesio/libraries.io/pull/3228 works - reverts https://github.com/librariesio/libraries.io/pull/3218
> fix: [sc-37574] Re-enable gathering maintenance stats

- app/models/application_record.rb
At least one table in production has outgrown integers
> Make `fast_total` able to cope with WebScale

- app/workers/check_repo_status_worker.rb
- app/workers/check_status_worker.rb
- app/workers/create_repository_worker.rb
- app/workers/github_hook_worker.rb
- app/workers/github_star_worker.rb
- app/workers/nuget_project_verification_worker.rb
- app/workers/project_score_worker.rb
- app/workers/project_tags_update_worker.rb
- app/workers/project_updated_worker.rb
- app/workers/repository_create_org_worker.rb
- app/workers/repository_create_user_worker.rb
- app/workers/repository_download_worker.rb
- app/workers/repository_maintenance_stat_worker.rb
- app/workers/repository_project_worker.rb
- app/workers/repository_tree_resolver_worker.rb
- app/workers/repository_update_org_worker.rb
- app/workers/repository_update_user_worker.rb
- app/workers/sync_permissions_worker.rb
- app/workers/tag_notifications_worker.rb
- app/workers/tag_worker.rb
- app/workers/tree_resolver_worker.rb
- app/workers/update_repository_source_rank_worker.rb
- app/workers/update_source_rank_worker.rb
- app/workers/version_notifications_worker.rb
Note to self: open PR for their upgrading guide
> Fix sidekiq unique jobs options

- config/initializers/sidekiq.rb
> Disable SidekiqUniqueJobs in tests

- app/models/repository_host/bitbucket.rb
Reduces some of the Bugsnag noise and make it easier to catch issues with a particular service
> Catch some empty payloads and better log errors

- app/models/repository_host/bitbucket.rb
* Use proper facet name and call correct method
> fix: Error while logging errors

- app/models/concerns/github_identity.rb
This should fix https://app.bugsnag.com/tidelift/libraries-dot-io/errors/64c8081643b15e0008352b41?filters[error.status]=open&filters[event.since]=30d&pivot_tab=event
> Fix up the repository dashboard

- app/models/repository_owner/gitlab.rb
fixes bugsnag 655efe17f52efa0007687c7e
> Follow redirects for repos that are moved on GitLab

- app/controllers/api/projects_controller.rb
- config/routes.rb
- spec/requests/api/projects_spec.rb
Adds an endpoint to programmatically trigger a resync of a given project
> chore: [sc-34977] Ensure that DepCI is able to trigger a manual resync on a Libraries package

- app/workers/proactive_project_sync_worker.rb
- spec/tasks/projects_spec.rb
- spec/workers/proactive_project_sync_worker_spec.rb
Name a more classic "that's how they get ya"
> fix: Add type guard to ensure default limit is default

- app/models/repository_host/github.rb
- spec/models/repository_spec.rb
If we try and get stats for a GitHub repository that GitHub returns a 404 error for, then don't run any queries for it and clear out the existing stats since they are no longer valid and stale.
> Ignore and Clear Out Stats for Not Found Repositories

- app/controllers/projects_controller.rb
- app/workers/package_manager_download_worker.rb
Seen while working through documentation updates.
> feat: [sc-39686] Clean up PackageManagerDownloadWorker and add method note

- docs/development-setup.md
> Remove removed phantomjs dependency from setup doc

- app/serializers/optimized_project_serializer.rb
- spec/requests/api/status_spec.rb
Fix a regression introduced in https://github.com/librariesio/libraries.io/pull/3316. The previous response was a csv string, not a json array.
> Fix status keywords again

- spec/requests/api/projects_spec.rb
Fixes the flaky spec that failed here:
https://app.circleci.com/pipelines/github/librariesio/libraries.io/2217/workflows/ddbbef63-e414-442b-aa1a-eb22a8baba7e/jobs/6905/tests#failed-test-0
> Fix flaky spec

- app/views/shared/flashes/2024-recs.html.erb
> update banner copy

- app/models/repository.rb
Follow-up to https://github.com/librariesio/libraries.io/pull/3364
We don't actually unset `status: "Removed"` until `update_from_repository`. This will short-circuit the update if we get a 404, but will proceed if we can resolve the URL.
> Repository: do a manual sync if we don't get a 404 for the repository

- app/models/repository.rb
Follow-up to https://github.com/librariesio/libraries.io/pull/3365 - missing return 🤦
> Repository: add return to check_status

- .irbrc
* displays the rails env you're in
* disable multiline for faster pasting
* disables autocomplete bc it's difficult to work with
* allow a local .irbrc.local file to be defined with more settings
> Adds an .irbrc for sensible defaults

- app/models/version.rb
Don't need this generally so let's have it be a wee bit quieter
> Switch this log to be debug

- spec/models/package_manager/go_spec.rb
This got left in after my last commit
> remove a spec focus

- app/models/package_manager/nu_get.rb
- lib/tasks/one_off.rake
just a few fixes that I ran into over the weekend, while running this rake task.
> Some tweaks to NuGet update logic and rake task

- app/models/repository_host/github.rb
- spec/models/repository_host/github_spec.rb
There is a permissions issue I need to figure out. While I look into it this PR will temporarily disable the query from being run.
> disable repository policy URLs query

- app/controllers/accounts_controller.rb
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/sessions_controller.rb
- app/services/amplitude_service.rb
- config/application.rb
- config/initializers/bugsnag.rb
- spec/requests/projects_spec.rb
- spec/services/amplitude_service_spec.rb
Story details: https://app.shortcut.com/tidelift/story/43911
Tracking for most of the rails events
- Page Viewed
- Login Successful
- Account Updated
- Account Deleted
> feat: [sc-43911] Libraries.io: Implement Initial Amplitude Tracking

- app/models/project.rb
> log npm status changes

- app/domain/repository/persist_repository_from_upstream.rb
(followup to https://github.com/librariesio/libraries.io/pull/3437)
> Add another "audit_comment" to Repository#status when it's updated

- app/models/repository.rb
(followup to https://github.com/librariesio/libraries.io/pull/3437)
forgot to switch this `update_attribute` to `update` in `Repository#check_status`
> Fix Repository.check_status, and ensure we run Project callbacks

- app/models/repository.rb
(followup to https://github.com/librariesio/libraries.io/pull/3444)
it's one of those Fridays
> Fix copypasta.

- app/workers/check_status_worker.rb
(followup to https://github.com/librariesio/libraries.io/pull/3447 )
> Fix args in CheckStatusWorker

- app/serializers/optimized_project_serializer.rb
- spec/requests/api/status_spec.rb
Return `last_synced_at` in Api::StatusController#check so callers can determine if a project might need to be resynced.
> Api::StatusController: return last_synced_at in #check

- app/assets/stylesheets/application.scss
- app/views/projects/_dev_practices.erb
- app/views/projects/index.html.erb
- app/views/shared/flashes/libraries-and-tidelift.html.erb
- app/views/shared/flashes/upstream-2024.html.erb
https://github.com/user-attachments/assets/52819347-364b-48af-b888-dd93e91ab201
> update home page once more

- app/controllers/projects_controller.rb
- app/views/shared/flashes/libraries-and-tidelift.html.erb
forgot a link here
https://github.com/user-attachments/assets/49a9cf2a-e91f-408d-982e-051b99924144
> actually link inthe banner

- lib/tasks/one_off.rake
Story details: https://app.shortcut.com/tidelift/story/44868
> chore: [sc-44868] Add task to backfill Maven dependencies

- app/controllers/api/status_controller.rb
This should better label the trace in datadog
> StatusController: add a Oj.dump and render traces

- app/models/project.rb
And if we were, we'd probably just use the traces
> Change a log to debug as we aren't really looking at this anymore

- app/workers/check_status_worker.rb
followup to https://github.com/librariesio/libraries.io/pull/3477
> Fix missing arg in CheckStatusWorker

- app/models/package_manager/conda.rb
- spec/fixtures/vcr_cassettes/conda/shap.yml
- spec/models/package_manager/conda_spec.rb
similar to https://github.com/librariesio/libraries.io/pull/3474
>  PackageManager::Conda: treat "" requirement as "*" when fetching dependencies 

- app/models/project.rb
(followup to https://github.com/librariesio/libraries.io/pull/3482)
* change `Project#rate_limited_npm_request()` to look at the TTL of its host-specific rate-limit key, instead of the value
if we cache a "retry-after: 60", we'd store the value as 60 and the TTL as 60. But as time goes on, the value is still 60 but the TTL is, say, 13. So if we look at the value, we're waiting longer to retry than we need to.
> Project: allow npm retries sooner by using ttl instead of get

- app/views/projects/_dev_practices.erb
> remove duplicate dev practice

- app/controllers/api/status_controller.rb
(followup to https://github.com/librariesio/libraries.io/pull/3531 )
I should've put the tags on the span, not the trace 🤦🏻 And I moved them into method params too.
> Api::Status#check: move DD tags to span and clean up

- app/models/package_manager/maven/maven_central.rb
- spec/models/package_manager/maven/maven_central_spec.rb
when we scrape the HTML of MavenCentral projects to get the latest version, we currently give up if any of the versions are invalid semver. This improves the logic so that we only skip the invalid versions.
fixes the scraping of this project, which contains a version `3.0.0-,3`: `https://repo1.maven.org/maven2/org/wso2/am/am-parent/`
> MavenCentral.latest_version_scraped(): skip bad versions instead of giving up altogether

- app/views/repositories/_repository.html.erb
Some Projects endpoints are using this. For now, to prevent the pages from erroring, restore this partial. Decide what to do about these pages later.
> Restore Repository partial

- app/models/dependency.rb
- db/migrate/20250403234704_backfill_dependencies_new_id.rb
- db/schema.rb
Backfill for this is now done and it should be ready to merge.
> Index dependencies.id_new and backfill all uuids

- db/migrate/20250403234704_backfill_dependencies_new_id.rb
> Lengthen statement timeout on validate_check_constraint
