config/initializers/payola.rb

When running rake db:migrate command, initializers are loaded before migrations executed. So payola
initializer can not find 'SubscriptionPlan' model and it breaks migrations. With this change we control
'SubscriptionPlan' is defined before.
Without this change, contribution to this project will be painful.

Fixed payola initializer for migrations.

---

app/controllers/help_wanted_controller.rb
app/models/concerns/issue_search.rb
app/models/github_issue.rb
app/views/help_wanted/index.html.erb
config/routes.rb

https://github.com/librariesio/libraries.io/issues/471

Help wanted Issue search

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb

Getting ready to move the rails app off heroku at the weekend 📦

Initial capistrano setup

---

app/views/api/docs/index.html.erb

@jlord and I are working on [a project](https://github.com/zeke/repos-using-electron/blob/master/index.js) to collect information about repos using electron.
We noticed there's no documentation about how to change the number of results per request, so we guessed `per_page` and it works! (Convention over configuration!)
This PR adds a section to the API docs about pagination, and documents the default values.
What is the maximum allowable value of `per_page`?

Improve API docs on pagination

---

app/views/dashboard/_monitoring_promo.html.erb
app/views/dashboard/index.html.erb

Added links to the promo icons
See screenshots

issue 755 add links to package manager promos

---

app/assets/stylesheets/_readme.scss
app/assets/stylesheets/_tree.scss
app/assets/stylesheets/application.scss

Some minor style amends, if you'd like 😁 
- margin above and below ads
- horizontal lines after `h1` and `h2`
- only show title anchor link icon on hover (as per bootstrap, github)
- more vertical spacing
- removed border from code blocks to be more like github (and added a bit more padding)
- bit of margin underneath tree view
I put all the new styles relating to readmes in a new stylesheet `_readme.scss`.
I reviewed it on a few readmes but I haven't got many on my localhost, so please do have a look before you merge :)

Misc style amends to repo readme and tree view

---

app/views/projects/dependent_repos.html.erb
app/views/projects/dependents.html.erb

Show the counts prominently on the `/<platform>/<project>/dependents` and `/<platform>/<project>/dependent-repositories` pages.
Please check I've not incurred any huuuuuge queries. Pretty sure I'm just using cached counts though 🙊 
Looks like this:

Show dependent repo/project counts prompinently on respective pages

---

app/models/github_repository.rb

Avoids issues like https://github.com/librariesio/librarian-parsers/issues/51 getting into the db 🚫

Ensure no duplicate deps (version and name) are saved

---

app/controllers/api/tree_controller.rb
config/routes.rb

Fixes #839
Urls like: 
```ruby
'https://libraries.io/api/npm/express/tree?api_key=XXX' # latest version
'https://libraries.io/api/npm/express/4.14.0/tree?api_key=XXX' #specific version
```
Requires an API key, so no anonymous access as it's quite intensive if not cached.
Some big trees may time out if they've not loaded within 60 seconds, need to come up with some way to say "check back in a minute" once #864 is complete.
Not going to add it to the documentation yet as the format may need to change but gives @whit537 something to play with for now.

Dependency Tree API endpoint

---

app/controllers/tree_controller.rb
app/models/tree_resolver.rb
app/views/tree/_tree.html.erb
app/views/tree/show.html.erb
app/workers/tree_resolver_worker.rb

Fixes #864 
Web page checks every second to see if the tree is cached and then renders it and stops checking

Resolve dependency tree in sidekiq and update with js

---

app/views/keywords/show.html.erb
app/views/languages/show.html.erb
app/views/licenses/show.html.erb
app/views/platforms/show.html.erb

Making them look more like the [Explore](https://libraries.io/explore) sidebar:

Improved display of sidebar filters on overview pages

---

app/controllers/api/bower_search_controller.rb
app/controllers/api/search_controller.rb
app/controllers/search_controller.rb
app/helpers/application_helper.rb
app/models/concerns/searchable.rb

Part 4 of #912 
Waiting on #917 being merged, will require reindexing all projects in elasticsearch (i.e partial downtime)

Allow sorting by dependent_repos_count in elasticsearch

---

app/assets/stylesheets/_usage.scss
app/assets/stylesheets/application.scss
app/controllers/project_usage_controller.rb
app/helpers/application_helper.rb
app/views/project_usage/show.html.erb
config/routes.rb

Usage statistics for projects

---

app/assets/stylesheets/application.scss

Fixes https://github.com/librariesio/support/issues/123. Probably. I committed this with toast in one hand.

Allow all h1/.h1 elements to wrap mid-word

---

app/controllers/project_usage_controller.rb

Forks may be skewing the numbers slightly, only showing non-forked repo usage data until we have a reliable way of determining if a fork is being used or just github mess left behind after a pull request.
Related to #934

Only show usage stats for non-forked repos

---

CONTRIBUTING.md

as briefly commented in https://github.com/librariesio/libraries.io/pull/975, this fixes a small naming mistake in the `contributing.md` file. hooray! 🎉

small fix in contributing guide

---

app/controllers/github_repositories_controller.rb
app/helpers/sourcerank_helper.rb
app/models/concerns/repository_source_rank.rb
app/models/github_repository.rb
app/views/github_repositories/sourcerank.html.erb
app/workers/update_repository_source_rank_worker.rb
config/routes.rb

Adds calculator and background job for calculating source rank for repos

Initial pass at repo source rank #477

---

app/controllers/sessions_controller.rb
app/models/concerns/github_identity.rb
app/models/github_repository.rb
app/models/identity.rb
app/models/recommendable.rb
app/models/user.rb
app/views/admin/project_suggestions/_project_suggestion.html.erb
app/views/admin/stats/index.html.erb
app/views/dashboard/home.html.erb
db/migrate/20170105065900_drop_old_user_fields.rb
db/schema.rb
spec/factories.rb
spec/models/user_spec.rb
spec/support/login_helpers.rb

I've moved all oauth data into identities so we can drop a lot of fields from the User model, only thing left to do is hook up the owning of github repositories to a user:
```ruby
has_many :github_repositories, primary_key: :uid, foreign_key: :owner_id
has_one :github_user, primary_key: :uid, foreign_key: :github_id
```

Drop unused user fields, fixes #1040

---

app/controllers/api/github_repositories_controller.rb
app/controllers/github_repositories_controller.rb
app/helpers/application_helper.rb
app/models/concerns/issue_search.rb
app/models/concerns/repo_search.rb
app/models/github_issue.rb

Fixes #1022
Fixes #1021
Don't merged until the majority of popular GitHub repos have had a rank calculated for them
These two rake commands need to be ran once this is merged and deployed:
rake github:reindex_issues
rake github:reindex_repos

Index rank in repo and issue search

---

app/controllers/sessions_controller.rb
app/views/accounts/show.html.erb

**headlines**
1) Lets make it so users can connect multiple bitbucket and gitlab accounts to their user profile!
(also why not multiple github accounts too)
Fixes #1074
**TODO's**
**latest screenshot**

Allow users to connect multiple accounts from settings page

---

CONTRIBUTING.md

On the project's guide to contributing clicking the README link lead to
a 404 error due to an incorrect path. Readme.md was used rather than
README.md.

Fix incorrect URL for link to project README

---

app/models/concerns/github_identity.rb
app/models/concerns/github_repository.rb
app/models/github_organisation.rb
app/models/github_user.rb
app/models/repository.rb

GitHub specific methods + constant belong in `GithubRepository`, not `Repository`.

Move GitHub specific constant + methods to `GithubRepository`

---

docs/add-a-package-manager.md

Details on adding support for a new Package Manager registry to the main application with links out to extra repos with soon to be added documentation.
Rendered view here: https://github.com/librariesio/libraries.io/blob/add-package-manager-docs/docs/add-a-package-manager.md
Fixes https://github.com/librariesio/libraries.io/issues/1031
Fixes https://github.com/librariesio/documentation/issues/9

Add documentation for adding support for a package manager

---

app/models/package_manager/base.rb
app/models/package_manager/cran.rb
app/models/package_manager/dub.rb
app/models/package_manager/homebrew.rb
app/models/package_manager/pub.rb
app/models/package_manager/pypi.rb
app/models/package_manager/sublime.rb
lib/tasks/documentation.rake

Fixes https://github.com/librariesio/documentation/issues/28
rake documentation:package_manager_matrix
Doesn't require any production data so can be ran locally in development environment.
Updated matrix in documentation using the output here: https://github.com/librariesio/documentation/blob/23bfcbade4a80200d016d54103e6e1adccff6e8d/packagemanagers.md

Add rake task to generate package manager support matrix

---

app/controllers/hooks_controller.rb
app/services/github_hook_handler.rb
spec/requests/hooks_spec.rb
spec/services/github_hook_handler_spec.rb

An abstract way of dealing with different kinds of GitHub webhooks. Will
be useful when solving #1174.
cc @andrew

Introduce GithubHookHandler

---

Gemfile
Gemfile.lock

Upgrade of the simplecov gem. Explicitly sets version in Gemfile to
0.14.1 and updates Gemfile.lock file.
Fixes #1297

Upgrade simplecov gem to 0.14.1

---

app/controllers/hooks_controller.rb
config/routes.rb
spec/requests/hooks_spec.rb

To be used by "watcher". Called when new package versions are released,
and need to be processed.
cc @andrew

Add `/hooks/package` endpoint

---

app/models/repository.rb
app/models/repository_host/base.rb
app/models/repository_host/bitbucket.rb
app/models/repository_host/github.rb
app/models/tag.rb
app/models/version.rb
app/services/firehose.rb
app/views/projects/show.html.erb
app/views/projects/tags.html.erb
app/views/projects/versions.html.erb
app/views/repositories/show.html.erb
app/views/repositories/tags.html.erb
app/views/versions_mailer/new_version.html.erb
app/views/versions_mailer/new_version.text.erb
config/routes.rb

For projects that have their source hosted on GH/GL/BB and push tags their when they release new versions we can do some cool things:
- Link to view the changelog or browse source for the tagged release: https://github.com/splitrb/split/releases/tag/v2.2.0
- Link to a diff between the current and previous version: https://github.com/splitrb/split/compare/v2.1.0...v2.2.0
This PR adds those links for versions and tags on projects and tags on repositories with a slightly redesigned list view:
Also adds the browse and compare links to new version emails if available and adds the links to the firehose json payload for lib2issues and lib2slack to use.

Release and diff urls for versions and tags

---

app/models/repository_host/github.rb
db/migrate/20170413091907_add_repository_user_id_to_repositories.rb
db/schema.rb

Part of https://github.com/librariesio/libraries.io/issues/1169
Needs to be merged and migrated before https://github.com/librariesio/libraries.io/pull/1344
Currently repositories have a weird relationship to users:
```ruby
belongs_to :repository_user, primary_key: :uuid, foreign_key: :owner_id
```
This is because when only GitHub repositories where supported we could just save the uuid from GitHub onto the repository model and hope that the user was already in the table without knowing it's id.
This doesn't work anymore because users aren't unique by their uuid, host_type also needs to be involved, so instead let's properly join them by primary keys so it ends up looking like this:
```ruby
belongs_to :repository_user
```
Will require a two stage deployment:
1. Add new column and start …

Change relationship between repository and repository user to be via primary key rather than uuid

---

app/controllers/projects_controller.rb
app/models/project.rb
app/views/projects/digital_infrastructure.html.erb
config/routes.rb

Todo
* fix pg query syntax
* double check render
* add test

Add (broken) cii experiment

---

app/models/issue.rb
app/models/repository_user.rb
db/migrate/20170518105429_rename_repository_user_id_to_uuid_on_issues.rb
db/schema.rb

Part 1.5 of https://github.com/librariesio/libraries.io/issues/1170
Previously the `repository_user_id` field on issues was used to store the uuid of github users directly from the API, with https://github.com/librariesio/libraries.io/pull/1431 we'll be storing GitLab and Bitbucket user ids too, so uuid isn't ideal here as active record relations don't really work with the data split across two fields.
Luckily we aren't using the relationship between issues and users yet so we can change the contents without breaking loads of things.
This pr makes a small change so that going forward we'll find/create the github user that opened the issue and save their primary key instead, then we can do the same for GL and BB users in https://github.com/librariesio/libraries.io/pull/1431
It also moves …

Find or create issue opener and store their primary key on issue instead of uuid

---

app/views/projects/index.html.erb

* remove ‘search by’ sections
* add persona-focussed info/CTAs
* reintroduce /explore
I have not included btn-groups in the two ‘success’ CTAs as they cannot reliably be set to width:100%. Could remove centre-block from the buttons however and re-introduce this as it does save a click (and the login page is very minimal). Open to comments. 
Fixes #1246

Refine homepage

---

.dockerignore
Dockerfile
config/sidekiq.yml
docker-compose.yml

:wave: This PR attempts to fix and clean up the Docker configuration needed for local dev, as it seemed to be broken. (Running `docker build` failed due to missing system dependencies). Key changes:
* Ignore some unneeded paths when building Docker image
* Parallelize gem installation during `docker build` for speed
* Add missing system deps (libicu-dev and cmake)
* Reduce verbosity of Sidekiq logging as it gets quite overwhelming quickly (let me know if this is not desired)
* Revamp docker-compose with the following improvements:
* Durable volume stores for the databases
* Pin versions of database images to avoid inadvertent drift
* Add Sidekiq container
Possible future improvements include adding Mailcatcher (easy), and supporting running tests via Docker (there are multiple …

Fixup Docker configuration for local dev

---

app/views/projects/index.html.erb

Just a quick update.  Played around with a few other options including:
- having two buttons
- having a fifth panel
- creating a combined data page
Didn’t like em. Rethink later.

Update homepage to prioritise /data release

---

app/views/search/index.html.erb

Just noticed this typo today while searching for libraries

Fixed typo: repetition of the word is "is is"

---

app/assets/stylesheets/application.scss
app/models/identity.rb
app/views/pages/_open_data_downloads.html.erb
app/views/pages/data.html.erb

Updated links to new zenodo release which should fix the zip errors people have been reporting: https://zenodo.org/record/833207

Update links to open data release for v1.0.1

---

app/models/package_manager/puppet.rb
lib/tasks/download.rake
spec/models/package_manager/puppet_spec.rb

This is pretty much just the minimal methods implemented, but lots of
the others are possible based on the capabilities of the API.
This aims to address #1026 
I'll follow up with additional commits to flesh out the other methods when I get a moment but this imports Puppet package details locally.

Initial work on supporting Puppet Forge packages

---

app/views/api/docs/index.html.erb

I've added some content to the "project search" section of the API docs that tells the reader they can specify the `sort` and `languages` parameters, with some example values.  Styling probably leaves something to be desired though... happy to refactor to taste.

Add sort/language params to search documentation.

---

app/controllers/api/application_controller.rb
app/controllers/api/subscriptions_controller.rb
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb

Set `ENV['READ_ONLY']` to true to disable all writes to the database via the web interface.
Disables any logged in actions, including logging in itself and disables three actions in the API subscriptions controller that allow changing data.
This doesn't stop incoming hooks being pushed into the redis queue, although it's assumed the workers won't be running whilst in read-only mode

Read only mode enabled by ENV var, fixes #1801

---

app/services/github_hook_handler.rb
spec/services/github_hook_handler_spec.rb

This reverts commit 96b822d584b46d60aef83918d4d46046af365be0.
Now that we have upgraded the database server we can start drinking from the full firehose again 🎉

Revert "Disable test for issue/pull request events from GH"

---

app/views/projects/_actions.html.erb
app/views/projects/show.html.erb

- Fixes #1752
This change adds a checkmark to the "subscribe" button and updates the copy to read "Already subscribed" when a user is viewing a project they are subscribed to. As mentioned in the issue, this more clearly differentiates between the two states.
Please note that this removes the conditional that would show the word "stable." Also, the Bootstrap grid widths were adjusted to accommodate the larger button size.

Update button copy for subscribed projects

---

config/routes.rb
spec/requests/api/projects_spec.rb

Some package names (notably java ones) have colons in their name.  Stick them in the set of allowed characters for the API similar to allowing @ in 0e7c59ecd3534badd56e14a55afca673baeeb7ff

Be more permissive in package names in the API

---

app/controllers/api/projects_controller.rb
app/views/api/docs/index.html.erb
config/routes.rb
spec/requests/api/projects_spec.rb

Useful for what @havocp is working on

Add API endpoint to return the sourcerank breakdown

---

app/models/package_manager/cocoa_pods.rb
spec/models/package_manager/cocoa_pods_spec.rb

Discovered whilst investigating https://github.com/librariesio/spdx/issues/42

Handle cocoapods license fields sometimes being a hash rather than string

---

app/controllers/repositories_controller.rb
app/models/concerns/github_identity.rb

Also forces syncing of all active user repos on a more regular basis
As reported by @splashinn

Improve syncing repos where permissions are required

---

app/helpers/open_data_helper.rb
app/views/pages/_releases.html.erb
app/views/pages/data.html.erb

Aiming to get the release out on 13th March, bits still to calculate:
Fixes https://github.com/librariesio/libraries.io/issues/2011

Preparing for open data release 1.2

---

app/models/package_manager/pypi.rb
spec/models/package_manager/pypi_spec.rb

Fixes #2024
Only thing that doesn't appear to work correctly on the new pypi.org is the rss feeds which are aren't matching with the ones on pypi.python.org at the moment, will wait for that to be fixed before merging.

Update pypi links from pypi.python.org to pypi.org

---

Gemfile
Gemfile.lock
config/boot.rb

Uses https://github.com/Shopify/bootsnap to shave a few seconds off the startup time

Speed up application start-up with bootsnap

---

app/controllers/admin/stats_controller.rb
app/controllers/api/application_controller.rb
app/views/admin/_nav.html.erb
app/views/admin/stats/api.html.erb
app/views/shared/_notice.html.erb
config/routes.rb

We need to get a bit more visibility on which API keys are using the API so we can advise active/heavy users about upcoming changes, requirements to optin to new terms of service etc
This pr adds recording of active api keys broken down by month, stored in redis, and an admin dashboard to see a breakdown:

Record API usage by month

---

app/controllers/api/docs_controller.rb
app/controllers/api/project_usage_controller.rb
app/views/api/docs/index.html.erb
config/routes.rb

Simple counts of version number/range usage on all open source, non-forked repos.
Fixes #999 
Example URL: https://libraries.io/api/npm/base62/usage
Example output:
```json
{
"*": 4,
"= 0.1.0": 1,
"0.1.0": 1,
"^0.1.1": 3,
"~0.1.1": 3,
"0.1.1": 6953,
"^0.1.2": 2,
"0.1.x": 1,
"^1.0.0": 3,
"^1.1.0": 62,
"~1.1.0": 1,
"1.1.0": 19,
"^1.1.1": 6,
"1.1.1": 109,
"^1.1.2": 13,
"1.1.2": 180,
"^1.2.0": 4,
"1.2.0": 1312,
"^1.2.1": 3,
"1.2.1": 1078,
"1.2.4": 1,
"1.2.5": 62,
"^1.2.7": 1,
"1.2.7": 648,
"1.2.8": 115,
"http://npm.tescloud.com/base62/-/base62-1.1.1.tgz": 1,
"http://registry.npmjs.org/base62/-/base62-0.1.1.tgz": 6,
"http://registry.npmjs.org/base62/-/base62-1.1.2.tgz": 1,
"http://registry.npmjs.org/base62/-/base62-1.2.0.tgz": 2,
"http://registry.npm.taobao.org/base62/download/base62-0.1.1.tgz" …
```

Add version range usage breakdown api

---

config/appsignal.yml

We get occasional requests for things in random formats; don't report to appsignal

Ignore ActionController:UnknownFormat errors

---

app/controllers/repositories_controller.rb
app/models/concerns/repo_search.rb

Stop getting back faceted aggregations to speed up queries on pages
like /github so that we don't timeout. We're not using the aggregations
and they're expensive for ES to compute

repo_search doesn't need facets on ES search

---

app/models/project.rb
app/serializers/project_serializer.rb
spec/rails_helper.rb
spec/requests/api/bower_search_spec.rb
spec/requests/api/projects_spec.rb
spec/requests/api/subscriptions_spec.rb
spec/serializers/project_serializer_spec.rb

This is a small step toward https://github.com/librariesio/libraries.io/issues/2169 , making available at least the latest download url.

Add a latest_download_url field to the projects API

---

app/models/package_manager/maven.rb
spec/fixtures/proto-google-common-protos-0.1.9.pom
spec/models/package_manager/maven_spec.rb

Ox.locate returns an array so we need to look at the first element
of the array for a lot of things. Also take advantage of the fact
that Ox.locate can take a path in the xml instead of constructing
that logic.
Add tests with a sample pom file to show things are working

Fix parsing various things out of pom.xml

---

app/models/package_manager/maven.rb

The download url is wrong for maven packages

Use only artifact rather than group:artifact in maven download urls

---

app/models/package_manager/packagist.rb

We want the metadata from the latest version of a package on packagist
but we can't count on them to be ordered in the return from packagist
so instead pull the most recently published non-dev version

Do a better job of finding the latest version for packagist

---

app/views/api/docs/index.html.erb

Very minor, but the error code generated by rack is (correctly) code 429 ("Too Many Requests") and not 403 ("Forbidden").
I noticed this when [running my spec suite on travis](https://travis-ci.org/marcandre/libraries_io/jobs/428830643#0-611). I now use VCR to avoid network calls at all...

Fix doc on limit error code [doc only]

---

app/views/api/docs/index.html.erb

I created an API wrapper for Ruby: https://github.com/marcandre/libraries_io
This PR adds a link to the relevant docs page.

Add link to Ruby wrapper

---

app/views/api/docs/index.html.erb

I noticed also that the API page has inconsistencies, as noted in [#2126].
This PR fixes the inconsistencies related to the links.
No attempt (yet) has been made to insure that the example output actually matches the API's output.

Fix project links in API doc page

---

app/models/package_manager/pypi.rb

This fixes up how we get the full list of packages from pypi per [PEP-503](https://www.python.org/dev/peps/pep-0503/)

Fix how we fetch the full list of package names from pypi

---

app/models/version.rb
app/views/projects/_statistics.html.erb
spec/models/version_spec.rb

Some package managers (notably cargo) use 'normal' for 'runtime'
deps so put that in the allowed kinds for runtime

Allow runtime dependencies to include 'normal'

---

app/models/concerns/releases.rb
app/models/project.rb
db/migrate/20181010192042_add_stable_release_to_projects.rb
db/schema.rb

This pulls the latest stable release and saves it along with the project much like is done with latest release. This way, we can get the information without having to do extra queries

Add information about latest stable releases to the project table

---

app/models/package_manager/nu_get.rb

nuget stopped updating registration1 a few months ago, we should
use registration3. It looks like everything we read out of the json
works just fine and it was already handling following the pages

Switch to the (non-deprecated) registration3 endpoint for nuget

---

app/views/repositories/show.html.erb

A link to all repos on github isn't that helpful and it times out pretty consistently

Remove link to /github which never loads

---

app/models/project.rb
spec/models/project_spec.rb

Allow basic spdx license mappings with OR and AND. Note that libraries
doesn't distinguish between the two with the current model so just
reporting both

Update normalize_licenses to handle basic SPDX style license expressions

---

Gemfile

It appears that in order for Puma to run in daemon mode it requires the `listen` gem. Moved that dependency to the production list so that it is available at deploy time.

Moved listen gem to production list for PUma daemon mode

---

app/views/api/docs/index.html.erb
app/views/pages/_open_data_documentation.html.erb
app/views/repository_users/projects.html.erb
docs/add-a-package-manager.md

Its = belonging to it.
It's = it has, or it is.
It sort of makes sense when one considers one's yours, theirs, and hers,
which works so long as one's prepared to overlook one's one's. : )
https://en.oxforddictionaries.com/definition/its
- It would be pretty cool to run all your prose through a grammar checker but I think it's out of scope for this PR ;)
- No, I was too lazy to do this, but the change is so minor that I probably haven't broken anything.

Fix grammar: possessive its

---

app/models/user.rb
spec/models/user_spec.rb

User.watched_dependent_projects is used on the homepage for User.all_subscribed_versions
and ends up being a pretty slow query
```sql
SELECT "projects"."*" FROM "projects" INNER JOIN "repository_dependencies" ON "projects"."id" = "repository_dependencies"."project_id" INNER JOIN "manifests" ON "repository_dependencies"."manifest_id" = "manifests"."id" INNER JOIN "repositories" ON "manifests"."repository_id" = "repositories"."id" INNER JOIN "repository_subscriptions" ON "repositories"."id" = "repository_subscriptions"."repository_id" WHERE "repository_subscriptions"."user_id" = ? GROUP BY projects.id
```
We can speed this up by making explicit queries that just return ids as necessary
and then querying by id (primary key) rather than ending up doing large table scans

Optimize how we get the watched dependent projects

---

config/github_graphql_schema.json
lib/tasks/github.rake

Created `github:update_github_v4_api_file` rake task. The task is configured to take in a Github API token directly as the first argument or through an environment variable `GITHUB_TOKEN`. This will query the API for it's schema and store the file `config/github_graphql_schema.json`. The way to update the schema is to run this task with a valid token, update the file, and then make a commit to this repository with the updated schema file.

Rake Task to Update Github V4 API Schema File

---

app/controllers/api/application_controller.rb
app/controllers/api/status_controller.rb
app/models/project.rb
app/serializers/project_status_serializer.rb
app/serializers/repository_maintenance_stat_serializer.rb
spec/factories.rb
spec/requests/api/status_spec.rb

Added the repository stats to the project response in the status controller and added some tests to verify the response is correct. I also added the requirement for an internal API key to hit this URL.

Add Maintenance Stats to the project status response 

---

config/sidekiq.yml

The sidekiq configuration file has a different queue name than what the worker is expecting/using.

Fix Queue Name

---

Gemfile
Gemfile.lock
config/initializers/rack_timeout.rb

Rack::Timeout leads to leaking of database connections as requests
timeout and that then takes things down. Let's instead let requests
run a little longer

Remove rack-timeout

---

app/models/project.rb
lib/tasks/projects.rake
spec/models/project_spec.rb

Added rake tasks to update a project's maintenance stats and to fill in those stats for project's without any.

Rake Task to Process Repository Maintenance Stats

---

lib/tasks/projects.rake

Should let us change the amount of projects we want to dump in the queues in the cron jobs without having to deploy a new version of libraries.io

Pass in # of Projects to Sync in Rake Tasks

---

app/models/package_manager/nu_get.rb

This parses nuget licenseExpressions which are the current way
to give a license for a nuget package (see
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg).
To support older packages, we'd also need/want to look at licenseUrl
but that then would require downloading and evaluating the contents
of that file. Given nuget is deprecating and not allowing it for new
versions, this feels like it'll cover things as they're released
and is the current best practice for the ecosystem

Parse nuget licenses

---

app/models/package_manager/maven.rb

Previously the Maven PackageManager relied on the ordering provided by the Maven repository website and resulted in Java packages having very out of date data.

Change latest_version to Sort by Date and Pick the Most Recent

---

app/models/gather_repository_maintenance_stats.rb
spec/models/gather_repository_maintenance_stats_spec.rb

Also look at project's tied to the repository and make sure they are pointed to Github as well before trying to gather maintenance stats.

Check Project for GitHub URL

---

app/models/package_manager/base.rb
app/models/project.rb
spec/models/project_spec.rb

This might help with a few repositories that have an old poorly formatted repository url and do not find a new one to reformat on sync.

Reformat Project repository_url On Save

---

app/models/project.rb
app/workers/package_manager_download_worker.rb

Add a log message when starting a sync so we can search for it in the logs to figure out what is going on with packages that are not syncing correctly. Also changed when `last_synced_at` is set so that it is set during the update and not when the request is made.

Add Log Message to Trace Sync Errors

---

app/controllers/api/projects_controller.rb

They are already ordered by this on the main Project page.

Order Contributors by the Number of Contributions in API

---

app/models/repository.rb
app/workers/repository_maintenance_stat_worker.rb

This will remove the unique requirements when adding a repository to the maintenance stat queue. The digests are not being reliably removed from Redis which results in a repository being locked out from getting refreshed, potentially permanently. It appears to be a known issue in the unique jobs gem: https://github.com/mhenrixon/sidekiq-unique-jobs/issues/379
Keeping the repository requests unique is potentially useful, but more care needs to be taken on creating/removing the locks. Perhaps the gem will provide a fix that could be used again later?

Remove Unique Digests

---

app/models/concerns/project_search.rb
spec/models/concerns/project_search_spec.rb

Looks like this may have been broken in #2269
You must define `marshal_load` if you define `marshal_dump` (https://ruby-doc.org/core-2.6/Marshal.html)

Define ProjectSearch#marshal_load to match marshal_dump

---

app/models/concerns/source_rank.rb

We call the async worker when we're updating a record. So updated_at
is always going to be recent. This means we're not actually updating
source ranks regularly
Fixes #2324

We need to always update source rank instead of deciding based on updated_at

---

app/models/tree_resolver.rb

I'd like to have version information in the tree API for use elsewhere - this seemed like the sanest approach? Open to other ideas.

Put normalized_licenses in tree

---

app/controllers/api/docs_controller.rb
app/controllers/api/projects_controller.rb
app/controllers/api/repositories_controller.rb
app/serializers/dependency_serializer.rb
spec/requests/api/projects_spec.rb
spec/serializers/dependency_serializer_spec.rb

I'd like to have `normalized_licenses` in the dependencies API schema
I opted to modify all uses of `map_dependencies` to avoid n+1 queries rather than introduce another serializer.

Add normalized_licenses to dependencies view

---

Gemfile
Gemfile.lock

This updates the `bibliothecary` gem from [v6.4.0 -> v6.7.0](https://github.com/librariesio/bibliothecary/compare/v6.4.0...v6.7.0). Includes some pom.xml improvements, Go Module support, and more.

bibliothecary v6.4.0 ~> v6.7.0

---

app/models/package_manager/maven.rb
spec/fixtures/proto-google-common-protos-0.1.9.pom
spec/models/package_manager/maven_spec.rb

This will look into the POM xml for an artifact and if there is a parent specified it will also look up the parent POM file recursively. Values are overwritten by the child POM file and missing values are carried down from the parent. This should hopefully help with some of the Maven data being missing or incorrect.

Maven: Look up Parent POM for Information

---

app/models/package_manager/maven.rb

`repo_fallback` and the `licenses` map return empty strings if there is no information. This overwrites the parent information if it is available. This PR initializes the Hash to match that logic and ignores empty values from the child POM before merging the two.

Ignore Empty Strings from Child POM Info

---

app/models/package_manager/maven.rb

There is no current usage for `groupId` but this is clearer going forward.

Separate groupId and groupPath to Preserve the Actual Group ID

---

Gemfile
Gemfile.lock
app/models/package_manager/base.rb
app/models/package_manager/maven.rb
spec/fixtures/proto-google-common-protos-0.1.9.pom
spec/spec_helper.rb

Use Bibliothecary to expand properties in POM files. Gather properties from parent projects and send those in alongside child pom files.

Expand Maven Properties

---

app/controllers/api/status_controller.rb
app/models/package_manager/base.rb
app/models/package_manager/pypi.rb
app/models/project.rb
spec/models/package_manager/pypi_spec.rb

Still need to do some more testing locally to make sure nothing is screwed up with this, but wanted opinions. This creates a method in package managers to have a suggested list of names to use to find projects. For all the cases except Pypi, this is just the project name. For Pypi this includes replacing hyphens with underscores and vice versa. This is to help mimic the same mechanic that Pypi supports and would help find projects when reading Python dependency manifests.

Handle Hyphens and Underscores for Pypi Projects

---

app/controllers/api/status_controller.rb
app/models/package_manager/base.rb
app/models/project.rb

Catching errors was not catching everything it needed to and this seems like a better way to get the correct package manager class to call.

Fix Package Manager Name Lookup

---

app/models/package_manager/maven.rb

Could also have gone with `respond_to?(:nodes)` if that feels better?

Don't error if a property node has no `nodes`

---

app/models/package_manager/maven.rb

Fixes #2392 - the problem here is not that `prop_node` is missing, but that it doesn't have `nodes`

Only consider nodes for prop_nodes that have them

---

app/controllers/application_controller.rb
app/models/package_manager/go.rb
app/models/project.rb
spec/models/package_manager/go_spec.rb
spec/requests/api/projects_spec.rb

There's a balance to be struck here - at what point do we just start using `go get`?
This only handles metadata redirects to github.com urls - we may want to expand that, but I wanted some discussion.

Basic support for metadata redirects

---

app/controllers/api/status_controller.rb
app/queries/project_status_query.rb
app/serializers/project_status_serializer.rb
spec/queries/project_status_query_spec.rb
spec/requests/api/status_spec.rb

Two changes here:
1. Serve project data with the name that was used to request it
2. Handle Go redirects in the bulk status API
Think I should centralize some of this Go handling somehow?

Support Go redirects in bulk API

---

app/views/accounts/show.html.erb

Add space after period in "API Key" section of account settings page.
Other questions: no; this is formatting of a user-visible string, should not affect functionality.

Fix spacing on account settings page

---

app/models/repository_tree_resolver.rb
app/models/tree_resolver.rb
spec/models/tree_resolver_spec.rb

Two things I wanted to change here:
1. Increase max tree depth to 15 (which lets eg: `npm/gulp` get to the leaves of its tree)
2. Remove the `["MORE"]` magic string when truncating
To get there, I did some refactoring.
The "Add TreeResolver tests" commit adds tests for `TreeResolver` that pass before any changes to that class.
Probably best to review this commit-by-commit!

Increase tree depth

---

app/models/repository_host/base.rb
spec/workers/repository_maintenance_stat_worker_spec.rb

I noticed a lot of failed Sidekiq messages because Gitlab repositories would getting stats synced. This should fix the errors causing the Sidekiq jobs to fail and reduce some churn in the workers.

Avoid Error on Missing Method

---

app/models/package_manager/base.rb

This was specifically made to try and help reduce our errors when calling for Python dependencies. This will skip a version if we have already seen dependencies for it, which should hopefully cut down on calls. This also adds a retry to the connection object used in the `PackageManager` classes.
I think a lot of the Python libraries do not have any dependencies. I would love some thoughts on how to prevent duplicate calls for packages like that. Perhaps adding a `deps_last_updated` time column for `versions`?

Retry on Calls to Get Dependencies

---

docs/development-setup.md

I re-ran the instructions for `Development Setup` recently on OSX, and a few things have changed. This updates the instructions.

Update homebrew instructions -- some stuff needs brew cask now

---

app/workers/package_manager_download_worker.rb
spec/models/package_manager/go_spec.rb

I think this may be causing issues with packages never syncing. I've run into issues before where the lock on a job is never cleared.

Remove Unique Setting for Package Download Worker

---

app/helpers/application_helper.rb
app/views/meta/_seo.html.erb

Let's stop the googlebot from indexing things that are removed packages or packages that don't exist
/cc @amytidelift

Add noindex meta tags for removed/non-existent pages

---

app/controllers/api/bulk_project_controller.rb
app/controllers/api/maintenance_stats_controller.rb
app/controllers/api/status_controller.rb
config/routes.rb
spec/requests/api/maintenance_stat_spec.rb

This creates a new endpoint that lets us take in a list of projects to watch for maintenance stats. I've reused the queries and work done in the StatusController to handle looking up the Projects and moved that code to a common controller class.

Create Endpoint to Begin Watching Projects Maintenance Stats in Bulk

---

app/views/projects/_releases.html.erb

This fixes the Tagged Releases side bar to match the Releases Side bar.
there was a missing `<dt>` here, which caused the `<dl>` css margin-bottom: 20px to add it on every row, not just the block.

match dl/dt order for tagged releases

---

app/models/package_manager/packagist.rb
spec/models/package_manager/packagist_spec.rb

The Packagist spec says:
> When branch names look like versions, we have to clarify for composer that we're trying to check out a branch and not a tag. In the above example, we have two version branches: v1 and v2. To get Composer to check out one of these branches, you must specify a version constraint that looks like this: v1.x-dev. The .x is an arbitrary string that Composer requires to tell it that we're talking about the v1 branch and not a v1 tag (alternatively, you can name the branch v1.x instead of v1). In the case of a branch with a version-like name (v1, in this case), you append -dev as a suffix, rather than using dev- as a prefix.
Currently there are about ~60k Packagist releases with this suffix, like [this one](https://libraries.io/packagist/graham-campbell%2Fsecurity): …

Ignore `.x-dev` Packagist versions that aren't releases as defined by spec.

---

Gemfile.lock
app/models/concerns/dependency_checks.rb

Upgrades semantic_range to pull in https://github.com/librariesio/semantic_range/pull/69, plus one additional change to stop if `max_satisfying` can't find a version.

Newest semantic_range

---

docker-compose.yml

Small tweak to fix redis service url for running with docker-compose

Update to correct redis url for docker-compose services

---

app/models/package_manager/pypi.rb

pypi has clarified that keywords are supposed to be comma separated
but the spec historically said space (... even though the tools
have mostly worked with commas). So be generous in what we support
Fixes #2507

Handle comma or space separated keywords for pypi

---

app/models/package_manager/npm.rb
app/workers/license_backfill_worker.rb

There are about ~500k failing ﻿﻿LicenseBackfillWorker jobs in Sidekiq because the projects are yanked and don't have versions. This handles this gracefully and assumes these packages have 0 versions.
Example for `npm/bundlerjs`:
```
curl http://registry.npmjs.org/bundlerjs | jq
{
"_id": "bundlerjs",
"name": "bundlerjs",
"time": {
"modified": "2019-11-13T20:00:39.709Z",
"created": "2014-09-15T14:35:48.983Z",
"0.0.0": "2014-09-15T14:35:48.983Z",
"unpublished": {
"name": "npm-support",
"time": "2019-11-13T20:00:39.708Z",
"tags": {
"latest": "0.0.0"
},
"versions": [
"0.0.0"
],
"maintainers": [
{
"name": "ericprieto",
"email": "ericprieto@live.com"
}
]
}
}
}
````

Handle yanked/hidden NPM packages that have no versions.

---

app/assets/javascripts/application.js

This looks like "just a typo" that has no real consequence for an ordinary user!
Was introduced by https://github.com/phil-davis/libraries.io/commit/da555b600012656d2a2e89160b251a1c0dea9f35

Fix typo of 'change' in app/assets/javascripts/application.js

---

.github/CONTRIBUTING.md

This is just a minor review of https://github.com/librariesio/libraries.io/blob/master/.github/CONTRIBUTING.md
(I don't think I need to create an issue for this?)

Add Documentation link in CONTRIBUTING.md and fix some typos

---

config/locales/en.yml

Fixes issue #2546 
Condense the "number" section in `config/locales/en.yml` to a single section.

Remove duplicated number section in config/locales/en.yml

---

bin/deploy.sh

Fixes issue #2544 
If something goes wrong with `gcloud --quiet container images describe ${TAGGED_IMAGE}` then:
- save the status of the command
- echo the existing test to stderr
- exit with the saved status
This will let the caller have both the human-readable text in stderr and the actuall error status of the `gcloud`  command.

Echo error and then exit in bin/deploy.sh

---

app/controllers/api/application_controller.rb
app/controllers/api/projects_controller.rb
app/controllers/api/status_controller.rb
app/models/deleted_project.rb
app/models/project.rb
app/serializers/project_serializer.rb
app/serializers/project_status_serializer.rb
config/routes.rb
db/migrate/20200709221449_create_deleted_projects.rb
db/schema.rb
spec/models/project_spec.rb
spec/requests/api/projects_spec.rb
spec/requests/api/status_spec.rb
spec/serializers/project_serializer_spec.rb

The /updated endpoint returns a list of packages with updated_at
in a given time window.
The purpose of this is to simplify mirroring.

Included updated_at in package API replies and add /updated endpoint

---

bin/deploy.sh

PR #2545 "enhanced" the error handling in `bin/deploy.sh` But the command is now always exiting. It should exit only when there was an error.
Put the sequence of error-handling commands in brackets so that they are all considered together as a group on the right-side of the "or" expression.
http://www.gnu.org/software/bash/manual/html_node/Command-Grouping.html - I used the "curly braces" grouping because that does not create a subshell. There is less thinking with that - we want to save the status, emit some text, then exit the current shell. Using `()` syntax would send us down into a subshell.

Fix operator-command precedence in deploy.sh

---

app/models/package_manager/nu_get.rb
app/views/shared/flashes/idc-webinar.html.erb

More nuget packages are being released with semver2 style
versioning; this will let us index those versions

Use the newer semver2 endpoint to get more nuget packages

---

db/migrate/20200921173826_convert_repository_dependency_id_to_big_int.rb
db/schema.rb

* converts `repository_dependencies.id` from integer to bigint 
This migration assumes that we're ok waiting for the table lock, and just temporarily serving bad data for this table until it's done.

 RepositoryDependency id migration step 2: migrate from integer to bigint

---

app/views/api/docs/index.html.erb

Fixes #2361 
Uses `source_rank_breakdown` instead of `source_rank` to show output as defined in `app/controllers/api/projects_controller.rb#L8`
```ruby
def sourcerank
render json: @project.source_rank_breakdown
end
```

fix(API-Doc): show correct Output for SourceRank

---

app/models/package_manager/base.rb

The code that was changed here in https://github.com/librariesio/libraries.io/pull/2590 wasn't functionally equivalent. We need to create using the hash passed in to grab other data points outside of the version number like the published date.

Add create(hash) Back into Version Save

---

app/models/package_manager/base.rb
app/models/package_manager/maven.rb
app/models/package_manager/maven/maven_central.rb
app/models/package_manager/maven/spring_libs.rb

This tries to remove some properties set in the Maven package manager and defer to the MavenCentral provider. This also changes some logic in the Base package manager to not use `self.name.demodulize` when looking/saving the platform on `Project` and instead use a new property called `db_platform` that defaults to `self.name.demodulize` but is overridden in the Maven provider classes so it all still works.

Clean Up Maven Package Manager

---

app/controllers/hooks_controller.rb
app/models/package_manager/base.rb
app/models/package_manager/maven.rb
app/models/project.rb
app/workers/package_manager_download_worker.rb
lib/tasks/download.rake
lib/tasks/projects.rake
spec/workers/package_manager_download_worker_spec.rb

Adjust the `rake download:maven` tasks to take in an optional provider parameter to run the sync with.

Maven Download Rake Tasks For Multiple Repository Sources

---

app/models/package_manager/maven.rb

This temporarily fixes the project sync button for Maven projects. This still needs to be fixed to allow Maven to pick the right provider to use for those projects.

change default repository_source_name in Maven

---

app/models/package_manager/maven.rb
app/models/project.rb

Right now the resync button is broken for any project that doesn't use the default Maven Central provider. This PR would run the sync through all provider classes that this project has in it's Versions.

Project Sync with Multiple Providers

---

app/models/package_manager/go.rb
lib/tasks/download.rake

Previously the go download task was only looking at new unknown packages. This would change it to update every project from the recent index listing on index.golang.org.

Run Go Download as import_recent

---

app/models/package_manager/go.rb
spec/models/package_manager/go_spec.rb

This is very broken. I thought the tests had covered it, but without an existing database version none of the bad code was hit. Fixed the type and return issues and added a spec that now hits that code.

Fix Type Issues in Go.update()

---

lib/tasks/projects.rake

This task would go through and start updates for Go modules that have a `/vx` on the end of the name. The intention is to get the base module project in place if it doesn't exist and then run the update on the versioned module to get versions added correctly to both projects.

Update Go Versioned with Base Modules

---

app/models/package_manager/maven.rb
spec/models/package_manager/maven_spec.rb

When parsing versions of a Maven project, we may come across a version with a missing pom (or in the case below, a missing parent pom). 
Currently `retrieve_versions` will blow up if any versions are missing, so instead of blowing up and not updating *any* versions, let's update the versions that work still and ignore the broken version.
As precedent, we're [skipping bad versions](https://github.com/librariesio/libraries.io/blob/master/app/models/package_manager/go.rb#L110-L111) in Go currently too.
Pom: https://repo1.maven.org/maven2/org/opencastproject/opencast-common/8.5/opencast-common-8.5.pom
Parent pom: https://repo1.maven.org/maven2/org/opencastproject/base/8.5/base-8.5.pom
Pom: https://repo1.maven.org/maven2/org/opencastproject/opencast-common/7.7/opencast-common-7.7.pom
Missing …

Maven: skip versions that have missing poms, rather than raising err.

---

app/mailers/versions_mailer.rb

Quick fix for a job failure that shows up a lot for `VersionsMailer#new_version ` jobs:
`"undefined method `empty?' for nil:NilClass"`

Fix VersionsMailer nil email bug

---

app/models/project.rb
spec/models/project_spec.rb

* removes the `Project#sync` method because I don't think it's called from anywhere
* instead of checking deprecation/removal status via ^, we can check it by kicking off `CheckStatusWorker` when an async sync happens on the project
NB There **are** currently deprecated and removed projects in the database, but I think that's because Projects **sometimes** get marked as such by their parent repository [here](https://github.com/librariesio/libraries.io/blob/41159948ff612c0813f909b73a4bda697bb92e7f/app/models/repository.rb#L272-L287). In NPM's case, deprecation happens via the NPM CLI, so we'd never get triggered to update the Repository's status. This should update it more often on Projects.

Kick off CheckStatusWorker in Project#async_sync.

---

app/controllers/errors_controller.rb
app/views/errors/not_acceptable.html.erb

Noticed a lot of noise in the container logs for the ErrorsController endpoints:
```
2020-12-10 16:26:16.558 EST Error during failsafe response: ActionController::UnknownFormat
2020-12-10 16:26:16.558 EST /libraries.io/app/controllers/errors_controller.rb:3:in `not_found'
2020-12-10 16:26:16.558 EST /usr/local/bundle/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:194:in `process_action'
2020-12-10 16:26:16.558 EST /usr/local/bundle/gems/marginalia-1.8.0/lib/marginalia.rb:111:in `record_query_comment' 
...
```
This should at least quiet it in the logs.

Add fallbacks for error endpoints and backfill a missing template.

---

app/views/layouts/application.html.erb

More stuff I've noticed in the logs. These are in the asset pipeline so they need to be linked via `asset_url` so they get the proper hash at the end and the `/assets` prefix.

Fix broken asset urls.

---

lib/tasks/projects.rake

Hah! `count` is a method on args, not the actual arg. Silly mistake.

Fix argument in Go rake task.

---

app/models/package_manager/npm.rb
spec/models/package_manager/npm_spec.rb

This maps to NPM's logic, where the latest version is displayed for the package landing page, and the deprecation message shows up at the top if that version is deprecated.
For example, buildmail:
* https://www.npmjs.com/package/buildmail <-- deprecated, bc it's really 4.0.1
* https://www.npmjs.com/package/buildmail/v/4.0.1 <-- deprecated
* https://www.npmjs.com/package/buildmail/v/3.0.0-beta.0. <-- not deprecated

Only consider package deprecated if the last version is deprecated.

---

app/controllers/api/status_controller.rb
app/serializers/optimized_project_serializer.rb
config/initializers/active_model_serializers.rb
config/initializers/google_cloud_trace.rb
lib/query_counter.rb
spec/requests/api/status_spec.rb

An attempt at optimization for the check endpoint. 
Initially I assumed this was going to be an N+1 fiesta, but in digging around here, it seems like queries are optimized quite nicely thanks to some work done by @kbarrette in https://github.com/librariesio/libraries.io/pull/2399 and https://github.com/librariesio/libraries.io/pull/2418. Turns out the bulk of the work happens in serialization. This adds a stripped down serializer that avoids active model serializers entirely, and tries to optimize a little bit (merge! vs merge, etc...). We also force usage of Oj for json serialization in this endpoint, something we probably want to explore doing universally. I've left a couple things that seemed useful that I hacked in to do some optimization.
A test run on my machine using 500 …

Optimize status check endpoint

---

.gitignore
Dockerfile
cloudbuild.yaml
config/environments/production.rb
config/initializers/git_revision.rb
spec/requests/pages_spec.rb

This is a lot of plumbing so that static assets are assets/GIT_HASH/ and that they then end up pushed to google cloud storage by cloud build

Set up pushing static assets to GCS

---

app/controllers/api/bulk_project_controller.rb
app/controllers/api/status_controller.rb
app/queries/project_status_query.rb
app/serializers/optimized_project_serializer.rb

Ditching AR includes and plucking what we need for versions and maintenance stats makes this over 4x faster now in a local test with 500 projects.
```
/api/check?v2=true
0.848421   0.020203   0.868624 (  0.892780)
/api/check
3.559839   0.027464   3.587303 (  3.628964)
```

Further check endpoint optimizations

---

app/controllers/api/project_usage_controller.rb
app/controllers/project_usage_controller.rb

repositories is way too big and we're table scanning; just include
forks in the counts as it's not going to skew things much and will
be _way_ more performant

Don't exclude forks in project usage to avoid bad queries

---

app/models/package_manager/pypi.rb
app/models/project.rb
spec/models/package_manager/pypi_spec.rb

Pypi is similar to NPM in that it only allows specific releases to be "yanked", but having the latest release yanked is treated as if the whole package is yanked.
NB: according to PEP 592, yanked packages are still downloadable, and they won't be used by package managers unless they're the only possible release that satisfies a manifest.

Add package-deprecation support for pypi yanking.

---

app/models/package_manager/base.rb
config/initializers/elasticsearch.rb
config/initializers/octokit.rb

We're not hitting the same URLs over and over so this is just overhead
and driving up memcache usage without being effective.

Stop using faraday http cache where it is unlikely to help

---

Gemfile
Gemfile.lock
config/initializers/fuzzy_match.rb

sidekiq workers crash fairly often with a segfault in amatch. Let's
just use fuzzy match and see if things are more stable; the speed
cost is less important for a background processing job

amatch is segfaulting; let's try not using it

---

app/workers/package_manager_download_worker.rb

I'd like to think about a registration process for packagemanagers so we don't have to manually maintain this, but this will get us back up and running on Maven stuff for now.

Include maven repository package managers

---

app/models/package_manager/pypi.rb
spec/models/package_manager/pypi_spec.rb

Previously in https://github.com/librariesio/libraries.io/pull/2658 we started marking PyPi packages as "deprecated" if their latest release was "yanked", per the new PEP-592.
There's also an older method of renaming a project, via [PEP 423](https://www.python.org/dev/peps/pep-0423/#how-to-rename-a-project), which looks to have been used to deprecate projects too. This adds support for them.
Examples in [the wild](https://pypi.org/search/?q=&o=&c=Development+Status+%3A%3A+7+-+Inactive):
* [explicitly deprecated package](https://pypi.org/project/fake-factory/)
* [a package deprecated bc it's buggy](https://pypi.org/project/tempstorage/)
* [an unmaintained Python 2 package](https://pypi.org/project/multilint/)
* [stable but proactively marked as inactive](https://pypi.org/project/memtop/)
* …

Add deprecation support for older 'development status' pypi classifier.

---

app/models/package_manager/pypi.rb
spec/models/package_manager/pypi_spec.rb

Forgot to include the `"info"` JSON namespace.

Quickfix for Pypi old-style deprecation detection.

---

app/models/package_manager/pypi.rb

We get a 301 instead of 404 without the slash, which was breaking the `check_status_url` method for Pypi projects.

Add necessary trailing slash to pypi deprecation url.

---

app/models/package_manager/packagist.rb
spec/models/package_manager/packagist_spec.rb

The only way for a Composer package to mark itself as "deprecated" is via the [`abandoned` keyword in composer.json](https://getcomposer.org/doc/04-schema.md#abandoned) (NB this is also supported per-version)
Composer also lets you define a replacement package as that value, so this PR records the replacement package as the deprecation message.

Packagist: save replacement library as deprecated message if it exists.

---

Gemfile
Gemfile.lock

Libraries requires `github-markup`, which uses `github-linguist` to do syntax highlighting. Some slowness arises from `github-linguist` loading some big JSON files using either `Yajl` (faster) or `YAML` (slower): https://github.com/github/linguist/search?q=%22defined%3F%28yajl%29%22
`github-linguist` only adds `yajl-ruby` as a development dependency, so we don't get it in our lockfile. Adding that gem should decrease boot time by ~2 seconds. 
```
$ time bin/rails r ""
real    0m7.590s
user    0m5.360s
sys     0m1.341s
```
```
$ time bin/rails r ""
real    0m5.497s
user    0m3.395s
sys     0m1.286s
```

Libraries boot time: add Yajl gem so github-linguist will load its samples faster.

---

app/models/package_manager/base.rb

404s, etc all lead to things blowing up later but parsing "" seems
to do a little better

Ignore errors on requests

---

app/services/url_parser.rb

We pass frozen strings into url parser sometimes which blows up
when we later do regexes on those strings so dup to lose the frozen
state

dup strings in url parser so we don't try to modify frozen strings

---

app/models/maintenance_stats/stats/github/contributor_count_stats.rb

This avoids an error when there haven't been weeks_ago contributions
to the project which ends up doing array[-52..-1] and if the array
only has 50 items, we get back a nil.
Instead get back contributions based on the max size of the window
b

Enusre we're not trying to look at earlier than the first contribution

---

app/models/package_manager/go.rb
app/models/project.rb

The pkg.go.dev url we were using would return 405 for any HEAD request. This proxy url, instead, returns 200 for found and 410 for not found.

Fix check_status_url for golang.

---

app/models/package_manager/go.rb

Ignore versions that have case-insensitive name collisions instead of blowing up when we try to fetch their info.
* [example Go Module version with name collision](https://github.com/ysweid/aws-sdk-go/tree/v1.12.68/models/apis)
* [breaking url for ^](https://proxy.golang.org/github.com/ysweid/aws-sdk-go/@v/v1.12.68.info)
* [Go issue](https://github.com/golang/go/issues/33778)

Handle unfetchable Go versions that have name collisions.

---

app/models/package_manager/go.rb

Followup to https://github.com/librariesio/libraries.io/pull/2687
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/600f04159833b70018bd5b9f

Select created_at when getting Go versions in case published_at nil.

---

app/models/package_manager/hackage.rb

A FAQ link was added to one of the side bar titles ([example](http://hackage.haskell.org/package/atp)), so this just checks the beginning of the sidebar title. Doesn't look like they've added a JSON version of this yet either.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffc9822aa4acf00198281f9

Fix Hackage scraping that broke bc of a new anchor link in Versions

---

app/models/package_manager/cargo.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60118a93fa872a00174d9f44?event_id=60118a930069a0686dd20000&i=sk&m=nw

Ensure we require rubygems for the tar reader.

---

app/models/package_manager/cocoa_pods.rb

Sometimes pods that are in our api feed are missing when we look them up in our [api](https://github.com/librariesio/cocoapods-api/). Not sure why yet, but this prevents the pod from raising an error until we can look deeper.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6006f83938be280017c6f1ef?event_id=6010aeb4006995105ac80000&i=em&m=fq

Silence missing Cocoapods until we can fix the feed.

---

app/models/version.rb
app/workers/version_notifications_worker.rb
spec/workers/version_notifications_worker_spec.rb

I'd like to get some stats and this seemed to be an easy way. What I'm seeing is really odd though in that the time for method execution isn't even close to accounted for in the calls within it. I think I'm misunderstanding something.
```
Benchmark.measure { Version.order("random()").first.send_notifications }.real * 1000
Version#send_notifications benchmark overall: 1921.9531649998771ms dt:1894.0594109999438ms ns:3.391713000155505ms nf:24.29645300003358ms nw:0.05531300007532991ms
=> 23714.67944799997
```

Lower 'queue weight' of version notification worker and benchmark

---

app/workers/package_manager_download_worker.rb
config/initializers/sidekiq.rb

Seems useful overall, but trying to figure out the problem with a Maven job that's failing:

Include stacktrace for debugging PackageManagerDownloadWorker

---

Gemfile.lock

[bibliothecary diff](https://github.com/librariesio/bibliothecary/compare/v6.8.7...v6.9.7)
Should silence these errors: https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffcc76ae4560f0017add9ac?event_id=60142d1f00699a746d010000&i=em&m=fq

bibliothecary 6.8.7 ~> 6.9.7

---

app/models/project.rb

We should refactor Project#check_status into the PackageManager classes, but this is a quick bandaid.
May fix, but not sure: https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6007059462591d001892e3a9

Properly set removed property of CheckStatusWorker job.

---

cloudbuild.yaml

The docker builds have been timing out recently -- this just extends it a few more minutes, so we can deploy the latest commits.

Timeout in Cloud Build after 12 min, instead of default 10 min

---

lib/tasks/one_off.rake

There are 20k Maven projects with no group id in their name, and their statuses are all "Hidden". They were all created around the same dates in 2015 and 2018 too. 
Not sure the history behind this batch of Maven projects, but I propose deleting them.
```
Project.where(platform: "Maven").where("name NOT LIKE '%:%'").count
=> 20063
Project.where(platform: "Maven").where("name NOT LIKE '%:%'").group(:status).count
=> {"Hidden"=>20063}
Project.where(platform: "Maven").where("name NOT LIKE '%:%'").group("DATE(created_at)").count
=> {Sun, 07 Jun 2015=>1, Mon, 02 Jul 2018=>17, Thu, 28 Jun 2018=>12425, Sat, 30 Jun 2018=>47, Fri, 29 Jun 2018=>7552, Sun, 01 Jul 2018=>21}
```
Fixes some of https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffca22b75b5bf00176c087e

Add a task to remove hidden maven projects with no group id.

---

app/models/concerns/project_search.rb
app/models/package_manager/clojars.rb
app/models/package_manager/maven.rb
lib/tasks/one_off.rake

* use `/` instead of `:`, because that's what [Clojars uses](https://github.com/clojars/clojars-web/wiki/Groups) and we also have a bunch of pre-2020 Clojars projects that already use `/`.
* a rake task to backfill any missing `/` packages, and delete all the `:` packages.
Depends on https://github.com/librariesio/maven-updater/pull/7
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6013958dfaa82200183bb68e?event_id=6019a6a200699dade9aa0000&i=em&m=fq

Use / to join Clojars package names instead of :.

---

app/models/package_manager/clojars.rb
app/models/package_manager/maven.rb
spec/models/package_manager/maven_spec.rb

Followup to https://github.com/librariesio/libraries.io/pull/2711
We use MavenUrl in a couple places, so we should just stick with that instead of subclassing it for Clojars.

One more fix for Clojars names.

---

app/models/package_manager/clojars.rb
app/models/project.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffca22b75b5bf00176c087e

Clojars urls require a version, so use web url for check_status.

---

app/models/package_manager/clojars.rb

Accidentally put the delimiter in the wrong method call:
https://app.bugsnag.com/tidelift/libraries-dot-io/errors/601d7ba5cab0000017044e74?aevent_id=601d7ba50069ac1bf8b30000&i=sk&m=nw

Fix accidental clojars argument.

---

app/controllers/api/repositories_controller.rb

Example with 122 repository deps:
Before:
```
Benchmark.ms { r.repository_dependencies.includes(:project).map { |d| DependencySerializer.new(d) }.as_json }
=> 996.7429660000562
```
After:
```
Benchmark.ms { r.repository_dependencies.includes(:project, :manifest).map { |d| DependencySerializer.new(d) }.as_json }
=> 634.9350350001259
```
There's another N+1 with versions/tags queries, but we can't fix it bc it requires Ruby logic :\

Include manifest in Api::Repositories#dependencies to fix N+1

---

app/controllers/application_controller.rb

It's easier to track down bottlenecks when you can drill into specific endpoints.

Trace endpoints for better instrumentation.

---

app/models/concerns/releases.rb

To be merged after this backfill is run: https://github.com/librariesio/libraries.io/pull/2721

Start using db-based latest_stable_release_number instead of Ruby version

---

Gemfile
Gemfile.lock
app/controllers/api/projects_controller.rb
app/models/project.rb
app/models/version.rb
app/serializers/project_serializer.rb
app/views/api/projects/dependencies.json.jb
spec/rails_helper.rb
spec/requests/api/bower_search_spec.rb
spec/requests/api/projects_spec.rb
spec/requests/api/subscriptions_spec.rb
spec/serializers/project_serializer_spec.rb

An attempt at speeding up `/api/projects/:platform/:name/:version/dependencies`:
* adds `jb` gem for simple JSON templates
* adds `v2=true` param that switches from ProjectSerializer to JB template in this endpoint
Sample project with 1820 versions, roughly before and after:
```
> Benchmark.ms { ProjectSerializer.new(p).as_json }
=> 277.5426210137084
> Benchmark.ms { p.versions.map { |v| v.slice(:number, :published_at, :spdx_expression, :original_license, :researched_at, :repository_sources) }.as_json }
=> 82.78486994095147
```

Add JB gem, and a first JB template for Api::Projects#dependencies.

---

app/controllers/application_controller.rb

Some endpoints are getting conflated in GCP Trace because the spans are leaving out the controller namespace. 
E.g. for `Api::ProjectsController#dependencies`:
`endpoint#projects#dependencies`
`endpoint#api/projects#dependencies`

Ensure that namespaces are included in controller name spans.

---

app/models/package_manager/wordpress.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/5ffc7d823a74ac00181b3361

Wordpress' "tags" is Hash if full, or an Array if empty.

---

config/initializers/google_cloud_trace.rb

Just realized that there's a `Google::Cloud.configure.use_trace` variable that gets set in the Railtie, and it determines if the middleware is added. Removing the monkeypatch will mean that some real Trace code will run inside `in_span`, but it should no-op anyway.

Tweak GCP intializer.

---

app/middleware/sidekiq/google_cloud_trace_middleware.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/602c1832d301e70017a4c8bd

Cloud Trace middleware fix.

---

app/middleware/sidekiq/google_cloud_trace_middleware.rb
app/models/package_manager/base.rb
config/initializers/sidekiq.rb

Just noticed that the stacktrace isn't very useful because it's the trace for the worker being run.
Also seems like knowing the job args would be useful, so including those in each trace too.

Disable stacktrace in sidekiq middleware, and include job args in span.

---

Gemfile

Rubocop loads about 20mb into memory, and we don't need it most of the time (especially in production).

Don't require rubocop by default.

---

app/workers/package_manager_download_worker.rb

Found some of these in the `PackageManagerDownloadWorker` logs:
```
2021-02-17T01:52:34.761Z 8 TID-gt7a9aigw WARN: URI::InvalidURIError: bad URI(is not URI?): "https://repo1.maven.org/maven2/io/service84/library/standardservice/ 1.2.0/standardservice- 1.2.0.pom"
```

Ensure we strip versions in PackageManagerDownloadWorker

---

app/models/package_manager/wordpress.rb
docs/add-a-package-manager.md
spec/models/package_manager/wordpress_spec.rb

Wordpress JSON urls offer a `versions` key that is sometimes populated. This hasn't been touched in 6 years and I'm not sure why `versions` wasn't fetched before, so the data might've gotten better since then.

Get all Wordpress versions if they're available.

---

app/models/package_manager/base.rb
app/models/package_manager/go.rb
app/models/package_manager/maven.rb
app/workers/package_manager_download_worker.rb

This combines the `PackageManager::Base.update` and `PackageManager::Base.update_version` methods because they're doing similar things, and `update_version` was wrapping `update` anyway.
This should also fix an issue with Maven where we fetched all the versions twice (i.e. if a package has 2000 versions, we'll make 4000 requests total). 😬

 PackageManagerDownloadWorker refactor: step 2

---

app/models/package_manager/base.rb
app/models/package_manager/maven.rb
spec/fixtures/tidelift-maven_metadata.xml
spec/models/package_manager/maven_spec.rb

TL;DR: this fetches the latest version for Maven packages from maven_metadata.xml, instead of fetching all the versions and picking the newest one.
We need to use `latest_version()` for `mapping()`, so we need the latest version AFAIK.
In the next step, we can make `versions()` optional, so we can get project data without making N requests for the versions.
Here's the original commit that started fetching the latest version to use as the project's POM: https://github.com/librariesio/libraries.io/commit/3b77f008b27cd05870b0bb534c1236e0a1213e9d#diff-ac475c62f3e3faba6f62b8831d6d8b85af275fdb812328fd9cfaec0179718e20R39

 PackageManagerDownloadWorker refactor: step 3

---

app/models/package_manager/base.rb

This has been noisier since we started using `save!` methods instead of `save` during package updates.
Should silence https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036fff1d519f90017f7229b

Quiet some PackageManagerDownloadWorker race condition noise.

---

app/models/package_manager/cran.rb

Projects like [this](https://cran.r-project.org/web/packages/acumos/index.html) are scraped from CRAN, including the URL, which can be pretty long. Seems specific to CRAN so why not just truncate long url fields (or we could make this column bigger too 🤷 )
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6035c1add3b47400174b50dc

Silence some PackageManagerDownloadWorker noise from long CRAN scraped urls.

---

app/models/package_manager/npm.rb
app/models/package_manager/packagist.rb

Followup to https://github.com/librariesio/libraries.io/commit/78cbb976d01c84f859bbc2501f8f02b3a7a52873
IMO better to return `nil` for a project's mapping that we don't care about rather than `nil` **or** `false` (and false seems more appropriate if this method was inquisitive).
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6033ea3c71af060018d90a6b

Return nil from mapping() instead of false or nil.

---

app/models/package_manager/cocoa_pods.rb

We're getting `{"versions" => {}}` for CocoaPods that don't exist, but we want just a blank `{}` so we can do an early-return because the project doesn't exist.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036a95d2447bb0018ea48f2

PackageManager::CocoaPods: don't set 'versions' on project if the project is missing.

---

app/models/package_manager/homebrew.rb

Another thing that switching to `save!` on package updates has surfaced: I think Homebrew updating might've been broken since [the API endpoint was updated](https://github.com/librariesio/libraries.io/commit/87874db767e1d69a8487d84dd81649596d7ce6c8)?
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036a95d2447bb0018ea48f2

Fix Homebrew project mapping.

---

app/controllers/sessions_controller.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
spec/requests/sessions_spec.rb

This ensures that Libraries does safe-redirects with its `return_to` parameter, by setting an environment-specific host and checking that before redirecting to the stored `return_to` url.

Safe redirects.

---

app/models/package_manager/base.rb

This line usually doesn't get called, which is why we didn't notice it was broken before.

Fix a logger method

---

app/models/package_manager/maven.rb
spec/models/package_manager/maven_spec.rb

Some libs in the Spring Artifactory instance (also some Maven libs) do not have POMs, even tho they have zips, pom.asc etc. For example:
https://repo.spring.io/webapp/#/artifacts/browse/tree/General/libs-release-local/org/springframework/cloud/spring-cloud-function-docs/3.1.2
This gracefully moves on during the update if it is missing.
https://app.clubhouse.io/tidelift/story/16019/pom-parsing-error-in-package-manager-download-worker

Handle missing POMs 

---

app/models/package_manager/base.rb
app/models/package_manager/maven.rb
spec/models/package_manager/maven_spec.rb

Followup to https://github.com/librariesio/libraries.io/pull/2779
When pulling specific versions and the POM is missing, skip the update on that version.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/606f904b075d7d00079ebe85?event_id=606f904b00770c3cbd710000&i=em&m=nw

Skip version updates if POM is not found.

---

app/models/package_manager/sublime.rb

Looks like the `Rust` package, for example, was being redirected to `Rust Enhanced`. This ignores those redirects instead of raising an error.
Things to look into later:
* fix the `project_names` endopint, which broke in v3 of the package manager, and now returns no names.
* add support for redirects, so we can mark a project as "Deleted" and add the new project name (or something)
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036c592aa2da800175dd916?event_id=60735c7d007759f45dc10000&i=em&m=fq

Sublime: don't follow redirects bc they lead to HTML of other projects.

---

app/workers/package_manager_download_worker.rb

Not positive where this failing `" optimist"` update is getting queued up from yet, but this should squash it.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036c59c5e2e0700174e0541?event_id=60767b1600770aa4e7f10000&i=em&m=fq

Ensure we strip package names in worker.

---

app/workers/package_manager_download_worker.rb

PlatformIO gives us ints back, which we use to lookup the projects when updating them.
Followup to https://github.com/librariesio/libraries.io/pull/2783
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/607799964ea05c00075280d9?event_id=6077999600777eaaf2850000&i=sk&m=nw

Cast project name arg to string before stripping.

---

app/models/package_manager/go.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/607f36c9ad85a200085f2828

Fix tiny url regression.

---

app/controllers/hooks_controller.rb
app/models/package_manager/platform_io.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036c59c5e2e0700174e0541?filters[event.since][0]=30d&filters[error.status][0]=open

PlatformIO: add some hook logging to debug, and fix project lookup.

---

app/models/package_manager/base.rb
app/models/package_manager/conda.rb
app/models/package_manager/go.rb
app/models/package_manager/maven/maven_central.rb
app/models/package_manager/npm.rb
spec/models/package_manager/go_spec.rb
spec/models/package_manager/maven_spec.rb

Also changes the signature of `one_version()` to avoid fetching the project again needlessly.
https://app.clubhouse.io/tidelift/story/16937/implement-single-version-package-manager-download-worker-updates-for-npm

NPM: enable single-version updates.

---

Gemfile
Gemfile.lock

Looks like we haven't bumped bibliothecary in a few months, so here's a diff:
https://github.com/librariesio/bibliothecary/compare/v6.9.7...v6.12.2

bibliothecary 6.9.7 ~> 6.12.2

---

app/models/concerns/project_search.rb

Some records are now throwing 500s in search because they exist in the db/ES but their PackageManager::Base platform was removed. Until we remove those records in a cleanup, this ignores those removed platforms in all project searches explicitly. This should also exclude those removed platforms from faceting too 👍🏻 
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60ae50aca940100007305441

Search: exclude platforms removed from code but still exist in db/ES.

---

app/models/concerns/project_search.rb

Forgot to add Jam to ignored Project search package managers.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/60ae50aca940100007305441

Ignore Jam in Project search too.

---

app/models/package_manager/base.rb

This is a duplicate error thrown on a version lookup failure. In https://github.com/librariesio/libraries.io/pull/2829 a custom error was introduced so that we can rely on sidekiq retries but not send to bugsnag. This also doesn't need to get sent to bugsnag, and we can rely on that worker exception.

Remove duplicate handling for failed version lookup

---

Gemfile
Gemfile.lock

I thought it would be helpful to have these libraries around to help with debugging in the dev/testing environments, as you would be able to step through/over/continue/etc. from the pry console when you hit a `binding.pry` in the code.

Add byebug and pry-byebug as dev/test dependencies

---

app/models/package_manager/maven.rb
spec/fixtures/proto-google-common-protos-0.1.9.pom
spec/models/package_manager/maven_spec.rb

This is a quick fix to resolve the missing license information for the org.jacoco:org.jacoco.* packages. I was able to get the EPL2 license information locally with this change. 
See https://app.clubhouse.io/tidelift/story/18585/license-missing-for-maven-org-jacoco-org-jacoco-packages#activity-18662 for more details.

Add epl2 url to LICENSE_STRINGS

---

app/controllers/healthcheck_controller.rb

Adding the current revision commit SHA to the healthcheck endpoint for better internal notifications/monitoring.

Add current commit sha to healthcheck endpoint

---

app/models/project.rb
spec/models/project_spec.rb

The license "Apache License, Version 2.0" is being incorrectly split on the comma. This results in two licenses: one correct, and one incorrect.  This change will strip the comma for this special case.
I added a new sanitize method, which can be used in case there are other special cases in the future.

add special case for Apache License, Version 2.0

---

app/models/package_manager/packagist.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/612eba4cd9053000070f37e0

Packagist repo sources: include "Main" here, since we're saving the repo source as this for now

---

app/models/package_manager/packagist.rb

We need this now that it's a multiple source package manager.
Fixes Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/612eae3d8904d30007653a10

Implement download_url() for Packagist 

---

app/models/package_manager/packagist.rb

I can try to fix this so it doesn't happen to others using MultipleSourcesBase in the future, tomorrow.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/612ebba8e857d90007e74dad

Packagist: ensure we set these two methods too

---

app/models/package_manager/packagist/drupal.rb

This one works with our license fuzzy matching, whereas the previous one broke and got interpreted into a totally diff license.

Use GPL-2.0+ for Drupal modules.

---

app/models/package_manager/base.rb

This should fix many of the `string contains null byte` errors that Libraries gets from package manager data.
https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6036b670266ec50019a37a09?event_id=6152fd6b00826e026c5d0000&i=em&m=fq

Clean out null bytes from any strings we get from package managers.

---

app/models/project.rb
app/workers/check_status_worker.rb
lib/tasks/projects.rake

This should help cases where a project is no longer deprecated, e.g. https://github.com/librariesio/libraries.io/issues/2865

When re-checking removed projects, also check deprecated.

---

app/controllers/project_usage_controller.rb
app/views/project_usage/show.html.erb

These are inefficient to load so let's just pop a message vs doing
very expensive queries that break the site

Don't show large project usage pages

---

app/models/package_manager/packagist/drupal.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/618bd78384a4da0008c55296

Drupal: modify regexp for repo url, and use safe navigation

---

app/controllers/api/projects_controller.rb
app/controllers/application_controller.rb
config/routes.rb
spec/requests/api/tree_spec.rb
spec/requests/tree_spec.rb

The two endpoints to get a dep tree use different params for version:
```
api_version_tree GET      /api/:platform/:name/:version/tree(.:format)              api/tree#show {:format=>:json, :platform=>/[\w\-]+/, :name=>/[^\/]+/, :version=>/[\w.\-]+/}
version_tree GET      /:platform/:name/:number/tree(.:format)                   tree#show {:number=>/[\w.\-%]+/, :name=>/[^\/]+/}
```
~~This adds the `params[:version]` to the tree-resolver-initialization logic so the first route can fetch the specific version instead of "latest stable" version.~~
This changes `params[:version]` to `params[:number]` to fix the API tree endpoint and make API routes consistent with Web routes.

Fix API tree endpoint by changin params[:version] to params[:number]

---

app/models/project.rb
spec/models/project_spec.rb

Libraries' deprecation logic may be imperfect sometimes and is evolving (or a package repo could allow undeprecation of a package), so if a package on a platform that allows package-deprecation was deprecated in the past and is no longer deprecated, then mark it as not deprecated.
Followup to https://github.com/librariesio/libraries.io/pull/2907

Undeprecate a previously-deprecated package if it is no longer deprecated.

---

app/models/package_manager/go.rb
lib/tasks/projects.rake
spec/models/package_manager/go_spec.rb

Use `pkg.go.dev` to verify if a package name is correct for Go and don't return partial info if the name is not found. This also fixes up an encoding issue when querying the proxy for version info.

Use pkg.go.dev For Go Package Names

---

app/models/package_manager/go.rb
app/workers/go_project_verification_worker.rb

When verifying a project name and ending up with a non Go module package downcase the name and use that as the canonical name for that package.

Update Go Project Verification To Deal With Non Module Names

---

lib/tasks/version_scheme_counter.rake
spec/tasks/version_scheme_counter_spec.rb

After running the rake task for a couple days, noticed the cursor was stuck at 999 instead of reflecting 25k records processed.
Also
- fix off-by-one calculation of the cursor
- remove redundant call to output file

Actually update cursor as version scheme detection task runs

---

app/models/package_manager/go.rb
spec/models/package_manager/go_spec.rb

This adds a 2-second timeout to `PackageManager::Go.project_find_names()`, which is currently timing out (60 sec?) on a module that has been moved (`vbom.ml/util` -> `github.com/fvbommel/util`).

Set a reasonable timeout when looking up canonical name of go module

---

lib/tasks/version_scheme_counter.rake

The task has made it through 56k of the project list but is stuck now because it keeps crashing on a weird version number which is causing an exception in the calver validator. 
Two possible version numbers which would cause this to happen is if a package contained a version of `""` or `"."`

Guard against unexpected version numbers in the calver test

---

Gemfile.lock

To avoid CVE-2022-24790 request smuggling vuln.
[Diff](https://github.com/puma/puma/compare/v5.3.2...v5.6.4)

puma 5.3.2 ~> 5.6.4

---

app/models/package_manager/packagist/drupal.rb

Drupal removed the "submitted on" date from their index of releases, so we have to fetch each release page separately to fetch the real published_at date.

Drupal: scrape each release page for published_at instead of releases index.

---

app/models/package_manager/packagist.rb
spec/models/package_manager/packagist_spec.rb

Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6296bb1dfa287a00093c83ea

Adapt Packagist's deprecation_info to new v2 api too.

---

app/models/package_manager/packagist.rb

The old logic of Packagist V1 API was to use the version with the highest "time" value to fetch the metadata. Now, in V2, that might not necessarily be the "highest" version, and only the "highest" version will have the metadata. This uses the first one returned, which (based on my sample of 20 projects) should always have the metadata.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/629694b6d12c280008c2f4e7

Packagist updates: use the first version returned to get metadata.

---

Gemfile.lock

Update to support M1 chips. 1.3.0 is the first 1.x version that supports M1 chip installs.
https://github.com/pganalyze/pg_query/issues/210

update pg_query to 1.3.0

---

app/models/package_manager/pypi.rb

Pypa is doing some refactoring to their routes and CDN so it looks like we'll need to use the no-slash route for JSON pypi urls (we don't follow redirects so we're using the wrong response in Project#check_status):
https://github.com/python/pypi-infra/pull/74#issuecomment-1149830495
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6279b21e084724000936ed63

Remove trailing slash to accomodate recent pypi route changes.

---

app/models/project.rb

I'm not positive if 404s on JSON endpoints for missing projects is a new response on Pypi, but we're getting them now, so we can just use them as a signal that the package is deleted. e.g. `astoptimizer` and `cocolangapi` are ones that we're currently blowing up on bc they 404.
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6279b21e084724000936ed63

Mark pypi packages as Removed when we get a 404.

---

app/models/package_manager/pypi.rb
spec/models/package_manager/pypi_spec.rb

Not very consequential, but PEP 503 says "All URLs which respond with an HTML5 page MUST end with a / and the repository SHOULD redirect the URLs without a / to add a / to the end.", so we can save them a redirect by publishing the project-with-version url with a trailing slash.

Always publish pypi project urls with a trailing slash.

---

app/models/package_manager/cpan.rb
app/models/package_manager/dub.rb
app/models/package_manager/npm.rb
app/models/package_manager/packagist.rb
app/models/package_manager/pub.rb

We need versions in mapped_project for some package managers for
dependencies to work. Bring it back for those specific ones.

self.dependencies requires versions in mapped_project for some package managers

---

app/controllers/admin/projects_controller.rb
app/views/admin/projects/show.html.erb

This removes the `repository_url` field from the Admin Project form for 2 reasons:
1) the value gets overridden by PackageManagerDownloadWorker anyway when the project gets rescraped after save
2) and we want libraries to be the canonical source of repo data, not curated data

Make repository_url non-editable in admin

---

app/controllers/platforms_controller.rb

ActiveRecord::RecordNotFounds seem to be rendered as uncaught errors/500s in production instead of 404. This results in false-positive 500 metrics. Going to try rescuing them explicitly and return 404s and if that works then possibly introduce some `rescue_from`.

Try to rescue RecordNotFound in one spot and explicitly return 404

---

config/initializers/sidekiq.rb
spec/support/sidekiq_testing_helpers.rb
spec/workers/repository_maintenance_stat_worker_spec.rb

Some specs are flaky because we don't clear Sidekiq between specs, and don't disable SidekiqUnique for specs.

Fix flaky sidekiq specs

---

app/models/package_manager/base.rb
app/models/version.rb

Saving a project can be expensive, because of the [set_dependents_count callback](https://github.com/librariesio/libraries.io/blob/90c862489207925e5f9b713d1cb340e806740241/app/models/project.rb#L317-L317). We can call this less often by not saving the project on every upsert of a version.

Perf: PackageManager update

---

app/controllers/application_controller.rb
app/views/tree/show.html.erb

If a date is present, [this code](https://github.com/librariesio/libraries.io/blob/02626e29606d48c8fe5e01471997ff9dcc833204/app/models/concerns/dependency_checks.rb#L35-L37) won't use the preloaded versions, instead it performs another sql query because we're adding a `.where()` clause to the preloaded versions. This happens many times over the course of building a tree.
`date` is frequently nil coming in from the API, so let's keep that nil value so we can leverage the included versions. For my sample package, this reduces the tree computation to 51 seconds, instead of crashing the pod with OOM in 2m14s. (I think we can do better, but this is a step in the right direction).

Perf: tree

---

app/controllers/api/search_controller.rb

We're falling over due to excessive requests to this so let's block that for the moment

Require an internal api key for the search endpoint

---

app/controllers/api/search_controller.rb
spec/requests/api/search_spec.rb

- the project search endpoint was previously able to be queried without an API key, which is likely too permissive
- marking it as internal-only seems too restrictive since this is a publicly documented endpoint
- this aims to find a middle ground, ensuring users can still reach the endpoint, while keeping away unregistered usage
Opening this in hopes of providing an option for legitimate usage of the project search endpoint. With bad keys blocked and anonymous keys throttled in #2975, I would think that would catch most API misuse, and rate limits (at the individual or default level) could then be adjusted as needed.

Require api key on search endpoint

---

config/initializers/rack-attack.rb
spec/requests/api/search_spec.rb

- missing or invalid API keys were being handled with Rack::Attack's
"throttle" method, which automatically returns "429 Too many requests"
- this adds a helper method to check the validity of the API key and use
a blocklist or throttle as needed
- recent work to stop API abuse throttles requests with invalid API keys to zero
- this is somewhat confusing, as someone who mistakenly enters their API key incorrectly will get a "too many requests" error message
- a "forbidden" response body would be more clear and semantically correct
- use [Rack::Attack's blocklist method](https://github.com/rack/rack-attack#blocklistname-block) for requests with invalid API keys, which [returns "forbidden" by default](https://github.com/rack/rack-attack#customizing-responses)
- add a memoized [request …

Respond with forbidden when invalid api key

---

app/workers/package_manager_download_worker.rb
config/initializers/bugsnag.rb
spec/workers/package_manager_download_worker_spec.rb

Currently, when we get a newly published version and sync a `PackageManagerDownloadWorker` job, we'll raise a `VersionUpdateFailure` (and ignore that error in bugsnag) if we can't find the version. This is most likely because the package repo has a stale cache, so we let the job try again and it is usually a long enough delay for the new version to exist on the repo.
There are some problems with this:
* since we know this is because of repo staleness, this doesn't really count as "exceptional" enough to raise an error
* this leads us to thousands of regular jobs in the "retries" queue normally, which conceals real errors.
* we're also logging the backtraces and passing around the backtraces for these thousands of errors, which is a lot of strings.
* regarding ☝🏻 , I've noticed the sidekiq …

Change VersionUpdateFailure behavior to be less exceptional.

---

config/initializers/bugsnag.rb

Followup to https://github.com/librariesio/libraries.io/pull/2997
Now that we're sending real VersionUpdateFailure exceptions to Bugsnag (instead of transient ones), the amount is much higher than expected. Since we have the error on hand now, silence them in Bugsnag until we can fix.

Temporarily silence VerisonUpdateFailure again

---

app/workers/package_manager_download_worker.rb
config/initializers/bugsnag.rb
spec/workers/package_manager_download_worker_spec.rb

Sometimes go modules can't be found on pkg.go.dev, e.g. https://pkg.go.dev/github.com/oraichain/wasmd . It could be because they're forks or some other reason, but the rules around pkg.go.dev indexing are elusive and changing. 
If we come across a go version update for this case, silently ignore them. If someone notices a missing package, they can manually click "Request package" on pkg.go.dev and it'll possibly fetch the package, and then we can index it on Libraries too.

Decrease VersionUpdateFailure attempts to 15 and skip them for go.

---

Gemfile.lock

`.../bugsnag-6.11.1/lib/bugsnag/cleaner.rb:65: warning: Using the last argument as keyword parameters is deprecated`
These were fixed in [bugsnag 6.13.0](https://github.com/bugsnag/bugsnag-ruby/blob/master/CHANGELOG.md#6130-30-jan-2020).

Update bugsnag to silence a deprecation warning fixed in 6.13.0

---

app/models/repository_host/bitbucket.rb
app/models/repository_owner/bitbucket.rb
app/views/admin/projects/index.html.erb

Use Addressable::URI.escape instead of URI.escape to silence warnings:
`...  warning: URI.unescape is obsolete`

Use Addressable::URI.escape instead of URI.escape

---

db/migrate/20220930184941_add_covering_index_on_repository.rb
db/schema.rb

The `Project#dependent_repositories` association can be an expensive query because it has a default group/order by, in which the sorted columns are not indexed. This adds an index on (rank, stargazers_count, id), which are all int columns. The query is:
Base query:
``` sql
SELECT "repositories".* 
FROM "repositories" 
INNER JOIN "repository_dependencies" ON "repositories"."id" = "repository_dependencies"."repository_id" 
WHERE "repository_dependencies"."project_id" = 1803769 
GROUP BY repositories.id 
ORDER BY repositories.rank DESC NULLS LAST, repositories.stargazers_count DESC
```
(alternatively, we could remove the `order` from this association)

Add covering index on repositories on (rank, stargazers_count, id)

---

app/models/repository_host/github.rb

A big chunk of time in `Repository#update_all_info` comes from its call to `RepositoryHost::Github#download_contributions`, which downloads all contributors and updates their contribution count. 
This fixes a type issue in the find-or-insert, which should save 3 queries per contributor that is already in the db: the "id" that comes back from GH is an integer, whereas RepositoryUser#uuid is a string.
Example for a repo that only has lookups and no updates:
> Benchmark.ms { Repository.find_by_full_name('golang/go').download_contributions(AuthToken.token)}
=> 2250.269000418484
> Benchmark.ms { Repository.find_by_full_name('golang/go').download_contributions(AuthToken.token)}
=> 4314.122000243515
(hopefully this reduces memory usage a ton too)

Fix type error in Github#download_contributions

---

app/workers/repository_maintenance_stat_worker.rb

This should avoid a deadlock case that we've happened to hit

Make repo maintainence workers unique by repo

---

Gemfile
Gemfile.lock
lib/tasks/one_off.rake
spec/rails_helper.rb
spec/tasks/one_off_spec.rb
spec/tasks/version_scheme_counter_spec.rb

There are currently 1,301,892 repository_maintenace_stats so I think it should be okay to run this query on that many records. Both queries were adapted from the queries [at this stackoverflow post](https://stackoverflow.com/questions/53722174/most-efficient-way-to-remove-duplicates-postgres).
The first query is from the OP and the second query is from the accepted answer. I like the first query better since it is really succinct and easy to understand and according to the accepted answer is faster, but the author of the question left a comment that said he didn't know why it was sometimes leaving duplicates 🤷 . I don't see anything wrong with the query and if anyone thinks our mileage might be different then I can remove sql2 and use the first sql. Otherwise I'll remove the first sql and …

Add rake task to remove repository_maintenance_stats duplicates to prepare for unique index creation

---

app/models/package_manager/maven.rb

The `/all` endpoint on the maven-updater was [removed last year](https://github.com/librariesio/maven-updater/commit/59c3a8cc76fb83acd94eb20e7b63dcedd543c206), so this updates the Maven `project_names` to just use the `/recent` endpoint, which is better than nothin.

Maven /all endpoint no longer exists, just use /recent

---

app/models/package_manager/base.rb
app/models/version.rb

* move logging callback before the 'save_project' callback, which is skipped when saving project
* explicitly log the version after it's created in PackageManager::Base

Two attempts at fixing the "[NEW VERSION]" logging

---

Gemfile.lock
app/models/package_manager/maven.rb
spec/fixtures/proto-google-common-protos-0.1.9.pom
spec/models/package_manager/maven_spec.rb

Fixes `maven/com.indeed:proctor-tomcat-deps` on Libraries, which currently has a repository_url of `${project.parent.scm.url}`
If a parent pom has a `<scm><url /></scm>` value outside of the `<properties>`, this will add "scm.url" to the parent properties so we pass it on to Bibliothecary for interpolatuion.
(background: pom parent interpolation was added in https://github.com/librariesio/libraries.io/pull/2380)

Maven: set "scm.url" in parent props manually, in case they're outside parent properties

---

app/models/package_manager/base.rb
app/models/package_manager/pypi.rb
spec/fixtures/vcr_cassettes/pypi_dependencies_requests.yml
spec/models/package_manager/pypi_spec.rb

This is fixing Pypi dependencies after this update: https://github.com/pypi/warehouse/pull/11775 which broke the existing implementation.

Update Pypi.dependencies after update to package manager api

---

app/controllers/application_controller.rb
config/environments/production.rb

* don't log `params[:api_key]` (it's redacted currently anyway)
* build our own custom "api_key" object for Logstash for filtering request logs, etc

Don't log api_key param, but include custom api_key object if it exists.

---

Gemfile.lock

Updates bibliothecary for [this change](https://github.com/librariesio/bibliothecary/pull/568/), which improves pyproject.toml parsing.

bibliothecary 8.5.1 ~> 8.6.0

---

app/models/project.rb
app/serializers/optimized_project_serializer.rb
app/serializers/project_serializer.rb
db/schema.rb
spec/rails_helper.rb
spec/requests/api/projects_spec.rb
spec/requests/api/subscriptions_spec.rb
spec/serializers/project_serializer_spec.rb

[Story Link](https://app.shortcut.com/tidelift/story/30079/archived-github-repos-should-trigger-appears-unmaintained-standard)
This adds a `repository_status` field to `Project` in order for `dependencyci` to be able to use it. 
Please note that I haven't run the project locally with these changes because of headaches with getting elasticsearch 2.4.5 working on an M1 Mac. If it is important that I do this then let me know and we can try to figure something out.

Add repository_status to projects

---

app/models/project.rb
app/serializers/optimized_project_serializer.rb
app/serializers/project_serializer.rb
spec/rails_helper.rb
spec/requests/api/projects_spec.rb
spec/requests/api/subscriptions_spec.rb
spec/serializers/project_serializer_spec.rb

Reverts librariesio/libraries.io#3054
This *un*-reverts librariesio/libraries.io#3052 which we reverted because we thought it was related to a live bug, but proved otherwise.
Please see the above un-reverted PR for approvals on exactly the same code.

Revert "Revert "Add repository_status to projects""

---

app/models/package_manager/base.rb
app/models/package_manager/go.rb
app/models/project.rb
app/workers/package_manager_download_worker.rb
spec/models/package_manager/pypi_spec.rb
spec/models/project_spec.rb
spec/workers/package_manager_download_worker_spec.rb

This passes a flag to the package download worker and then platform update methods to completely resync the dependencies. This isn't anything fancy. It will remove any existing dependencies and replace them with the ones from the platform provider's response in the `save_dependencies` function. This should allow us to clear out any Projects with incorrectly formatted dependency information on a case-by-case basis.

Resync Version Dependencies on Manual Sync

---

app/models/maintenance_stats/queries/github/repository_contributor_stats_query.rb

This method had a broken adhoc retry mechanism for a Github REST API call. Octokit can already perform retries on this call if passed a timeout value. With the default 0.5 second wait, 10 seconds allowed enough attempts to pass with the existing VCR cassettes.

Fix error handling while pulling github contributor stats

---

app/models/package_manager/base.rb
app/models/package_manager/maven.rb
app/models/package_manager/maven/atlassian.rb
app/models/package_manager/maven/hortonworks.rb
app/models/package_manager/maven/jboss.rb
app/models/package_manager/maven/jboss_ea.rb
app/models/package_manager/maven/spring_libs.rb
app/workers/package_manager_download_worker.rb
spec/workers/package_manager_download_worker_spec.rb

[Shortcut](https://app.shortcut.com/tidelift/story/31152/maven-projects-from-removed-repositories-causing-errors)
This restores these removed classes from maven's provider map while still omitting them from being automatically synced

Fix errors on projects from certain maven repositories

---

app/models/package_manager/maven/google.rb

Random disconnection errors were killing the whole Rake job. This should prevent that from happening.

Add retries for connection issues

---

app/models/package_manager/base.rb

Reverting this line, which ended up creating redundant "[NEW VERSION]" log lines.

Remove extra new verison logging that was creating dupe logs

---

app/models/package_manager/base.rb
app/models/package_manager/pypi.rb
spec/models/package_manager/base_spec.rb
spec/models/package_manager/pypi_spec.rb

```
$ curl https://pypi.org/pypi/CairoSVG/json 2>/dev/null | jq '.info.project_urls'
{
"Code": "https://github.com/Kozea/CairoSVG/",
"Documentation": "https://cairosvg.org/documentation/",
"Donation": "https://opencollective.com/courtbouillon",
"Homepage": "https://courtbouillon.org/cairosvg",
"Issue tracker": "https://github.com/Kozea/CairoSVG/issues"
}
```

Add project_urls.Code as a possible PyPI repository URL

---

app/models/maintenance_stats/stats/github/release_stats.rb
app/models/repository_host/bitbucket.rb
app/models/repository_host/github.rb
spec/models/repository_spec.rb

A Repository can be related to multiple Projects. Right now, if **any** those Projects have an erroneous or missing `repository_url`|`homepage` set, then the Project doesn't have a github|bitbucket_owner_name set, and we don't gather stats on that repository and trash existing ones. Given not the name or anything from Projects are actually needed or used when gathering repository stats, I've replaced that check. 
If there's a reason at the Project level we'd want this integrity check or to skip/reset gathering stats can find a better place to do it.

Don't let a bad Project spoil its Repository's stats

---

app/models/maintenance_stats/queries/github/repository_contributor_stats_query.rb
spec/models/package_manager/rubygems_spec.rb

* Octokit::Error expects to be initialized with response hash

Fixes for gathering github maintenance stats

---

config/environments/production.rb

Not very consequential, just useful to have for grouping, searching, e.g.:
```
[2c7ffd7c-cb44-4bba-87d4-f5f1e7eac364] [dd.env=development dd.service=libraries dd.version=0cf971e2cc63994ef271c39b8e6d5c9061c70932 dd.trace_id=2696306947296716588 dd.span_id=2672779687593121511] {"method":"GET",...}
```

Add "request_id" to Libraries' log_tags

---

app/controllers/application_controller.rb
app/controllers/hooks_controller.rb
config/environments/production.rb

Start tracking the "X-Github-Event" header from github hooks in our logs, when they exist, so we can correlate logs to GH events.

Track "github_event" in logs from the GH hook header.

---

app/controllers/api/projects_controller.rb
app/views/api/docs/index.html.erb
docs/development-setup.md
spec/requests/api/projects_spec.rb

The current method of getting names of packages that are dependent packages is not only too slow, but can result in causing Libraries to time out due to JSON rendering. This enables retrieving just the names of the current set of dependent packages for a single package, rendering only a minimal amount of JSON to do so.

Add returning names only for project dependents

---

lib/tasks/projects.rake

Referencing this list of removed platforms: https://github.com/librariesio/libraries.io/blob/main/app/models/concerns/project_search.rb#L3-L7

Clean out some removed platforms from the rake tasks

---

app/models/package_manager/base.rb
app/models/package_manager/cargo.rb
app/models/package_manager/npm.rb
app/models/package_manager/nu_get.rb
app/models/package_manager/packagist.rb
app/models/package_manager/pypi.rb
app/models/project.rb
spec/models/package_manager/npm_spec.rb
spec/models/package_manager/packagist_spec.rb
spec/models/package_manager/pypi_spec.rb

`deprecation_info()` was occasionally failing for Cargo since 2021, which means we haven't been updating Cargo project statuses recently. This fixes that, which requires changing the arg for `deprecation_info(name)` to use `db_project` instead.
```
NoMethodErrorCheckStatusWorker@status
undefined method `name' for "tokio-io":String
```

Fix deprecation_info() for cargo, by changing its method signature

---

app/models/package_manager/nu_get.rb

```undefined method `dig' for nil:NilClass```
Example: https://libraries.io/nuget/FAMILY-ISLAND-HACK-2022-ir

Silence deprecation_info() error for missing nuget packages

---

app/services/github_hook_handler.rb
app/workers/github_hook_worker.rb
spec/workers/github_hook_worker_spec.rb

Occasionally we receive GH hook events like "push" where the "sender" field is missing, e.g. for PR merges it seems. The docs [say](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#push) that "sender" is optional for these events, and we don't update the Repository unless we find the "sender"'s GH token anyway, so we can ignore these. 
Fixes https://app.bugsnag.com/tidelift/libraries-dot-io/errors/63e7fef4e6b45a000baf7d20

Ignore GitHub hooks where the "sender" field is nil

---

app/models/package_manager/go.rb
config/environments/production.rb

This disables the ActionDispatch::DebugExceptions middleware in Rails, which prints out stacktraces whenever we encounter exceptions, e.g. ActiveRecord::RecordNotFound. Libraries uses lograge/JSON for log output, so these backtraces aren't in the right format anyway.
This should remove about ~10 extraneous log lines, in the case of ActiveRecord::RecordNotFound.

Silence exception backtraces in production.

---

app/controllers/application_controller.rb

This was added about 3 years ago in https://github.com/librariesio/libraries.io/pull/2632, but I don't think we've done much with it, and we can probably inspect this via DD now. It takes up about 150k lines per day.
Alternatively, I could just add this information to the request logs too, to take up less log room.

Remove the "active connection" log

---

app/controllers/application_controller.rb
config/environments/production.rb

* adds libraries' IP to the trusted proxy list, so that `remote_ip()` filters it out from`X-Forwarded-For`
* also log `ip()`, to make sure it's correct (since that's the same value that rack-attack is using)

Add IP to trusted_proxies so we get the real IP in logs

---

app/controllers/api/projects_controller.rb
app/controllers/projects_controller.rb
app/views/projects/_statistics.html.erb
app/views/projects/dependents.html.erb
app/views/projects/top_dependent_projects.html.erb
spec/requests/api/projects_spec.rb

Gathering dependents details about a package is currently way too slow to be used practically. How we gather and present this data will need to be rethought in order to do it efficiently.

Disable dependents view & API access

---

app/controllers/application_controller.rb
config/initializers/rack-attack.rb
lib/subscribers/rack-attack.rb

Instead of adding our proxy to Rack's ip_filter to fix `request.ip`, we can just use ActionDispatch's algorithm via the `remote_ip()` method.

Rack::Attack: use ActionDispatch's remote_ip instead of Rack's ip

---

config/database.yml

Query timeouts would now surface as this error: 
```
> ActiveRecord::Base.connection.exec_query("select 1 from pg_sleep(50000);")
ActiveRecord::QueryCanceled: PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
: select 1 from pg_sleep(50000); /*application:Libraries*/
```

Add 30 second statement timeout to db

---

app/models/project.rb
config/initializers/active_record.rb
spec/ext/active_record_spec.rb

* cleanup the `with_statement_timeout` code a bit, and pass the connection as an arg to the block
* adds `get_statement_timeout` to make verifying timeout easier
* adds a spec to confirm that `with_statement_timeout` doesn't affect other connections' timeouts
* extend the timeout of a query that seems occasionally problematic

Some improvements to with_statement_timeout

---

app/models/project.rb
lib/tasks/projects.rake
spec/models/project_spec.rb

[Story](https://app.shortcut.com/tidelift/story/32776/fix-libraries-io-retrieval-of-project-status)
[Related PR for infra](https://github.com/tidelift/infra/pull/385)
This PR fixes `Project#check_status` and the `projects:check_status` rake task (which is being used in a new cron job in the related infra PR). We already regularly check removed projects to see if they've been reintroduced [here](https://github.com/tidelift/infra/blob/main/libraries-kube/cronjobs/libraries-projects-check-removed-status.yaml). This change is to do the opposite and check whether projects that exist have been removed.

Fix retrieval of project status

---

app/models/package_manager/npm.rb
spec/models/package_manager/npm_spec.rb

Missed this case before, but npm packages may in fact have 0 versions. 
[Related bugsnag](https://app.bugsnag.com/tidelift/libraries-dot-io/errors/6449ef47ba806a00087c3d74?event_id=6449ef4700bbaa8be9b90000&i=sk&m=nw)

Fix npm deprecation detection when there's no published versions

---

app/models/package_manager/npm.rb

In addition to being included but empty, the `versions` data may just not be present at all
[Bugsnag](https://app.bugsnag.com/tidelift/libraries-dot-io/errors/643606b6c120cb000af4e770)

NPM deprecation fixes part deux

---

db/migrate/20230502182027_add_index_to_projects_updated_at.rb
db/schema.rb
lib/tasks/projects.rake

- Adds back the missing project.updated_at index
- Updates the project:check_status to take in processing configs so we can process packages in smaller chunks
- Prioritize the projects that haven't been touched in the longest time first for getting refreshed

chore: Update project:check_status to take in processing configurations

---

app/models/project.rb
app/models/repository.rb
app/workers/check_repo_status_worker.rb
app/workers/check_status_worker.rb
spec/fixtures/vcr_cassettes/project/check_status/rails.yml
spec/models/project_spec.rb
spec/workers/check_repo_status_worker_spec.rb
spec/workers/check_status_worker_spec.rb

This removes the `deprecated_or_removed` parameter from `Project#check_status` (and associated methods) in an effort to simplify this method and ensure data is being updated properly.
Packages can still have the status set to `nil` if we find a correction to the data, but will no longer have a way to manually pass a flag to force a status reset.
Updating the specs after this change was triggering a new HTTP request, so I added a new VCR cassette to cover this.

chore: [sc-33382] Remove the deprecated_or_removed param from Project

---

app/models/project.rb
app/workers/check_status_worker.rb
lib/tasks/projects.rake

What I believe is the appropriate fix for the patch introduced [here](https://github.com/librariesio/libraries.io/commit/3593fd23d715dd80fe80be656be5d469fe3612c7).
~Removed ignored parameter from method signature~, and removes it from other calls of this method. I did not see any other calls that were being made incorrectly in searching through the code.

Remove ignored deprecated_or_removed parameter from CheckStatusWorker.perform

---

app/models/concerns/repo_manifests.rb
spec/models/repository_spec.rb

Fixes a noisy bug where a parsed manifest has an error and `dependencies` is nil instead of an array.
```
undefined method `map' for nil:NilClass
app/models/concerns/repo_manifests.rb:55:in `sync_manifest': undefined method `map' for nil:NilClass (NoMethodError)
from app/models/concerns/repo_manifests.rb:13:in `block in download_manifests'
from app/models/concerns/repo_manifests.rb:13:in `each'
from app/models/concerns/repo_manifests.rb:13:in `download_manifests'
from app/models/repository.rb:291:in `update_all_info'
```

Repository#sync_manifests: ignore manifests that had errors while parsing, and log a message.

---

Gemfile
Gemfile.lock

Updates Bibliothecary to 8.6.2 to incorporate [this change](https://github.com/librariesio/bibliothecary/pull/572).

Update Bibliothecary to 8.6.2

---

app/models/package_manager/pypi.rb
spec/fixtures/vcr_cassettes/pypi_dependencies_isort.yml
spec/models/package_manager/pypi_spec.rb

Once this is merged, I can put together a backfill for Pypi dependencies with `extra`s. The breadth of the dependencies table is so large that the backfill will consist of a rake task which I will baby-sit which will perform
```
PackageManagerDownloadWorker.perform_async("Pypi", <package_name>, nil, "parse-pypi-extras-backfill", 0, true)
```
on the affected dependencies in `created_at` order, in batches (the last `true` argument forces the resync of the dependencies). It will output the `created_at` of the latest batch processed so that it can be resumed from there if need be.
The query to get the affected dependencies will look like:
```
Dependency
.where(project_id: <batch of Pypi project ids>)
.where("dependencies.requirements LIKE '%==%'")
```

Consider Python dependency environment markers as the "kind" (scope) of the dependency

---

app/models/package_manager/maven.rb
app/serializers/dependency_serializer.rb
spec/requests/api/projects_spec.rb
spec/serializers/dependency_serializer_spec.rb

Uses the new `optional` field (added [here](https://github.com/librariesio/bibliothecary/pull/572) and [here](https://github.com/librariesio/libraries.io/pull/3121)) to add this to the `Dependency.optional` for Maven records.
Adds the `Dependency.optional` field to `DependencySerializer` so it is present in API responses.

Add optional field to dependencies for maven, add optional to DependencySerializer

---

app/models/package_manager/pypi.rb
lib/tasks/one_off.rake
spec/fixtures/vcr_cassettes/pypi_dependencies_isort.yml
spec/models/package_manager/pypi_spec.rb

~~This task is meant to batch approx 500k affected versions into 4 updates per second (4 Pypi api-calls per second) over the course of 1.75 days~~
This task would still take 1.75 days, but only because the main query which scans dependencies needs to be done in batches to avoid timing out. The actual number of affected versions is way less than I originally thought. I thought 1/10 versions needed to be updated but it's actually more like 1/1000. So the actual number of Pypi api-calls won't be very much, ~5k spaced over 1.75 days.

Backfill "kind" of Pypi dependencies

---

app/controllers/api/repositories_controller.rb
app/models/repository_maintenance_stat.rb
app/serializers/optimized_project_serializer.rb
spec/requests/api/repositories_spec.rb

We have the stats being returned when querying for a package, but the stats are tied to the repository directly so this allows us to query for stats per repository instead of per package with a possibly incorrect repository URL.

Include Maintenance Stats in Repository Detail API

---

app/models/package_manager/pypi.rb
spec/models/package_manager/pypi_spec.rb

https://peps.python.org/pep-0440/#implicit-pre-release-number
In Libraries, this should only affect fetching deprecation info, but trying to keep this consistent across services

[fix] Allow for implicit tailing zero in pypi prerelease/development versions

---

app/models/package_manager/go.rb

The Go proxy site will error out if the version string is not encoded correctly which results in data not being saved correctly in Libraries.

Encode the Version String When Querying Go Proxy

---

app/models/concerns/dependency_checks.rb
app/models/package_manager/pypi.rb
spec/models/package_manager/pypi_spec.rb
spec/models/tree_resolver_spec.rb

Dependency version requirements being returned from the PyPI API often have parentheses surrounding them which breaks the tree resolver when trying to find the latest version that fulfills each requirement. This PR would strip the parentheses from the requirements text before saving the dependency rows. We can run a backfill to fix old data or leave the fix in `dependency_checks.rb` to remove them when calling `semantic_requirements` on a `Dependency`.

Remove Parentheses from PyPI API Dependency Requirements When Parsing Results

---

app/models/project.rb
lib/tasks/projects.rake
spec/factories.rb
spec/models/project_spec.rb

We do a lot of querying by platform, especially in these rake tasks. Given the mixed case format for platform names in use, I wanted to make it harder to do the wrong thing. This updates the `Project::platform` scope to accept a string or array of strings, so it can easily replace much of the manual `where(platform: "YoudBetterGetTheseCapsRight")` calls.

fix: Reduce some mismatched casing bugs on platform names

---

app/models/package_manager/base.rb

This `spdx_expression` key is never set by any PackageManager, and its continued inclusion in the code could cause confusion as to where the SPDX license for a version is being set.

Remove unneeded key from version hash assignment

---

app/models/dependency.rb
app/models/repository_dependency.rb
db/migrate/20230705195409_add_created_at_index_to_dependencies.rb
db/schema.rb
lib/tasks/projects.rake

This PR is to help out the [Projects Dependencies Link](https://github.com/librariesio/libraries.io/blob/d68a5ffb6f032d1ab9f91c3c7bf35ce45a32d973/lib/tasks/projects.rake#L17-L22) daily job which has been failing to complete for a while now. The main reason this job fails is that it is impossible to query the `dependencies` table because of its large size and it is querying an unindexed column. The PR adds an index for `created_at` and scopes the values down to remove the time portion and index it as a Date so that values are grouped up a bit in the index and updates the jobs to query by Date and instead of DateTime.
This migration is something that should be run manually outside of our normal deployment since it will take some time for the database to add the indexes.

Add Indexes to dependency and repository_dependency on created_at date

---

lib/tasks/projects.rake

Updating the list of package managers we check the statuses of. Confirmed on a console that they all have a url string coming out of `check_status_url`.

Update the list of package managers to check the status of

---

app/models/project.rb
app/models/web_hook.rb
app/serializers/project_updated_serializer.rb
app/workers/project_updated_worker.rb
db/migrate/20230712143940_add_project_updated_to_web_hook.rb
db/schema.rb
spec/factories.rb
spec/models/web_hook_spec.rb
spec/workers/project_updated_worker_spec.rb

Note that we bump updated_at when any Version of the project
is added, as well.
There's no UX for this, the hook in question has to be manually added by admins.

Project: send a webhook event when projects are updated

---

lib/tasks/projects.rake

This adds some additional logging between batches, and removes a long `sleep` from the iterations, because this task was taking very long to run.

Clean up projects#sync_by_platform rake task

---

app/models/concerns/repo_manifests.rb
app/models/project.rb
lib/tasks/projects.rake

`Dependency` has a validation that a `project_name` should exist so the scope should be a no-op for that table. `RepositoryDependency` doesn't have that validation, but the lookup for project ID should return a `nil` if a project can't be found. This also updates how project IDs are mapped for repository dependencies so that they also use `Project.find_best` when looking for the correct `project_id`.
This PR should hopefully help `projects::link_dependencies` to finish more consistently and bring `RepositoryDependency` Project ID resolution in line with the `Dependency` table.

Remove the with_project_name scope from Daily Dependency Rake Task

---

lib/tasks/projects.rake

The query without using the batching SQL query parameters, namely `order by id asc where id > ? limit 1000`, seems to run pretty quickly and should avoid timing out. This change may result in the container hitting some memory issues, but that seems more manageable than trying to speed up the queries on these tables some more.

Query for all Dependency IDs Instead of Using Batching SQL Queries

---

lib/subscribers/rack-attack.rb

`[RACK_ATTACK] method=GET path=/api/versions?api_key=REDACTED match_type=throttle match=api match_discriminator=1234abcd request_id=65f59ad676836fa373b7 remote_ip=127.0.0.1 api_key_id=1234`

Add api key id to rack attack logs, if it exists.

---

app/models/package_manager/base.rb
app/models/package_manager/pypi/json_api_project.rb
app/models/package_manager/pypi/json_api_project_release.rb
app/models/package_manager/pypi/version_processor.rb
spec/factories.rb
spec/models/package_manager/pypi/version_processor_spec.rb
spec/models/package_manager/pypi_spec.rb

The Pypi api returns a yanked status at the package release level. This PR extracts that data and stores it in the database for each Pypi package version.
One assumption this PR makes is that if there are multiple distributions of a package release (e.g. `package-1.0.0.tar.gz`, `package-1.0.0.whl`), if one of the package releases is yanked then all of the package releases are yanked. 
There are also a couple of rubocop autocorrect fixes in the PR.

Enable pypi package versions to be individually marked as removed

---

Rakefile
app/models/concerns/github_identity.rb
app/models/repository_host/bitbucket.rb
app/models/repository_host/gitlab.rb
app/models/repository_owner/bitbucket.rb
app/models/repository_owner/gitlab.rb
app/views/layouts/application.html.erb
config/application.rb
config/initializers/bugsnag.rb
config/initializers/omniauth.rb

Having these in one place (application.rb) makes them easier to see at-once, and would make it easier to transition to [Rails' stored credentials](https://guides.rubyonrails.org/security.html#custom-credentials) if we ever do that (e.g. we'd just replace `Rails.configuration.foo` with `Rails.application.credentials.foo`)

Centralize env-based external key config in application.rb

---

app/models/package_manager/pypi/json_api_project.rb
spec/models/package_manager/pypi_spec.rb

Libraries will display a "Homepage" link for each package where we have such data available.
Libraries example: https://libraries.io/pypi/PyICU
Pypi source: https://pypi.org/project/PyICU/ (note the "Homepage" link under "Project links")
In the JSON API response we look for `home_page` or  `project_urls` => `Homepage` to populate this field in Libraries.
However, Pypi is not consistent with this field, and different projects will refer to this field in different ways. I've also observed:
- `project_urls` => `Home`
- `project_urls` => `homepage`
- `project_urls` => `HomePage`
Examples from Pypi where we are missing homepage data on Libraries:
- https://pypi.org/project/jupyter-server-fileid/
- https://pypi.org/project/nlbq/
- https://pypi.org/project/objverify/
- …

Update Libraries Pypi parser to handle different "homepage" variations

---

app/models/package_manager/pypi/json_api_project.rb
spec/models/package_manager/pypi_spec.rb

This slightly reworks the changes introduced in #3174.
The previous PR does updates the `homepage_url` value used, but that is not ultimately used to set the `Project#homepage` value: https://github.com/librariesio/libraries.io/blob/456440d4ece34fdc96965ddaa36da2b9fcdaa36e/app/models/package_manager/pypi/json_api_project.rb#L106
The `homepage_url` value is only passed into the [`repo_fallback` method](https://github.com/librariesio/libraries.io/blob/main/app/models/package_manager/repository_service.rb#L14-L20), which is used to set the `repository_url`.
I don't see a need to distinguish between the `homepage` and `homepage_url` methods, so this consolidates them.

Update Libraries Pypi parser to handle different "homepage" variations rework

---

app/models/readme.rb
app/models/repository_host/github.rb

Story details: https://app.shortcut.com/tidelift/story/36694

fix: [sc-36694] [libraries] Fix encoding error when scraping README contents

---

app/models/repository_host/bitbucket.rb
app/models/repository_host/github.rb
app/models/repository_host/gitlab.rb

This may be an old issue or one that cropped up after Rails upgrades. But it looks like we're getting cases where the readme record associated to a repository exists in the database, but hasn't been loaded by ActiveRecord (or was inserted by another thread?), and the existing basic nil check doesn't work. Unless there's a bigger problem this should cut down on these [snags](https://app.bugsnag.com/tidelift/libraries-dot-io/errors/631906c923d8450008a59c5e).

fix: README scraping: duplicate key error

---

config/application.rb
config/initializers/new_framework_defaults.rb

Ahead of rolling out Rails 7, I want to get the defaults to a closer version. 
AFAICT, the only default that is still relevant is `active_record.belongs_to_required_by_default = false`. Given it is still supported as an option, we don't need to prioritize unwinding all that. The others pertain to libraries we're not using or should be safe to enable once we're stable on 6.1, which we seem to be.

chore: Roll out bumping Rails' defaults to current production version

---

Gemfile.lock
config/initializers/bugsnag.rb

Autoloading this PackageManagerDownloadWorker::VersionUpdateFailure is causing a build issue, but the good news is, we don't have to.
https://github.com/bugsnag/bugsnag-ruby/blob/master/CHANGELOG.md?plain=1#L258/bugsnag/bugsnag-ruby/blob/bdfbf3972f2137b3b9b95194a6bedf9c8edf6555/CHANGELOG.md?plain=1#L258

Update bugsnag config to not need to autoload constants, fix build issue

---

lib/tasks/one_off.rake
spec/tasks/one_off_spec.rb

This one-off task is no longer needed.

Remove unused rake task

---

app/controllers/search_controller.rb
app/helpers/application_helper.rb
app/views/search/index.html.erb
spec/requests/search_spec.rb

This prevents expensive elasticsearch queries that have been the target of scraping efforts.

SearchController#index: short-circuit when no search term is provided

---

app/controllers/search_controller.rb
app/helpers/application_helper.rb
app/views/search/index.html.erb
spec/requests/search_spec.rb

Revisit https://github.com/librariesio/libraries.io/pull/3209
This prevents expensive elasticsearch queries that have been the target of scraping efforts. However, this time we only deny a search if no criteria at all is present. e.g. a search without a query is allowed if it has a license filter on it. But a search with only a sort is not allowed.

SearchController#index: short-circuit when no search criteria are provided

---

app/models/concerns/status.rb
app/models/package_manager/nu_get.rb
app/workers/nuget_project_verification_worker.rb
lib/tasks/projects.rake
spec/custom_matchers.rb
spec/factories.rb
spec/models/package_manager/nu_get_spec.rb
spec/workers/nuget_project_verification_worker_spec.rb

Story details: https://app.shortcut.com/tidelift/story/31318
This uses marking hidden as a soft-delete, but AFAICT there's nothing in `check_status` or `CheckStatusWorker` from resetting hidden projects. I'm considering that an issue for another day. The idea here is to gather data & do a safe sweep. 
Once we're satisfied, we can follow up with a hard-delete or other 'permanent' state.

feat: [sc-31318] [libraries] Backfill NuGet packages in libraries

---

app/models/package_manager/pypi/json_api_project.rb
app/models/package_manager/pypi/json_api_project_release.rb
spec/models/package_manager/pypi/json_api_project_release_spec.rb
spec/models/package_manager/pypi/json_api_project_spec.rb

This should help with PyPI packages being incorrectly marked as deprecated when:
* the latest stable becomes deprecated
* a newer, lower version becomes the most recently published
This ensures that the most recent release chronologically is the one used for deprecation determination.

fix: [sc-37352] Packages are incorrectly being marked as deprecated

---

app/workers/repository_maintenance_stat_worker.rb
spec/workers/repository_maintenance_stat_worker_spec.rb

There is something going on with AuthTokens when we try to find one to use for GraphQL calls to GitHub. Right now our workers can't find one to use so they spin for a very long time trying to find one which clogs up all the queues. This PR should no-op the worker and allow the other work to go through while we figure out what is happening.

Temporarily Disable Maintenance Stat Worker

---

app/models/package_manager/maven.rb
app/models/package_manager/maven/maven_url.rb
spec/models/package_manager/maven/maven_url_spec.rb
spec/models/package_manager/maven_spec.rb

Subclasses should be placed into separate files, not inlined into other
files. Some small code cleanups in MavenUrl as well.

feat: [sc-34666] Move MavenUrl to separate file

---

app/workers/nuget_project_verification_worker.rb
config/initializers/bugsnag.rb
config/initializers/sidekiq.rb
spec/workers/nuget_project_verification_worker_spec.rb

Adds a custom error class we can raise to use Sidekiq's built-in retry mechanisms without flooding error monitoring.

Allow sidekiq jobs to quietly raise and retry

---

lib/tasks/projects.rake

Story details: https://app.shortcut.com/tidelift/story/31318
Fix spacing out the batches, and slow the rate some more to be safe & considerate.

feat: [sc-31318] NuGet project verification worker: fix queueing adjust and rate of work

---

lib/tasks/auth_tokens.rake

Story details: https://app.shortcut.com/tidelift/story/37574
First part of cleaning AuthTokens up. Toss out the expired ones so we can get to the good ones.
I wrote this as a one-off, but it's probably worth scheduling too, monthly maybe.

fix: [sc-37574] Add task to scan and clean out expired authtokens

---

app/models/auth_token.rb
spec/models/auth_token_spec.rb

Octokit hides the [full details](https://docs.github.com/en/rest/rate-limit/rate-limit?apiVersion=2022-11-28) we can get from this endpoint, but we can inspect the full response and check a token's rate limit for both REST and GraphQL from the same request.
This means we don't have to involve both APIs just for checking if a token can be used, and cut down some code paths.

Fetch graphql rate limits from same request as rest limits

---

lib/tasks/one_off.rake
spec/tasks/one_off_spec.rb

In the original rake task, the `project.manual_sync` was an asynchronous process, meaning that it could be potentially unsafe to delete a `project` if it had no versions without the `manual_sync` finishing, since that could potentially create new versions again. This splits the work into two rake tasks; one to delete the versions, then a second to delete Maven projects without versions after the async workers are finished.

Split up Maven cleanup one-off into two tasks

---

lib/tasks/version_scheme_counter.rake
spec/tasks/version_scheme_counter_spec.rb

Spent some time investigating why this test started flaking in case there were any other interactions of state we needed to be concerned about. But, given the only effect is records being created "out of order", and the task output doesn't seem to be dependent on a given order, we just opted to apply a simple sort so we can assert against it consistently

Ensure sort order of output for consistent testing

---

lib/tasks/one_off.rake
spec/tasks/one_off_spec.rb

Previously, if there was a version with multiple repository sources, and one was ignored and another wasn't, this rake task would delete the version. Now, it doesn't do that, and instead just deletes the ignored repository sources.

Update Maven cleanup rake task to update and not delete versions with ignored and non-ignored sources

---

app/models/package_manager/packagist.rb

fixes this error, which is getting silenced into logs only, and which has happened about 1 million times in the past 2 weeks: `"ERROR Error while trying to get dependencies for Packagist/PACKAGE/NAME@1.0.0: no implicit conversion of String into Integer"`.

Fix Packagist dependencies update.

---

config/initializers/sidekiq.rb

these were useful when debugging the sidekiq-unique-jobs upgrade issue just now, but now they seem a little over-the-top.

Remove sidekiq-unique-jobs logs, they are a little noisy.

---

config/initializers/sidekiq.rb

`DEPRECATION WARNING: default_worker_options= is deprecated and will be removed from Sidekiq 7.0 (use default_job_options= instead)`

Silence sidekiq deprecation message

---

app/models/package_manager/base.rb
app/models/package_manager/haxelib.rb
app/models/package_manager/npm.rb
app/models/package_manager/rubygems.rb

there's an occasional bug we have where a version is ingested (via PackageManagerDownloadWorker) but the dependencies aren't saved on the initial download.
It's not clear why this is happening, so this PR adds some debugging code to monitor these a bit.

Adds some useful debugging for initial missing deps bug.

---

app/models/package_manager/cran.rb

CRAN is offline for maintenance today, so set a default timeout for HTML requests (the default seems to be a few minutes).

Set a reasonable 5-second timeout for CRAN requests.

---

app/models/package_manager/cpan.rb
app/models/package_manager/cran.rb

we need to select "dependency" as a returned field from their ES API, but "dependency" is an Object itself so ES complains that it's not a leaf node. Using `_source` lets us return that field specifically.
[docs on _source vs field](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html)
[docs on metacpan's API](https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md)

PackageManager::CPAN.dependencies(): fix this by passing the CPAN API "_source" instead of "field"

---

app/models/package_manager/maven.rb
app/models/package_manager/maven/maven_central.rb
spec/fixtures/vcr_cassettes/google-maven/memory-advice.yml
spec/fixtures/vcr_cassettes/maven-central/lambda-tracer.yml
spec/models/package_manager/maven/google_spec.rb
spec/models/package_manager/maven/maven_central_spec.rb

For Maven Central, search through HTML index directory for versions instead of using Maven metadata. This is required because Maven Central metadata is not guaranteed to include all versions.

Add way to get versions_from_html as opposed to searching through Maven metadata

---

app/models/package_manager/base.rb
app/models/version.rb
db/migrate/20231116161641_add_dependencies_count_to_version.rb
db/schema.rb
lib/tasks/one_off.rake
spec/models/package_manager/pypi_spec.rb
spec/models/version_spec.rb
spec/requests/api/projects_spec.rb

we need a "have dependencies been fetched yet?" flag on the Version model. To that end:
* adds `Version#dependencies_count`, which will be `nil` if we haven't fetched its deps yet
* (note that we have an existing `#runtime_dependencies_count` column)
* adds `Version#set_dependencies_count` method 
* call `Version#set_dependencies_count` after we've fetched a Version's dependencies (whether or not there are zero)
* adds `one_off:backfill_version_dependencies_count` task to backfill this column in batches

Implements Version#dependencies_count

---

app/controllers/api/projects_controller.rb
app/models/package_manager/base.rb
spec/models/package_manager/pypi_spec.rb
spec/requests/api/projects_spec.rb

when a release's dependencies haven't been fetched yet, return `dependencies: nil` instead of `dependencies: []`, as a signal that the client can try again later.
(followup to https://github.com/librariesio/libraries.io/pull/3255 )

Api::Projects#dependencies_bulk: return "dependencies: nil" when deps haven't been fetched yet

---

app/models/project.rb
app/workers/set_project_dependents_count_worker.rb
spec/workers/set_project_dependents_count_worker_spec.rb

this method can be pretty expensive, and doesn't make sense to do in an after_save callback.

Make the Project#set_dependents_count happen in an async callback

---

app/models/repository_host/bitbucket.rb

The bitbucket gem returns the response body as the error message, which may be a big blob of webpage source. This strips out non-word characters as a means to brute force sanitize it for the structured logging json.

fix: Squish down error message that may contain an entire webpage

---

app/models/package_manager/homebrew.rb

I think we always want to return an empty Array instead of nil here.

Return [] instead of nil from Homebrew when deps don't match.

---

app/models/repository_owner/bitbucket.rb
app/models/repository_owner/github.rb
app/models/repository_owner/gitlab.rb

fixes bugsnag 65527440cf4e030007888c55
there are no specs for the RepositoryOwners code, but it seems that there's an infinite recursion bug that pops up when a RepositoryUser's "user_type" is not the same value as found in the GH API (e.g. we have "User" in the database but now they're an "Organization" on GH).
``` ruby
RepositoryUpdateUserWorker
RepositoryUser.host(host_type).login(login).first.try(:sync)
download_user_from_host
download_user_from_host_by(owner.uuid)    
RepositoryOwner::Base.download_user_from_host(owner.host_type, id_or_login)
RepositoryUser.create_from_host(host_type, fetch_user(id_or_login))
RepositoryOwner::Github.create_user(user_hash)
if user_by_id 
unless user_by_id.login.try(:downcase) == user_hash[:login].downcase && user_by_id.user_type == user_hash[:type] …
```

Fix a "stack level too deep" bug with repository owner updates.

---

app/models/repository_owner/bitbucket.rb
app/models/repository_owner/github.rb
app/models/repository_owner/gitlab.rb

fixes bugsnag 65527440cf4e030007888c55
this is the same fix as in https://github.com/librariesio/libraries.io/pull/3271 , but for RepositoryOrganisations instead of RepositoryUsers.
I found a case with an org that had moved their login to a new account, and the old account got a new login. After this fix, the account with the stale login should be deleted, which would then get re-added by Repository#download_owner at some point. These records haven't been updated in 5 years, so fixing them like this is better than having the stale data around.

 Fix a "stack level too deep" bug with repository owner org updates.

---

app/controllers/application_controller.rb
app/controllers/projects_controller.rb
app/models/version.rb
app/views/projects/_releases.html.erb
app/views/projects/versions.html.erb
db/migrate/20231213145217_add_published_at_index_to_versions.rb
db/schema.rb
spec/tasks/one_off_spec.rb

Some projects with many versions (several thousand) will take quite a while to render the `Project` show page. Sort `Versions` by `number` in SQL where possible. Limit the semver diff behavior on number of `Versions`.

Version: replace most in-Ruby sorting

---

app/models/package_manager/npm.rb
spec/workers/package_manager_download_worker_spec.rb

NPM is currently unreliable in its update publishing: https://github.com/npm/feedback/discussions/937 The updates are coming in out of order, which is throwing off single version updates.
In order to increase its reliability, we are disabling per-version updates for NPM until the update issues affecting the CouchDB feed are resolved.
It looks like the main entrypoint to this is the PackageManagerDownloadWorker, so I'll monitor that when this change goes out. If there's any other places to watch, let me know and I can keep an eye out.

Disable single version updates for NPM

---

app/models/package_manager/cargo.rb

If the version doesn't actually exist, we get no body and it's throwing an error. Just assume the best case
(accidentally pushed straight to main but let's go ahead and review before deploying)

Fix up error when cargo is pointing ot a bogus version

---

app/models/project.rb

Sometimes missing packages on pkg.go.dev return 400 and others return 404, so this adds support for both (I think the 400s might be from invalid Go Modules, eg Godeps packages):
```
curl -I https://pkg.go.dev/launchpad.net/gocheck 
HTTP/2 400 
curl -I https://pkg.go.dev/github.com/some-nonexistent-fake/pkg
HTTP/2 404 
curl -I https://pkg.go.dev/launchpad.net/gozk/zookeeperd
HTTP/2 404 
```
🤷🏻

Support 400 for missing Go packages too.

---

app/models/package_manager/base.rb
app/models/package_manager/conda.rb
app/models/package_manager/go.rb
app/models/package_manager/maven/google.rb
app/models/package_manager/maven/maven_central.rb
app/models/package_manager/npm.rb
app/models/package_manager/pypi.rb
app/workers/package_manager_download_worker.rb
spec/workers/package_manager_download_worker_spec.rb

In order for a package manager to support single version updates, in the current code you need to do two things:
* Add a one_version method to the subclass
* Add a SUPPORTS_SINGLE_VERSION_UPDATE constant set to true
It's not clear that you have to do both of these things, and the existence of the one_version method on the subclass can indicate the same thing as the constant. Removing the constant simplifies the interface for package managers.
In the rare case where a package manager that supports single version updates needs to be disabled, the class method that checks for the one_version method's existence can be overridden.
This also fixes a bug where the Google Maven package manager incorrectly indicated it supported single version updates but did not implement one_version.

Remove SUPPORTS_SINGLE_VERSION_UPDATE constant

---

Gemfile.lock
config/initializers/bugsnag.rb

(followup to https://github.com/librariesio/libraries.io/pull/3185)
the newest version of the `bugsnag` gem includes a fix for redacting paths in the breadcrumbs, so we can remove our patch and upgrade the gem.

Update bugsnag 6.26.0 ~> 6.26.1 and remove interrim breadcrumb redaction fix.

---

app/workers/repository_maintenance_stat_worker.rb
config/initializers/sidekiq.rb

The big change here is setting a default TTL on Sidekiq Unique Job locks. The default is `nil` which means a lock will live _f o r e v e r_ and if the lock fails to clear for some reason then the job is locked until redis crashes or somebody comes along and manually clears them. This sets the default to 1 day which seems mostly reasonable and can be overridden in specific workers if needed.
The other piece of the PR is setting a TTL and a custom prefix so I can try and hunt down locks for maintenance stats specifically in the future.

Set a Default Unique Job Lock TTL and set some Specific Options on Maintenance Stat Worker

---

app/models/maintenance_stats/queries/github/commit_count_query.rb
app/models/maintenance_stats/stats/github/commits_stat.rb
spec/fixtures/vcr_cassettes/github/empty_repository.yml
spec/models/maintenance_stats/github/commit_count_stats_spec.rb

The GitHub GraphQL API does not seem to be consistent on which commit is the first returned. The order should be similar to what `git log` would return for the repository and there are some edge cases where a commit's data could have changed in a way where an older date commit is the first returned. This PR changes the query to look at the first 10 commits returned and find the latest date out of those. 10 is an arbitrary number but I didn't want the batch to be too big that it consumes more rate limit and the cases where I have found this to be a problem generally have the latest commit as the 2nd in the list returned from the query.
An example from https://github.com/dkubb/axiom-types/commits/master/
Query returns:
```
{
"data": {
"repository": {
"defaultBranchRef": {
"target": { …
```

Find Last Commit Date Out of Most Recent Batch of Commits

---

lib/tasks/maintenance_stats.rake

Now that we have fixed a few issues with the stat collection, we are collecting stats more often than we really need. This PR would update the task to only collect stats for repositories that are more than a week out of date rather than doing 2000 every hour as it is now.

Slow Down Stats Collection

---

Gemfile.lock

There is an error introduced in version 1.0.7 of the URL parser gem that needs to be fixed when resolving user URLs. This rolls back to the version before I bumped up to 1.0.8.

Downgrade URL Parser

---

app/controllers/api/projects_controller.rb
spec/requests/api/projects_spec.rb

If the caller is interested in dependencies for a version which has never successfully updated these, queue an update. But only if it's been at least 1 day since the last retry.

Queue PackageManagerDownloadWorker if it previously failed

---

app/workers/package_manager_download_worker.rb
spec/workers/package_manager_download_worker_spec.rb

sometimes `PackageManager::Base.update` can return `false`, so we need to check that before checking the resulting project's versions.

Ensure project update worked before checking project.

---

app/models/package_manager/maven.rb
app/models/package_manager/maven/google.rb
app/models/package_manager/maven/maven_central.rb
spec/models/package_manager/maven_spec.rb

Part of the problem with tracking down an issue with Google Maven was
that its behavior was too different from other package managers when it
didn't need to be. This gets Google Maven using more of the existing
infrastructure rather than inventing its own. It also cleans up some
additional API cruft, making method usages more consistent (even if
their parameters coming in are a little odd).

fix: [sc-39770] Make Google Maven act like other managers for updates/versions

---

config/initializers/pg_search.rb

I put this initializer in but: it is breaking the build, likely there's a better way to have that setting set, and we might not need it anyway

Remove setting custom similarity threshold

---

app/models/package_manager/go.rb
spec/models/package_manager/go_spec.rb

when we lookup Go Module names that we can't find to check for an alternative path to use, there are certain hosts that will be slow to respond. This adds a list of hosts that we want to explicitly skip when looking up Go Modules in `find_project_names` so we don't hold up `/api/checks` requests.

PackageManager::Go.find_project_names: skip certain hosts

---

Gemfile
Gemfile.lock
app/models/package_manager/conda.rb
app/models/package_manager/maven.rb
app/models/package_manager/multiple_sources_base.rb
app/models/package_manager/multiple_sources_base/provider_info.rb
app/models/package_manager/multiple_sources_base/provider_map.rb
app/models/package_manager/packagist.rb
app/models/project.rb
spec/factories.rb
spec/models/package_manager/multiple_sources_base/provider_map_spec.rb
spec/models/project_spec.rb

The Provider Maps are used to match Version#repository_sources to PackageManager classes for packages in ecosystems where multiple package providers exist. The original system was very lax in selecting the most appropriate provider, especially when multiple were involved.
Theoretically, a package should only be found at one provider, but in the case of Maven packages, this turned out to not be the case -- providers like Hortonworks and Atlassian provided their own versions of packages that also existed in Maven Central. We stopped examining Maven repos others than Google Maven and Maven Central, but unfortunately, some packages still present as belonging to these other less-supported repos.
The true fix for this is to remove any references to the old Maven repo in repository_sources, but …

Clean up Project Provider Map system

---

app/models/package_manager/maven.rb
spec/models/package_manager/maven_spec.rb

It's possible for Ox.parse to return nil when parsing. If that happens, raise a better error than `nil doesn't respond to <<`.

Better error for POM file parsing error

---

app/models/package_manager/go.rb
spec/models/package_manager/go_spec.rb

* `PackageManager::Go.project_find_names()`: avoid the case of an invalid Go Module from even being looked up

Ensure that Go hostnames are even valid when Libraries looks them up.

---

Gemfile
Gemfile.lock
app/models/package_manager/go/go_mod.rb
spec/models/package_manager/go/go_mod_spec.rb

* update `bibliothecary` to the newest version to get parsing support for the `replace` directive in go.mod (https://github.com/librariesio/bibliothecary/pull/585)
* adds a regression test for `replace` directive
* also, don't return local filepaths from `PackageManager::Go::GoMod#dependencies` bc Libraries has no need for them
this should prevent Libraries from seeing something like [this go.mod](https://github.com/netleapio/zappy-framework/blob/37b2a6ca97823b348a4a6ba7a365f811c891b384/go.mod) and trying to fetch `https://tinygo.org/x/tinyfont =>?go-get=1` as a url in `PackageManager::Go.package_find_names()`

Update bibliothecary to get new go.mod "replace" directive parsing

---

app/models/package_manager/go.rb

The caller to this was removed but this method was left behind.

Remove update_base_module Method

---

lib/tasks/auth_tokens.rake
spec/tasks/auth_tokens_spec.rb

Exceptions are being raised on the scheduled task to remove unauthorized tokens for ones that have hit their limit before we check on them. This should handle that error directly in the task so it the loop can continue.

Handle Exhausted Tokens When Setting Authorized

---

lib/tasks/auth_tokens.rake

I ran into issues where the initial call to the API seemed fine but the next call tripped the API error. This PR moves all the API calls into the rescue block.

Auth Token Reverify - Wrap All API Calls in Rescue

---

app/models/package_manager/npm.rb
spec/models/package_manager/npm_spec.rb

These changes tweak the behavior of NPM deprecation detection again:
we marked an NPM package as "Deprecated" if the latest-release had a "deprecation" message in the API.
we [changed the logic](https://github.com/librariesio/libraries.io/pull/3053) to require *all releases* to have a "deprecation" message for the package to be marked as "Deprecated". This was for two reasons:
* we were marking packages like [graphql](https://www.npmjs.com/package/graphql?activeTab=versions) as "Deprecated" because they publish frequent canary builds that are marked with a "deprecation" message. Whenever the latest release was a deprecated canary build and Libraries marked it "Deprecated", this gave the illusion that the package was deprecated even though it was very active.  
* and also the `npm …

NPM: change deprecation logic to only require latest non-prerelease to be deprecated

---

app/models/repository.rb

Project updates call the create function instead of update so Repository statuses were not being set correctly on Project updates and a full update would only run if any Repository details changed. This PR adds the Repository status method call into the create function so statuses would be set correctly on a Project update.

Add Repository Status Logic to Create Function

---

app/models/concerns/github_identity.rb

Update `id` to map to the upstream repository `uuid`

Fix Sync Permissions Worker Error

---

app/controllers/api/application_controller.rb
config/initializers/rack_attack.rb
lib/subscribers/rack_attack.rb
spec/requests/api/application_spec.rb

before https://github.com/librariesio/libraries.io/pull/3277 , we served `X-RateLimit-Limit` and `X-RateLimit-Remaining` headers in non-rate-limited responses to transmit info about rate-limiting to clients.
after https://github.com/librariesio/libraries.io/pull/3277 , those successful response headers were removed, and we added `RateLimit-Limit`, `RateLimit-Remaining`, and `RateLimit-Reset` headers to non-rate-limited responses, so unfortunately clients could no longer track their usage in successful responses.
these changes bring back the former non-rate-limited headers, and also prefix the rate-limited headers with `X-` since those headers are not quite a standard yet, at time of writing: https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-07.html .
```
HTTP/1.1 200 OK …
```

Re-add rate-limit headers back to non-rate-limited responses.

---

app/controllers/api/search_controller.rb
app/serializers/project_serializer.rb
spec/factories.rb
spec/requests/api/search_spec.rb

For performance gains / payload reduction, allow the querystring param `?include_versions=false`. Defaults to `true`

Search: allow opting out of versions

---

app/models/project.rb
lib/tasks/projects.rake
spec/models/project_spec.rb

if admins set a project's status to `"Hidden"`, we don't want to override that decision whenever the project's status is checked regularly.

Project#check_status: don't override status if it's manually set.

---

app/models/project.rb
db/migrate/20240409222313_add_latest_version_id_to_projects.rb
db/schema.rb

this new column can cache the most recently published `Project#versions` so we can do `includes()` and `joins()` against it. We currently do a query everytime we fetch `latest_version`: https://github.com/librariesio/libraries.io/blob/8cad44493718ea89347074a08db925dd5ca48b80/app/models/concerns/releases.rb#L40-L42
in a followup PR, we'll backfill this value, change it to a real association, and keep it updated in the same place that we keep `latest_release_published_at` + `latest_release_number` updated: https://github.com/librariesio/libraries.io/blob/main/app/models/project.rb#L268-L270
(NB: "latest release" means "either latest version or latest tag", but "latest version" will simply be the latest Version only)

Migration: adds Project#latest_version_id

---

app/models/project.rb
spec/models/project_spec.rb

This PR updates the `check_status` logic for Go packages to treat a redirect from pkg.go.dev as a "Removed" package. The reasons for this change are to help capture when packages are renamed or recased and mark the now incorrect one appropriately. This is just an idea, so feel free to disagree with this approach. 
One example is:
https://libraries.io/go/github.com%2FAzure%2Fazure-pipeline-go vs https://libraries.io/go/github.com%2Fazure%2FAzure-pipeline-go which both reference `github.com/Azure/azure-pipeline-go`. This PR would mark `github.com/azure/Azure-pipeline-go` as removed.
```shell
> url = "https://pkg.go.dev/github.com/azure/Azure-pipeline-go"
> response = Typhoeus.get(url)
> response.response_code
=> 302
> response.body
=> "<a …
```

Treat Redirected Go Packages as Removed

---

app/models/concerns/releases.rb
app/models/project.rb
db/migrate/20240409222653_backfill_projects_latest_version_id.rb
db/schema.rb
spec/models/project_spec.rb

(followup to https://github.com/librariesio/libraries.io/pull/3356)
* a backfill migration to populate `Projects#latest_version_id` (this has already been run on production)
* replace `Project#latest_version` method with a new `:latest_version` belongs_to association
* add a `set_latest_version` method that updates that column after a `Project` is saved

Add Project#latest_version assocation, keep it up-to-date on save, and backfill it.

---

app/controllers/api/docs_controller.rb
app/controllers/api/repositories_controller.rb
app/controllers/project_usage_controller.rb
app/controllers/repositories_controller.rb
app/models/package_manager/carthage.rb
app/models/project.rb
app/models/repository.rb
app/models/repository_subscription.rb
app/models/repository_tree_resolver.rb
app/models/tag.rb
app/models/user.rb
app/models/version.rb
app/models/web_hook.rb
app/serializers/dependency_serializer.rb
app/views/admin/stats/index.html.erb
app/views/admin/stats/overview.html.erb
app/views/api/docs/index.html.erb
app/views/dashboard/_github_repository.html.erb
app/views/repositories/_stats.html.erb
app/views/repositories/dependencies.html.erb
lib/tasks/open_data.rake
spec/models/project_spec.rb
spec/models/web_hook_spec.rb
spec/requests/api/repositories_spec.rb

this PR adds a `Repository#projects_dependencies` method and adds it to endpoints/codepaths where we want to fetch a repo's deps.
``` mermaid
flowchart TB
subgraph "AFTER"
direction TB
Repository1["Repository"] --> Project
Project --> Version
Version --> Dependency1["Dependency 1\n e.g. 'rack 1.0.0'"]
Version --> Dependency2["Dependency 2\n e.g. 'dalli ~> 2.0.0'"]
Version --> Dependency3["Dependency 3\n e.g. 'bibliothecary ~ 1.7'"]
end
subgraph "BEFORE"
direction TB
Repository2["Repository"] --> RepositoryDependency4["Dependency 1\n e.g. 'rack 1.0.0'"]
Repository2["Repository"] --> RepositoryDependency5["Dependency 2\n e.g. 'dalli ~> 2.0.0'"]
Repository2["Repository"] --> RepositoryDependency6["Dependency 3\n e.g. 'bibliothecary ~ 1.7'"]
end
```
**RepositoryDependency** is populated by …

Replace queries against RepositoryDependency with Dependency 

---

app/domain/repository/persist_repository_from_upstream.rb
app/models/repository_host/raw_upstream_data_converter.rb
spec/domain/repository/persist_repository_from_upstream_spec.rb

Presently, if we mark a Repository as with `status: "Removed"`, that is a terminal state which the Repository cannot leave. This PR enables unsetting the Repository's `status`, provided that the repository is reachable, and we get `archived: false` from the RepositoryHost.

Repository: allow status: "Removed" to be unset

---

app/models/package_manager/go/go_mod.rb
spec/models/package_manager/go/go_mod_spec.rb

these days `go.mod` files declare their name like `module my.go/module/name` at the top of the file, but it [looks like vgo](https://research.swtch.com/vgo-intro#defining_go_modules), the predecessor to Go Modules, actually quoted the name, e.g. `module "my.go/module/name"`
Go still seems able to parse these older `go.mod` files and will also auto-correct them when it updates the `go.mod` file. But pkg.go.dev [doesn't consider them valid](https://pkg.go.dev/github.com/simonwaldherr/gwv).
this adds support for the quoted names when looking up the canonical name via the Go Proxy's go.mod API, to avoid errors like these when updating the package:
`bad URI(is not URI?): "https://pkg.go.dev/\"github.com/SimonWaldherr/gwv\""`

GoMod#canonical_module_name: handle go module names from go.mod that have double-quotes 

---

lib/tasks/open_data.rake

this CSV doesn't make sense anymore since [RepositoryDependency is being phased out](https://github.com/librariesio/libraries.io/pull/3362)

Remove data/repository_dependencies-VERSION-DATE.csv from open data

---

app/controllers/admin/stats_controller.rb
app/controllers/api/docs_controller.rb
app/controllers/api/repositories_controller.rb
app/models/concerns/repo_metadata.rb
app/models/manifest.rb
app/models/repository.rb
app/models/repository_dependency.rb
app/models/repository_organisation.rb
app/models/repository_subscription.rb
app/models/repository_user.rb
app/models/tag.rb
app/models/user.rb
app/models/version.rb
app/views/admin/stats/overview.html.erb
app/views/admin/stats/repositories.html.erb
spec/models/manifest_spec.rb
spec/models/project_spec.rb
spec/models/repository_dependency_spec.rb
spec/models/repository_organisation_spec.rb
spec/models/repository_spec.rb
spec/models/repository_user_spec.rb
spec/models/user_spec.rb

in the quest to [phase out RepositoryDependency](https://github.com/librariesio/libraries.io/pull/3362), this removes any views or logic around Manifests. Manifests aren't used at all outside of RepositoryDependency code.
Because data in the Manifest table are disconnected from data in the Projects and Dependency tables, which we want to use instead of RepositoryDependency:
``` mermaid
flowchart BT
Project --> Repository
Dependency --> Project
Manifest --> Repository
RepositoryDependency --> Manifest
```

Remove Manifest logic and code

---

app/models/concerns/repository_source_rank.rb

one location where I forgot to switch usage of `Repository#dependencies` to `Repository#projects_dependencies`

Fix RepositorySourceRank after the move to projects_dependencies.

---

app/controllers/api/repositories_controller.rb
app/serializers/repository_serializer.rb
spec/requests/api/repositories_spec.rb
spec/serializers/repository_serializer_spec.rb

``` shell
curl https://libraries.io/api/github/librariesio/bibliothecary?include_readme=true
{
"full_name": "librariesio/bibliothecary",
"readme_html_body": "<!DOCTYPE html PUBLIC \"-//W3C//DT ... ",
...
}
```

Api::Repositories#show: pass readme back when ?include_readme=true

---

app/models/project.rb

* use custom queries to fetch dependent counts instead of associations
* wrap the dependent repos count in a long timeout too, to avoid this err:
```
ActiveRecord::QueryCanceled 
SetProjectDependentsCountWorker@small
PG::QueryCanceled: ERROR: canceling statement due to statement timeout 
```

Project#set_dependencies_count: wrap refactored dependent_repositories in timeout

---

app/controllers/api/repositories_controller.rb
app/models/project.rb
app/models/repository.rb
config/routes.rb
spec/requests/api/repositories_spec.rb

this endpoint is similar to the `Api::Projects#sync` endpoint, and only works for internal keys as well.
e.g. `curl https://libraries.io/api/github/librariesio/bibliothecary/sync?api_key=...

Adds an Api::Repositories#sync internal endpoint

---

app/models/dependency.rb
db/migrate/20240501171850_add_index_to_dependencies.rb
db/schema.rb

* removes a `dependencies(project_id)` index because we have a `dependencies(project_id, created_at)` covering index now
* adds a `dependencies(:project_id, :version)` to improve the "get a project's dependent repos" query [here](https://github.com/librariesio/libraries.io/commit/8b09b45e87adb05651b5745657274b41ea6751fc#diff-611e7045e8b0212d101cd856c335296959519af63b80129f51c246a7bbfe7b91R409).
This should help the "dependent repos" query on Project, which goes thru Version.

Change Dependencies [project_id] index to [project_id version_id]

---

app/models/concerns/monitoring.rb

this fixes a scope that became too ambiguous after the recent refactor and removal of RepsitoryDependency:
```
PG::AmbiguousColumn: ERROR: column reference "repository_id" is ambiguous LINE 1: SELECT "repository_id" FROM "dependencies" INNER JOIN "versi... ^ 
```

Fix an ambiguous column ref after the repo deps refactor.

---

app/models/repository.rb
spec/models/repository_spec.rb

It seems like we should be setting this if we get a 404 response when requesting repository data.

Set last_synced_at for Removed Repositories

---

app/controllers/api/repositories_controller.rb
config/routes.rb
spec/requests/api/repositories_spec.rb

This adds another route to get to the `repository#show` API endpoint. We occasionally hit route name conflicts when the `name` path parameter matches to another route. For example sending something like `repositories` will link to the `repository_users#repositories` route instead of our intended route.

Add repository#show Route Using Query Parameters Instead of Path Parameters

---

app/models/package_manager/pypi/json_api_project.rb
spec/models/package_manager/pypi/json_api_project_spec.rb

I could not find any support for this logic when researching how to deprecate a package on PyPI and it is causing issues for legitimate packages being labeled incorrectly.

Remove Logic to Deprecate a PyPI Project if Latest Version is Yanked

---

app/models/repository.rb

`Api::Repositories#sync` should be fast because it just kicks off a sidekiq job via `Repository#manual_sync`, but the traces are very slow (DD is not displaying them for me ATTM). 
after kicking off the job, `Repository#manual_sync` then updates the `last_synced_at` field so it doesn't get re-synced before it finishes syncing, but that `update()` kicks off a chain of callbacks in Repository and for all Repository#projects. So I'm minimizing the work done on this endpoint by changing it to a direct column update instead of a full save with callbacks.

Speed up Api::Repositories#sync by avoiding callbacks

---

app/models/project.rb

The `Project#manual_sync` method was added in https://github.com/librariesio/libraries.io/commit/e95cee4857425e139b6946378f48efe6fcc692ab and kicks off async jobs to update a project, so nothing in that method call actually should update the Project. But there's a `forced_save` in that method that just saves the record with a new `:updated_at`. 
From my archaeological dig, I believe that `forced_save` was just to ensure that Elasticsearch record for the Project was updated, but `manual_sync` shouldn't be updating anything in the Project since it just kicks off async jobs. 
The unintended side-effects of this `forced_save` call is the callback chain that happens with it:
```
after_commit :set_dependents_count_async, on: %i[create update]
after_commit :update_source_rank_async, on: …
```

Project#manual_sync: cease saving the project record bc we're just kicking off async workers.

---

app/models/package_manager/pypi/json_api_project.rb
app/models/package_manager/pypi/version_processor.rb
spec/models/package_manager/pypi/json_api_project_spec.rb

Follow up to https://github.com/librariesio/libraries.io/pull/3389
This PR uses the upstream API data to determine if a PyPI project should be marked as deprecated. It checks for all non pre-release version numbers and if they are all yanked then takes the reason text from the most recent release. This should capture projects like https://pypi.org/project/gitlab/#history which have essentially been completely pulled down for use.

Mark a PyPI Project Deprecated If All Versions are Yanked

---

app/models/concerns/source_rank.rb

Updating a project leads to calculating the source rank which leads to updating the project ...

Don't trigger callbacks when updating sourcerank

---

app/models/package_manager/cocoa_pods.rb
docs/add-a-package-manager.md
spec/models/package_manager/cocoa_pods_spec.rb

(followup to https://github.com/librariesio/libraries.io/pull/3397)
```ArgumentError 
PackageManagerDownloadWorker@critical
wrong number of arguments (given 1, expected 0; required keyword: number)
```

CocoaPods bugfix: pass kwargs to VersionBuilder instead of a Hash

---

app/models/package_manager/nu_get.rb
spec/models/package_manager/nu_get_spec.rb

changes to `PackageManager::Nuget`:
* rename `get_releases()` to `raw_versions()`, to avoid confusion and make more consistent with the `versions()` method
* also rename the `:releases` key in its raw project data to `:raw_versions` for consistency
* when we get a raw version from NuGet's API that has "published=1900-01-01...", **do not** update the "published_at" on our side to 1900 (so we keep the original published_at date, and set the `Version`'s "status" column to "Deprecated"
this would be Libraries' first use-case for deprecated Versions.

PackageManager::NuGet: stop recording "1900" published dates

---

app/models/package_manager/nu_get.rb
spec/models/package_manager/nu_get_spec.rb

this is to handle the case of an "unlisted" package on NuGet being "re-listed". We're not sure if this is possible yet, but we should handle it JIC.
re this convo: https://github.com/librariesio/libraries.io/pull/3400#discussion_r1631631024
(followup to https://github.com/librariesio/libraries.io/pull/3398)

Ensure we set "status: nil" on non-Deprecated NuGet packages.

---

app/models/package_manager/go.rb
spec/models/package_manager/go_spec.rb

Cache a timeout response the same way that we cache an unreachable host name when trying to resolve an unknown go project name to avoid trying to resolve it multiple times.

Cache Timed Out Go Project Names

---

app/models/package_manager/nu_get.rb
lib/tasks/one_off.rake
spec/models/package_manager/nu_get_spec.rb

It turns out that a release on NuGet can be "unlisted" but not "deprecated" on their side, e.g. `"RestSharp@105.2.0"`, and it's not clear why. 
But we consider both "unlisted" and "deprecated" on the NuGet side as "status: 'Deprecated'" on our side. This fix ensures we don't save the 1900 "published" date on these cases.

Ensure that NuGet releases that don't have "deprecation" field but have "published=1900" are not saved with "published_at: 1900"

---

app/models/package_manager/maven.rb
app/models/package_manager/maven/maven_central.rb

There are some cases (for example, commons-discovery:commons-discovery) where the version listed as latest in maven-metadata.xml isn't actually present on central. This lets us fallback to our scraping and using that.
Also improves the scraping of the latest version to prefer non date formatted versions as that's an older maven practice

Handle weird case where latest in maven-metadata doesn't exist

---

app/models/project.rb

If we get back an error response when checking the status of a package, don't let that update the status to ok
Log so that we can investigate them (but they'll get retried in a week)

Handle failure modes when checking package status

---

Gemfile.lock

On my setup, I was unable to `bundle install`. I was getting the issue described [here](https://github.com/brianmario/charlock_holmes/issues/172#issuecomment-2200823928). Upgrading the transitive dependency `charlock_holmes` fixed this for me.

Upgrade charlock_holmes

---

app/models/auth_token.rb
db/migrate/20240722132217_add_scopes_to_auth_token.rb
db/migrate/20240722132336_backfill_add_scopes_to_auth_token.rb
db/schema.rb
lib/tasks/auth_tokens.rake
spec/tasks/auth_tokens_spec.rb

This would be useful data to have when we need to make an API call with a specific scope. We can query directly for any authorized tokens we have with the required scope before attempting to make the API call.

Save Scopes an Auth Token Has Access To

---

app/models/auth_token.rb
app/models/repository_host/github.rb
lib/tasks/auth_tokens.rake
spec/models/auth_token_spec.rb

This adds some logic to grab tokens with specific scopes when needed. The logic is used to help re-enable to the API call to gather document URLs for repositories as that call needs some sort of repo scope enabled.

Add Logic To Fetch Tokens With Specific Scopes

---

app/models/repository.rb

We have this `last_synced_at` datetime stored on the `Repository` and I think it is mainly used to guard against syncing the data for a Repository more than once [within a two minute period](https://github.com/librariesio/libraries.io/blob/c121c579406c47b9ed29ba32495003b1f3b5efcb/app/models/repository.rb#L289). We set this time when we manually want to resync a repository which I think makes it never update due to the guard code that eventually gets called via an async worker.

Don't Set last_synced_at When Queueing Repository Resync

---

app/models/auth_token.rb

I forgot to include the argument in the call made to the function when it needs to retry finding a token.

Pass Through Scope Argument When find_token Retries

---

app/models/project.rb
spec/models/project_spec.rb

Reverts librariesio/libraries.io#3428
this is actually just a noop, and handled by `elsif !platform.downcase.in?(%w[packagist go]) && [400, 404, 410].include?(response.response_code)`

Revert "Bs/handle removed npm packages"

---

app/models/project.rb
spec/models/project_spec.rb

* handle 429 response code
* handle response error codes more explicitly (directly checking the response code numbers instead of previously used `.failure?` check), & guard revert to status: `nil` unless response status is a success

handle response error codes more explicitly & guard revert to nil status unless response status is a success

---

Gemfile
Gemfile.lock
app/models/project.rb
db/migrate/20240815181932_install_audited.rb
db/schema.rb
spec/models/project_spec.rb
spec/spec_helper.rb

this adds the [`audited` gem](https://github.com/collectiveidea/audited) to Libraries so we can start tracking historical data, e.g. `Project#homepage`. 
In a following PR, I'll lax-en the requirements for a Project's data to be updated, so having `audited` around will give us a little backup in case something goes wrong.
I tried overwriting the "audited" method so that it requires you to pass the "only:" key, such that we limit the data we audit to specific data, but I'm having trouble monkeypatching that method.

Introduce "audited" gem to Librarires

---

app/models/package_manager/base/version_builder.rb
app/models/package_manager/nu_get.rb
spec/models/package_manager/base/version_builder_spec.rb
spec/models/package_manager/nu_get_spec.rb

it looks like this method has been broken for a while, but PackageManager::Base [logs the error and never notifies us via Bugsnag](https://github.com/librariesio/libraries.io/blob/96225bffe6ff7bf90535f8dd29fa195b5b8993a6/app/models/package_manager/base.rb#L311-L316), so I only discovered it via DD:
```
ERROR Error while trying to get dependencies for NuGet/LocalisedString@1.3.0: undefined method `find' for nil:NilClass
current_version = mapped_project[:raw_versions].find { |v| v.version_number == version }
```

Fix PackageManager::NuGet.dependencies()

---

app/models/package_manager/base.rb

about [2 years ago](https://github.com/librariesio/libraries.io/pull/2922), a change was made to preserve a `Project#repository_url` if it suddenly goes `nil` upstream, so that we still have *something* of a value. 
but this is still incorrect data, and we have [audits on `Project#repository_url` now](https://github.com/librariesio/libraries.io/pull/3438), so we can look up historical values if they go `nil`.

Cease keeping around stale Project#repository_urls if they go nil on updates

---

app/workers/repository_download_worker.rb
config/initializers/sidekiq.rb

now that we have [audited on Libraries](https://github.com/librariesio/libraries.io/pull/3438), we're noticing a curious race condition situation:
* Repo1 has two projects: Project1 and Project2
* Project1 and Project2 both get pushed by their maintainer at the same time
* Depper picks up the two updates and enqueues two PackageManagerDownloadWorkers jobs for Libraries
* each PackageManagerDownloadWorker job kicks off a Repository update for the same Repository here: https://github.com/librariesio/libraries.io/blob/96225bffe6ff7bf90535f8dd29fa195b5b8993a6/app/models/package_manager/base.rb#L253
* ... so Project1 kicks off RepositoryDownloadWorker
* and while that RepositoryDownloadWorker ^ is running, Project2 kicks off another RepositoryDownloadWorker
* the first RepositoryDownloadWorker …

Lock RepositoryDownloadWorker while it's executing too

---

app/models/package_manager/carthage.rb

(followup to https://github.com/librariesio/libraries.io/pull/3362)

Carthage.project_names: fix the scope after projects_dependencies refactor

---

app/models/project.rb
app/workers/check_status_worker.rb
spec/models/project_spec.rb
spec/workers/check_status_worker_spec.rb

`Project#check_status` gets rate-limited occasionally by NPM and NuGet for up to 50k packages within a 1-2 hour time period.
currently we're skipping these updates if we get 429'ed, so we are probably missing status updates for many projects. 
this offers two quick fixes:
1) lock `CheckStatusWorker` **during the job** to avoid cases where a Project might be simultaneously enqueued >1 at a time.
2) when we get 429'ed, re-queue the `CheckStatusWorker` for 10-60 minutes from now, so we don't lose the status update, and to distribute the requests evenly.
the bigger fix for this could be creating a semaphore around each platform's "check_status" request, so we could only have X requests at a time per platform.

CheckStatusWorker: better lock, and retry 429s.

---

app/controllers/projects_controller.rb
app/views/projects/index.html.erb

make logged in user dashboard / homepage experience the same as a logged out user (just without "log in" buttons)
the old page is still accessible from the user dropdown in the top right, under "Repository Monitoring"
https://github.com/user-attachments/assets/6fcbe4f2-feb5-4143-8f54-1b2cc7e79f06

make logged in /dashboard the same as not logged in experience

---

app/models/package_manager/base/mapping_builder.rb
app/models/package_manager/maven.rb
spec/models/package_manager/maven_spec.rb

The `properties` field for Maven package data mapping was quietly dropped in https://github.com/librariesio/libraries.io/pull/3397 which causes `nil` errors when passing the pom XML files to Bibliothecary for parsing. This adds the `properties` back in to the mapping hash if some are passed in to fix that. This might also create more issues as this is re-enabled.

Include Properties in Mapping Hash 

---

Gemfile
Gemfile.lock
app/models/package_manager/base.rb
app/models/package_manager/maven.rb
spec/models/package_manager/maven/google_spec.rb
spec/models/package_manager/pypi_spec.rb

This bumps bibliothecary to the latest version, which also replaces the dependency hash with the new `Bibliothecary::Dependency` class. This also gives us a valid `requirement` attribute by default to use. So, hopefully we'll have mostly valid entries to upsert now and this won't be noisy. 
Re-raising the error so we halt seemed like the safe route to take, but if it's too pernicious, we can take that out and just rely on the logging.

Fix silently ignoring invalid dependencies

---

app/models/project.rb
spec/fixtures/vcr_cassettes/project/check_status/private_package.yml
spec/models/project_spec.rb

there are some packages in Libraries that return `302` when we fetch them from NPM, which means they're not accessible, i.e. not open-source. This starts marking those libraries as "Removed":
```
> curl -I "https://www.npmjs.com/package/@abcdef/ghijk"
HTTP/2 302 
location: /login?next=%2Fpackage%2F%40abcdef%2Fghijk
```

Consider privately scoped NPM packages that return 302 as Removed.

---

app/views/shared/flashes/libraries-and-tidelift.html.erb

space got included in the link, oopsie

dont highlight the space after the link

---

app/models/package_manager/base.rb
app/models/package_manager/cran.rb

This particular method existed on PackageManager::Base, but currently was only used by cran, and since it calls a method `find_dependencies` that currently only exists on cran, I just inlined it. Hopefully reduces some confusion!

Refactor away base method only used in one subclass

---

app/models/package_manager/npm.rb
spec/models/package_manager/npm_spec.rb

We were expecting this field to be a string or nil, but apparently
it can also be `false`
Handle it being `true` too just in case, though we haven't confirmed
that this happens, we do have some examples where deprecation_reason
is "t" which looks suspiciously like that could be what happened.

NPM: when `"deprecated":false` handle it correctly

---

app/workers/check_status_worker.rb

followup to https://github.com/librariesio/libraries.io/pull/3447

CheckStatusWorker: fix the time unit for retry from seconds to minutes

---

app/workers/check_status_worker.rb
spec/workers/check_status_worker_spec.rb

the last fix for retrying Project status 429s didn't help a ton, so this tries a new strategy:
* when we get a 429 while checking status, *don't* retry again in X.minutes. 
* instead, set the`Project#status_checked_at` timestamp to nil so that our nightly `projects:check_status` rake task picks it up during the nightly run

CheckStatusWorker 429s: reset timestamp to nil instead of retrying

---

app/models/package_manager/go.rb
app/workers/go_project_verification_worker.rb
spec/models/package_manager/go_spec.rb

In the case of [this forked Go package](https://libraries.io/go/github.com%2Fphilipatl%2Fwebsocket/v1.4.2), the name listed in their [go.mod file](https://github.com/philipatl/websocket/blob/master/go.mod) (which is used to get the canonical Go name in libraries) does not match their github url/name. This means libraries is pulling the incorrect information for this package.
The change here is to log when the name listed in the repository's go.mod file is not the same as the input package name, and favor the package name for lookups when they don't match.

Check the canonical Go project name against the passed in Go project name

---

app/models/project.rb

(followup to https://github.com/librariesio/libraries.io/pull/3477)
now that we're not getting constant 429s, I've tested `Project#check_status` against NPM, and found that `10 requests per 5 seconds` should be a safe rate at which to query NPM projects.

Project#check_status: relax our throttle a bit.

---

app/models/project.rb
app/workers/check_status_worker.rb
spec/models/project_spec.rb
spec/workers/check_status_worker_spec.rb

(followup to https://github.com/librariesio/libraries.io/pull/3477)
this changes up our strategy of fetching NPM package urls:
* fetch the `"retry-after"` value from the NPM response
* instead of using `RateLimitService`, just store `"retry-after"` in Redis with an expiry
* if we are checking an NPM package url, and `"retry-after"` exists, reschedule the request to the proper time
* ensure that we store this value **per host**, since different hosts will receive different values

Project#check_status: change the strategy of rate-limiting ourselves

---

app/models/package_manager/nu_get.rb
spec/models/package_manager/nu_get_spec.rb

 PackageManager::NuGet: treat "" requirement as "*" when fetching dependencies

---

app/models/package_manager/base.rb

* use `.pluck` instead of `.select` to avoid hydrating AR models and also pull less data from the db

PackageManager::Base.save_dependencies: use pluck instead of select

---

app/models/project.rb
app/models/repository.rb
spec/models/project_spec.rb

the `Project#check_status` 429 issue is resolved, but I've come across thousands of projects that now have thousands of blank audits that indicates that `check_status` is being called on them frequently. 
I can't find the exact codepath that would trigger `CheckStatusWorker`, but the main culprit is `Project#async_sync`, which is called from many places.
we should probably just limit `Project#check_status` to once per day, which should solve the issue!
```
> Project.find(6990999).audits.pluck(:created_at, :comment, :audited_changes).reverse
[[Mon, 07 Oct 2024 19:58:55.382661000 UTC +00:00, "Response 404", {}],
[Mon, 07 Oct 2024 18:50:25.421502000 UTC +00:00, "Response 404", {}],
[Mon, 07 Oct 2024 17:26:34.656901000 UTC +00:00, "Response 404", {}],
[Mon, 07 Oct 2024 16:59:48.967348000 UTC …
```

Debounce Project#check_status to once per day

---

app/controllers/api/projects_controller.rb
app/models/concerns/dependency_checks.rb
app/models/package_manager/base.rb
app/models/package_manager/cran.rb
app/workers/go_project_verification_worker.rb
app/workers/package_manager_download_worker.rb
lib/tasks/projects.rake
spec/requests/api/projects_spec.rb
spec/workers/package_manager_download_worker_spec.rb

* adds "source" to some logs in `PackageManager::Base` so we can track down some superfluous "save_dependencies()" calls

Pass "source" down to PackageManager::Base#save_dependencies() for logging

---

app/models/package_manager/base.rb
app/models/project.rb
spec/models/package_manager/pypi_spec.rb

this handles a pernicious race condition wherein a Project is created in another worker, right after the current Process has run the `Project.validates :name, uniqueness: true` validation but before it saves the Project.

Handle ActiveRecord::RecordNotUnique when creating projects too

---

app/models/web_hook.rb
spec/workers/project_updated_worker_spec.rb

For the webhooks that get an update on every change, we end up hammering the db a bit unnecessarily. Just don't update the last response / last sent info for those hooks

don't update webhook sent info for all project hooks

---

app/models/package_manager/cocoa_pods.rb
spec/models/package_manager/cocoa_pods_spec.rb

This switches to using the cocoapods CDN to get information about cocoapods per the details in
https://blog.cocoapods.org/CocoaPods-1.7.2/

Update cocoapods things to rely on "newer" cocoapods infrastructure

---

app/models/package_manager/cocoa_pods.rb

* fixes this error, from encounters with emoji names like ["🔒"](https://github.com/CocoaPods/Specs/blob/824d64bcc07cbc479d1d9cc83155314a2febfca5/Specs/%F0%9F%94%92/0.2.0/%F0%9F%94%92.podspec.json):
```
Encoding::CompatibilityError 
PackageManagerDownloadWorker@critical
incompatible character encodings: ASCII-8BIT and UTF-8
```

Support emoji in Cocoapods names.

---

app/models/package_manager/cocoa_pods.rb
spec/models/package_manager/cocoa_pods_spec.rb

fixes this error, for packages like `AFNetworking`:
```
ActiveRecord::RecordInvalid 
PackageManagerDownloadWorker@critical
Validation failed: Number can't be blank
```

CocoaPods: handle deprecated version entries

---

spec/models/project_spec.rb
spec/serializers/project_serializer_spec.rb

* clarify that we serialize repository_url that doesn't
have to match repository.url because we fall back to
home page for example when setting project.repository
* add a little test coverage for project.update_repository

Project: specs related to repository_url

---

app/controllers/api/repositories_controller.rb
config/routes.rb
spec/requests/api/repositories_spec.rb

This adds an `/api/repository/projects` endpoint that returns only the platform and name of Projects tied to a Repository. The current `/host_type/owner/name/projects` endpoint returns full `Project` objects with full `Version` objects and 500s pretty regularly due to the size of the response and the amount of data being returned. This new endpoint also moves all the parameters into query parameters to avoid any issues with the dynamic path segments potentially triggering the incorrect controller methods if the parameters happen to clash between routes.

Add Shallow Repository -> Project Names Endpoint

---

app/serializers/project_updated_serializer.rb
spec/models/web_hook_spec.rb
spec/workers/project_updated_worker_spec.rb

This is needed in particular to ignore status=Hidden

ProjectUpdatedSerializer: include the project status

---

app/models/concerns/releases.rb
app/models/project.rb
spec/models/project_spec.rb

We seem to be sending a fair number of webhooks when there
was no bump to updated_at, because after_commit runs when
you update, even if the save had nothing to save.
Stop doing that.

Project: do not send webhook when nothing actually happened

---

app/workers/project_updated_worker.rb
spec/workers/project_updated_worker_spec.rb

We [had set ignore_errors:true to reduce logging noise](https://github.com/librariesio/libraries.io/pull/3396), but unfortunately
it means this job never retries and enver exhausts retries. To retry or
to exhaust retries we need to raise an exception.
While there have been no errors from the all_projet_updates hooks that
I see in the past 24 hours, we do want to be sure we retry if there
ever are such errors.

ProjectUpdatedWorker: don't ignore errors on all_project_updates

---

app/controllers/api/status_controller.rb

mostly interested in reproducing slow rendering times like these:

Api::Status#check: Include list of project ids when tracing rendering

---

app/serializers/optimized_project_serializer.rb
spec/serializers/optimized_project_serializer_spec.rb

as @havocp points out, we need to fallback `Version#published_at` to `#created_at` when nil: https://github.com/librariesio/libraries.io/blob/627292f67f02d3d2a0a5e19c7a9be00acaec9dc4/app/models/version.rb#L141-L143

OptimizedProjectSerializer: fall back to created_at for published_at

---

Gemfile
Gemfile.lock
app/models/package_manager/maven.rb
app/models/package_manager/maven/maven_url.rb
spec/fixtures/vcr_cassettes/maven-central/jaxb-runtime.yml
spec/models/package_manager/maven_spec.rb

Story details: https://app.shortcut.com/tidelift/story/46631
The issue here was that [jaxb-runtime-2.3.1.pom](https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.1/jaxb-runtime-2.3.1.pom) contains a FastInfoset dependency without the `<version>` tag. So when sent to bibliothecary for parsing, bibliothecary assumes `*` for the version.
If you follow that bom's parents up enough you arrive at [jaxb-bom-2.3.1.pom](https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-bom/2.3.1/jaxb-bom-2.3.1.pom), which does contain the `<version>` tag, as well as the properties. Libraries does retireve this file, but only to get it's properties, we never looked at it's dependencies.
So this PR changes the internal code to store the gathered poms in an ordered array from child to parent as …

fix: [sc-46631] Libraries is returning wrong requirements for maven packages

---

app/models/package_manager/maven.rb
spec/fixtures/proto-google-common-protos-0.1.9.pom
spec/models/package_manager/maven_spec.rb

#3537 introduced a regression on properties where the parent would win in a conflict. This PR corrects that regression and adds a spec to confirm the proper behavior.

Maven: Fix property priority

---

app/controllers/api/projects_controller.rb
app/models/project.rb
spec/requests/api/projects_spec.rb

sometimes clients hitting this endpoint don't need to "destroy and re-create all dependencies for all versions" when syncing the package, so this makes it optional and `false` by default, e.g.:
`/api/npm/some-package/sync?force_sync_dependencies=true`
**NOTE**:  I'm not disabling `force_sync_dependencies` altogether when calling this endpoint because I'm not sure yet what the original motivation for was in https://github.com/librariesio/libraries.io/pull/3059

Api::Projects#sync: parameterize force_sync_dependencies to make optional

---

app/workers/project_updated_worker.rb

Story details: https://app.shortcut.com/tidelift/story/47166
Remove sidekiq_unique_jobs from the ProjectUpdatedWorker. I'm not sure if unique is causing the problem or not. But this will possibly fix, or possibly rule it out. It doesn't look like sidekiq-unique is proc'ing that often according to logs, so I don't expect removing it from this worker will have detrimental impacts.

fix: [sc-47166] Libraries project webhook not 100% reliable

---

app/models/package_manager/hackage.rb

for Hackage packages, Libraries currently scrapes the links in the Table of Contents to store in the "Project#keywords" attribute, but that sometimes raises an error in our Sidekiq worker when the words exceed the Postgres index size. 
this also results in huge keyword arrays for Hackage packages:
it's not clear from the [original PR](https://github.com/librariesio/libraries.io/commit/0ed14e37f2342c6d588b64eee4a153b4a7f49aa8) why the ToC was used, but there's a  more reasonable "Category" list of words/tags on the sidebar that we can use instead:

Hackage: use "Category" words from HTML instead of ToC content for keywords

---

app/models/package_manager/maven/maven_central.rb
spec/models/package_manager/maven/maven_central_spec.rb

e.g. Libraries got an update request for `maven/cljsjs:hammer`, but that is a Clojars package and doesn't exist on Maven Central.

If a project 404s on Maven, return nil early from latest_version_scraped

---

app/controllers/explore_controller.rb

These are some fairly expensive queries to populate the lists of languages and platforms on the `/explore` page. These lists should not be changing very often so this PR introduces a caching layer for those lists to help reduce db usage.

Cache Popular Languages and Platforms for Explore Page

---

app/models/dependency.rb
db/migrate/20250403234300_enable_uuid_extension.rb
db/migrate/20250403234330_add_new_id_to_dependencies.rb
db/schema.rb

This is step one in migrating to a uuid id.
next steps are roughly:
* manually add index on id_new and backfill id_new
* push a migration that adds the index and does the backfill (no-op)
* push a migration that swaps id to id_old and id_new to id
* push a migration that drops id_old

Add id_new uuid column to the dependencies table

---

db/migrate/20250403234704_backfill_dependencies_new_id.rb

I feel like this should have failed to run tests if it was going to fail in real life, but whatever.

When extending statement timeout, use safety_assured

---

Gemfile
Gemfile.lock
app/models/package_manager/base.rb
app/models/package_manager/pypi.rb
app/models/project.rb
app/queries/project_status_query.rb
spec/models/package_manager/pypi_spec.rb
spec/models/project_spec.rb
spec/queries/project_status_query_spec.rb
spec/requests/api/projects_spec.rb
spec/requests/api/status_spec.rb

Currently Libraries looks up Pypi projects using 3 lookup names: "FOO-BAR_BAZ" (the requested name), "foo-bar-baz", and "foo_bar_baz".
This PR goes further by using [PEP 503's name normalization rules](https://packaging.python.org/en/latest/specifications/name-normalization/): replace any run of "_-." with a single "-" and lower case it.
I've checked every PyPi Project on Libraries right now, and fetching the normalized name from PyPI's API returns the exact same project for the name in our database, which implies that any PyPi project can be queried by its normalized name (at the very least, this can be guaranteed for the "pypi.org/simple/" API, because of PEP 503).
* `Project`:
* adds a `find_all_with_package_manager!` method that does platform-specific alternate name bulk lookup
* for …

Project: use PEP530 name normalization for PyPi lookups

---

app/models/package_manager/maven/google.rb
spec/models/package_manager/maven/google_spec.rb

The url we use for `Project#check_status` for `PackageManager::Maven::Google` projects is broken, e.g.: `https://dl.google.com/dl/android/maven2/android/arch/core/core-testing`
I haven't determined if it ever worked, but it's forcing us to mark some Google-hosted projects as "Removed". 
This starts using the "maven-metadata.xml" URL for these status checks instead: `https://dl.google.com/dl/android/maven2/android/arch/core/core-testing/maven-metadata.xml`
They take about 500ms-ish for me, but I can't find a better option and there are [relatively few](https://maven.google.com/web/index.html) projects to check anyway.

Use the Maven metadata url for Google Maven status checks.
